import {
  _ as resolveDiscordShouldRequireMention,
  a as normalizeDiscordSlug,
  c as resolveDiscordChannelConfigWithFallback,
  f as resolveDiscordGuildEntry,
  n as isDiscordGroupAllowedByPolicy,
  r as normalizeDiscordAllowList,
  s as resolveDiscordChannelConfig,
  t as allowListMatches,
  u as resolveDiscordCommandAuthorized,
  v as resolveGroupDmAllow,
  y as shouldEmitDiscordReactionNotification,
} from "../../allow-list-DdPHme1x.js";
import {
  n as collectDiscordAuditChannelIds,
  t as auditDiscordChannelPermissions,
} from "../../audit-lxM-EgmA.js";
import { t as discordMessageActions } from "../../channel-actions-CRUXYs02.js";
import {
  n as listDiscordDirectoryPeersLive,
  t as listDiscordDirectoryGroupsLive,
} from "../../directory-live-CvOuJr0v.js";
import { t as createDiscordMessageHandler } from "../../message-handler-Dbs1_AVH.js";
import { i as buildDiscordMediaPayload } from "../../message-utils-prcoeLfb.js";
import { t as resolveDiscordOutboundSessionRoute } from "../../outbound-session-route-CtKNfzdZ.js";
import {
  i as setPresence,
  n as getPresence,
  r as presenceCacheSize,
  t as clearPresences,
} from "../../presence-cache-z1N8MbJ3.js";
import {
  a as resolveDiscordPrivilegedIntentsFromFlags,
  i as probeDiscord,
  n as fetchDiscordApplicationSummary,
  r as parseApplicationIdFromToken,
  t as fetchDiscordApplicationId,
} from "../../probe-C2UFNDLR.js";
import {
  a as createDiscordNativeCommand,
  i as waitForDiscordGatewayPluginRegistration,
  n as createDiscordGatewayPlugin,
  o as registerDiscordListener,
  r as resolveDiscordGatewayIntents,
  t as monitorDiscordProvider,
} from "../../provider-mYAvX9gb.js";
import { t as resolveDiscordChannelAllowlist } from "../../resolve-channels-WZV3GAJL.js";
import { t as resolveDiscordUserAllowlist } from "../../resolve-users-CkvSpRd0.js";
import { r as setDiscordRuntime } from "../../runtime-n11XewvP.js";
import {
  a as readDiscordChannelCreateParams,
  c as readDiscordParentIdParam,
  i as requiredGuildPermissionForModerationAction,
  n as isDiscordModerationAction,
  o as readDiscordChannelEditParams,
  r as readDiscordModerationCommand,
  s as readDiscordChannelMoveParams,
  t as handleDiscordAction,
} from "../../runtime-oJHQJikc.js";
import {
  A as removeRoleDiscord,
  B as removeChannelPermissionDiscord,
  D as kickMemberDiscord,
  E as fetchVoiceStatusDiscord,
  F as uploadStickerDiscord,
  I as createChannelDiscord,
  L as deleteChannelDiscord,
  M as timeoutMemberDiscord,
  N as listGuildEmojisDiscord,
  O as listGuildChannelsDiscord,
  P as uploadEmojiDiscord,
  R as editChannelDiscord,
  S as fetchChannelInfoDiscord,
  T as fetchRoleInfoDiscord,
  V as setChannelPermissionDiscord,
  _ as searchMessagesDiscord,
  a as sendTypingDiscord,
  b as banMemberDiscord,
  d as editMessageDiscord,
  f as fetchMessageDiscord,
  g as readMessagesDiscord,
  h as pinMessageDiscord,
  i as removeReactionDiscord,
  j as resolveEventCoverImage,
  k as listScheduledEventsDiscord,
  l as createThreadDiscord,
  m as listThreadsDiscord,
  n as reactMessageDiscord,
  o as sendVoiceMessageDiscord,
  p as listPinsDiscord,
  r as removeOwnReactionsDiscord,
  s as sendWebhookMessageDiscord,
  t as fetchReactionsDiscord,
  u as deleteMessageDiscord,
  v as unpinMessageDiscord,
  w as fetchMemberInfoDiscord,
  x as createScheduledEventDiscord,
  y as addRoleDiscord,
  z as moveChannelDiscord,
} from "../../send-BrvWC0qr.js";
import {
  n as registerBuiltDiscordComponentMessage,
  r as sendDiscordComponentMessage,
  t as editDiscordComponentMessage,
} from "../../send.components-Bp4GRNpd.js";
import {
  n as sendPollDiscord,
  r as sendStickerDiscord,
  t as sendMessageDiscord,
} from "../../send.outbound-CrioyPr2.js";
import {
  A as hasAllGuildPermissionsDiscord,
  G as registerGateway,
  K as unregisterGateway,
  M as hasAnyGuildPermissionDiscord,
  O as fetchChannelPermissionsDiscord,
  U as clearGateways,
  W as getGateway,
  k as fetchMemberGuildPermissionsDiscord,
  w as DiscordSendError,
} from "../../send.shared-Ciix19qx.js";
import {
  a as unbindThreadBindingsBySessionKey,
  i as reconcileAcpThreadBindingsOnStartup,
  n as listThreadBindingsBySessionKey,
  o as resolveDiscordThreadBindingIdleTimeoutMs,
  r as listThreadBindingsForAccount,
  s as resolveDiscordThreadBindingMaxAgeMs,
  t as autoBindSpawnedDiscordSubagent,
} from "../../thread-bindings-DlQfHcQe.js";
import {
  i as resolveThreadBindingThreadName,
  r as resolveThreadBindingIntroText,
  t as formatThreadBindingDurationLabel,
} from "../../thread-bindings-messages-C6JmokKM.js";
import { d as resolveThreadBindingsEnabled } from "../../thread-bindings-policy-d6bhdGnZ.js";
import {
  l as resolveThreadBindingPersona,
  u as resolveThreadBindingPersonaFromRecord,
} from "../../thread-bindings.discord-api-3Lk5SIht.js";
import "../../runtime-api.actions-2cIqmkFN.js";
import {
  i as testing,
  n as createThreadBindingManager,
  r as getThreadBindingManager,
  t as createNoopThreadBindingManager,
} from "../../thread-bindings.manager-fdDI3Boz.js";
import "../../runtime-api.lookup-DRL4LMrc.js";
import {
  n as setThreadBindingMaxAgeBySessionKey,
  t as setThreadBindingIdleTimeoutBySessionKey,
} from "../../thread-bindings.session-updates-BMUfEqde.js";
import {
  C as resolveThreadBindingIdleTimeoutMs,
  E as resolveThreadBindingMaxAgeMs,
  T as resolveThreadBindingMaxAgeExpiresAt,
  d as isRecentlyUnboundThreadWebhookMessage,
  w as resolveThreadBindingInactivityExpiresAt,
} from "../../thread-bindings.state-Da_kQ-2B.js";
import {
  a as resolveDiscordReplyTarget,
  l as sanitizeDiscordThreadName,
} from "../../threading-UQvctHcU.js";
import {
  a as isAbortError,
  c as normalizeDiscordListenerTimeoutMs,
  i as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  n as DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS,
  o as mergeAbortSignals,
  r as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  s as normalizeDiscordInboundWorkerTimeoutMs,
  t as DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS,
  u as runDiscordTaskWithTimeout,
} from "../../timeouts-Bj-qI9VL.js";
import "../../runtime-api.monitor-B2uTI4VE.js";
import "../../runtime-api.send-CProM8iE.js";
import "../../runtime-api.threads-1sLX3hQw.js";
export {
  DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS,
  DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS,
  DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  DiscordSendError,
  testing as __testing,
  testing,
  addRoleDiscord,
  allowListMatches,
  auditDiscordChannelPermissions,
  autoBindSpawnedDiscordSubagent,
  banMemberDiscord,
  buildDiscordMediaPayload,
  clearGateways,
  clearPresences,
  collectDiscordAuditChannelIds,
  createChannelDiscord,
  createDiscordGatewayPlugin,
  createDiscordMessageHandler,
  createDiscordNativeCommand,
  createNoopThreadBindingManager,
  createScheduledEventDiscord,
  createThreadBindingManager,
  createThreadDiscord,
  deleteChannelDiscord,
  deleteMessageDiscord,
  discordMessageActions,
  editChannelDiscord,
  editDiscordComponentMessage,
  editMessageDiscord,
  fetchChannelInfoDiscord,
  fetchChannelPermissionsDiscord,
  fetchDiscordApplicationId,
  fetchDiscordApplicationSummary,
  fetchMemberGuildPermissionsDiscord,
  fetchMemberInfoDiscord,
  fetchMessageDiscord,
  fetchReactionsDiscord,
  fetchRoleInfoDiscord,
  fetchVoiceStatusDiscord,
  formatThreadBindingDurationLabel,
  getGateway,
  getPresence,
  getThreadBindingManager,
  handleDiscordAction,
  hasAllGuildPermissionsDiscord,
  hasAnyGuildPermissionDiscord,
  isAbortError,
  isDiscordGroupAllowedByPolicy,
  isDiscordModerationAction,
  isRecentlyUnboundThreadWebhookMessage,
  kickMemberDiscord,
  listDiscordDirectoryGroupsLive,
  listDiscordDirectoryPeersLive,
  listGuildChannelsDiscord,
  listGuildEmojisDiscord,
  listPinsDiscord,
  listScheduledEventsDiscord,
  listThreadBindingsBySessionKey,
  listThreadBindingsForAccount,
  listThreadsDiscord,
  mergeAbortSignals,
  monitorDiscordProvider,
  moveChannelDiscord,
  normalizeDiscordAllowList,
  normalizeDiscordInboundWorkerTimeoutMs,
  normalizeDiscordListenerTimeoutMs,
  normalizeDiscordSlug,
  parseApplicationIdFromToken,
  pinMessageDiscord,
  presenceCacheSize,
  probeDiscord,
  reactMessageDiscord,
  readDiscordChannelCreateParams,
  readDiscordChannelEditParams,
  readDiscordChannelMoveParams,
  readDiscordModerationCommand,
  readDiscordParentIdParam,
  readMessagesDiscord,
  reconcileAcpThreadBindingsOnStartup,
  registerBuiltDiscordComponentMessage,
  registerDiscordListener,
  registerGateway,
  removeChannelPermissionDiscord,
  removeOwnReactionsDiscord,
  removeReactionDiscord,
  removeRoleDiscord,
  requiredGuildPermissionForModerationAction,
  resolveDiscordChannelAllowlist,
  resolveDiscordChannelConfig,
  resolveDiscordChannelConfigWithFallback,
  resolveDiscordCommandAuthorized,
  resolveDiscordGatewayIntents,
  resolveDiscordGuildEntry,
  resolveDiscordOutboundSessionRoute,
  resolveDiscordPrivilegedIntentsFromFlags,
  resolveDiscordReplyTarget,
  resolveDiscordShouldRequireMention,
  resolveDiscordThreadBindingIdleTimeoutMs,
  resolveDiscordThreadBindingMaxAgeMs,
  resolveDiscordUserAllowlist,
  resolveEventCoverImage,
  resolveGroupDmAllow,
  resolveThreadBindingIdleTimeoutMs,
  resolveThreadBindingInactivityExpiresAt,
  resolveThreadBindingIntroText,
  resolveThreadBindingMaxAgeExpiresAt,
  resolveThreadBindingMaxAgeMs,
  resolveThreadBindingPersona,
  resolveThreadBindingPersonaFromRecord,
  resolveThreadBindingThreadName,
  resolveThreadBindingsEnabled,
  runDiscordTaskWithTimeout,
  sanitizeDiscordThreadName,
  searchMessagesDiscord,
  sendDiscordComponentMessage,
  sendMessageDiscord,
  sendPollDiscord,
  sendStickerDiscord,
  sendTypingDiscord,
  sendVoiceMessageDiscord,
  sendWebhookMessageDiscord,
  setChannelPermissionDiscord,
  setDiscordRuntime,
  setPresence,
  setThreadBindingIdleTimeoutBySessionKey,
  setThreadBindingMaxAgeBySessionKey,
  shouldEmitDiscordReactionNotification,
  timeoutMemberDiscord,
  unbindThreadBindingsBySessionKey,
  unpinMessageDiscord,
  unregisterGateway,
  uploadEmojiDiscord,
  uploadStickerDiscord,
  waitForDiscordGatewayPluginRegistration,
};
