import {
  n as resolveTelegramAccountConfig,
  t as mergeTelegramAccountConfig,
} from "../../account-config-D_q_Am0A.js";
import { t as inspectTelegramAccount } from "../../account-inspect-Bttu8O3n.js";
import {
  a as resolveDefaultTelegramAccountId,
  c as resolveTelegramPollActionGateState,
  i as resetMissingDefaultWarnFlag,
  n as listEnabledTelegramAccounts,
  o as resolveTelegramAccount,
  r as listTelegramAccountIds,
  s as resolveTelegramMediaRuntimeOptions,
  t as createTelegramActionGate,
} from "../../accounts-BBOSygpA.js";
import {
  n as isNumericTelegramUserId,
  r as normalizeTelegramAllowFromEntry,
  t as isNumericTelegramSenderUserId,
} from "../../allow-from-Byf7JKVc.js";
import {
  a as resolveTelegramGroupRequireMention,
  i as normalizeTelegramMessagingTarget,
  n as collectTelegramStatusIssues,
  o as resolveTelegramGroupToolPolicy,
  r as looksLikeTelegramTargetId,
  s as resolveTelegramAutoThreadId,
  t as telegramPlugin,
} from "../../channel-qGYq-Cu_.js";
import {
  d as resolveTelegramChatLookupFetch,
  l as fetchTelegramChatId,
  t as telegramSetupPlugin,
  u as lookupTelegramChatId,
} from "../../channel.setup-kCV8RH3M.js";
import {
  i as resolveTelegramCustomCommands,
  n as normalizeTelegramCommandDescription,
  r as normalizeTelegramCommandName,
  t as TELEGRAM_COMMAND_NAME_PATTERN,
} from "../../command-config-BM9MYdyK.js";
import {
  c as buildTelegramModelsProviderChannelData,
  d as buildModelsKeyboard,
  f as buildProviderKeyboard,
  g as resolveModelSelection,
  h as parseModelCallbackData,
  l as buildBrowseProvidersButton,
  m as getModelsPageSize,
  p as calculateTotalPages,
  t as buildCommandsPaginationKeyboard,
  u as buildModelSelectionCallbackData,
} from "../../command-ui-_DB96vRI.js";
import {
  n as listTelegramDirectoryPeersFromConfig,
  t as listTelegramDirectoryGroupsFromConfig,
} from "../../directory-config-DBeFOfau.js";
import {
  a as isTelegramExecApprovalHandlerConfigured,
  c as resolveTelegramExecApprovalTarget,
  d as shouldSuppressLocalTelegramExecApprovalPrompt,
  i as isTelegramExecApprovalClientEnabled,
  l as shouldHandleTelegramExecApprovalRequest,
  n as isTelegramExecApprovalApprover,
  o as isTelegramExecApprovalTargetRecipient,
  r as isTelegramExecApprovalAuthorizedSender,
  s as resolveTelegramExecApprovalConfig,
  t as getTelegramExecApprovalApprovers,
  u as shouldInjectTelegramExecApprovalButtons,
} from "../../exec-approvals--6hqHgmF.js";
import {
  i as resolveTelegramInlineButtonsScopeFromCapabilities,
  n as resolveTelegramInlineButtonsConfigScope,
  r as resolveTelegramInlineButtonsScope,
  t as isTelegramInlineButtonsEnabled,
} from "../../inline-buttons-CwHG__q7.js";
import {
  i as telegramOutbound,
  r as sendTelegramPayloadMessages,
  t as TELEGRAM_TEXT_CHUNK_LIMIT,
} from "../../outbound-adapter-CvNvgoM8.js";
import {
  a as buildTelegramExecApprovalPendingPayload,
  n as resetTelegramProbeFetcherCacheForTests,
  o as shouldSuppressTelegramExecApprovalForwardingFallback,
  t as probeTelegram,
} from "../../probe-DCMHJuy6.js";
import { t as resolveTelegramReactionLevel } from "../../reaction-level-VyxXTXmy.js";
import { t as collectTelegramSecurityAuditFindings } from "../../security-audit-BBoPR3Z1.js";
import {
  A as buildTelegramThreadParams,
  B as resolveTelegramForumThreadId,
  E as buildTelegramGroupPeerId,
  F as resetTelegramForumFlagCacheForTest,
  G as resolveTelegramThreadSpec,
  J as buildSenderLabel,
  M as describeReplyTarget,
  N as extractTelegramForumFlag,
  O as buildTelegramParentPeer,
  Q as hasBotMention,
  R as resolveTelegramDirectPeerId,
  T as buildTelegramGroupFrom,
  U as resolveTelegramReplyId,
  V as resolveTelegramGroupAllowFromContext,
  W as resolveTelegramStreamMode,
  X as extractTelegramLocation,
  Y as buildSenderName,
  Z as getTelegramTextParts,
  bt as parseTelegramReplyToMessageId,
  ct as markdownToTelegramChunks,
  et as isBinaryContent,
  j as buildTypingThreadParams,
  k as buildTelegramRoutingTarget,
  lt as markdownToTelegramHtml,
  mt as splitTelegramHtmlChunks,
  q as withResolvedTelegramForumFlag,
  rt as resolveTelegramMediaPlaceholder,
  st as escapeTelegramHtml,
  tt as normalizeForwardedContext,
  ut as markdownToTelegramHtmlChunks,
  vt as normalizeTelegramReplyToMessageId,
  w as buildGroupLabel,
  xt as parseTelegramThreadId,
  z as resolveTelegramForumFlag,
} from "../../sent-message-cache-D-3cw6_g.js";
import { t as describeStickerImage } from "../../sticker-cache-BpYXQ2f-.js";
import {
  a as parseTelegramTarget,
  n as normalizeTelegramChatId,
  o as resolveTelegramTargetChatType,
  r as normalizeTelegramLookupTarget,
  s as stripTelegramInternalPrefixes,
  t as isNumericTelegramChatId,
} from "../../targets-Cb32iLpC.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-B6kdtLDb.js";
import {
  d as getAllCachedStickers,
  f as getCacheStats,
  h as searchStickers,
  p as getCachedSticker,
  u as cacheSticker,
} from "../../topic-name-cache-BWDqVym9.js";
import {
  c as writeTelegramUpdateOffset,
  o as readTelegramUpdateOffset,
  r as deleteTelegramUpdateOffset,
} from "../../update-offset-store-CnRvohsv.js";
export {
  TELEGRAM_COMMAND_NAME_PATTERN,
  TELEGRAM_TEXT_CHUNK_LIMIT,
  buildBrowseProvidersButton,
  buildCommandsPaginationKeyboard,
  buildGroupLabel,
  buildModelSelectionCallbackData,
  buildModelsKeyboard,
  buildProviderKeyboard,
  buildSenderLabel,
  buildSenderName,
  buildTelegramExecApprovalPendingPayload,
  buildTelegramGroupFrom,
  buildTelegramGroupPeerId,
  buildTelegramModelsProviderChannelData,
  buildTelegramParentPeer,
  buildTelegramRoutingTarget,
  buildTelegramThreadParams,
  buildTypingThreadParams,
  cacheSticker,
  calculateTotalPages,
  collectTelegramSecurityAuditFindings,
  collectTelegramStatusIssues,
  createTelegramActionGate,
  deleteTelegramUpdateOffset,
  describeReplyTarget,
  describeStickerImage,
  escapeTelegramHtml,
  extractTelegramForumFlag,
  extractTelegramLocation,
  fetchTelegramChatId,
  getAllCachedStickers,
  getCacheStats,
  getCachedSticker,
  getModelsPageSize,
  getTelegramExecApprovalApprovers,
  getTelegramTextParts,
  hasBotMention,
  inspectTelegramAccount,
  isBinaryContent,
  isNumericTelegramChatId,
  isNumericTelegramSenderUserId,
  isNumericTelegramUserId,
  isTelegramExecApprovalApprover,
  isTelegramExecApprovalAuthorizedSender,
  isTelegramExecApprovalClientEnabled,
  isTelegramExecApprovalHandlerConfigured,
  isTelegramExecApprovalTargetRecipient,
  isTelegramInlineButtonsEnabled,
  listEnabledTelegramAccounts,
  listTelegramAccountIds,
  listTelegramDirectoryGroupsFromConfig,
  listTelegramDirectoryPeersFromConfig,
  looksLikeTelegramTargetId,
  lookupTelegramChatId,
  markdownToTelegramChunks,
  markdownToTelegramHtml,
  markdownToTelegramHtmlChunks,
  mergeTelegramAccountConfig,
  normalizeForwardedContext,
  normalizeTelegramAllowFromEntry,
  normalizeTelegramChatId,
  normalizeTelegramCommandDescription,
  normalizeTelegramCommandName,
  normalizeTelegramLookupTarget,
  normalizeTelegramMessagingTarget,
  normalizeTelegramReplyToMessageId,
  parseModelCallbackData,
  parseTelegramReplyToMessageId,
  parseTelegramTarget,
  parseTelegramThreadId,
  parseTelegramTopicConversation,
  probeTelegram,
  readTelegramUpdateOffset,
  resetMissingDefaultWarnFlag,
  resetTelegramForumFlagCacheForTest,
  resetTelegramProbeFetcherCacheForTests,
  resolveDefaultTelegramAccountId,
  resolveModelSelection,
  resolveTelegramAccount,
  resolveTelegramAccountConfig,
  resolveTelegramAutoThreadId,
  resolveTelegramChatLookupFetch,
  resolveTelegramCustomCommands,
  resolveTelegramDirectPeerId,
  resolveTelegramExecApprovalConfig,
  resolveTelegramExecApprovalTarget,
  resolveTelegramForumFlag,
  resolveTelegramForumThreadId,
  resolveTelegramGroupAllowFromContext,
  resolveTelegramGroupRequireMention,
  resolveTelegramGroupToolPolicy,
  resolveTelegramInlineButtonsConfigScope,
  resolveTelegramInlineButtonsScope,
  resolveTelegramInlineButtonsScopeFromCapabilities,
  resolveTelegramMediaPlaceholder,
  resolveTelegramMediaRuntimeOptions,
  resolveTelegramPollActionGateState,
  resolveTelegramReactionLevel,
  resolveTelegramReplyId,
  resolveTelegramStreamMode,
  resolveTelegramTargetChatType,
  resolveTelegramThreadSpec,
  searchStickers,
  sendTelegramPayloadMessages,
  shouldHandleTelegramExecApprovalRequest,
  shouldInjectTelegramExecApprovalButtons,
  shouldSuppressLocalTelegramExecApprovalPrompt,
  shouldSuppressTelegramExecApprovalForwardingFallback,
  splitTelegramHtmlChunks,
  stripTelegramInternalPrefixes,
  telegramOutbound,
  telegramPlugin,
  telegramSetupPlugin,
  withResolvedTelegramForumFlag,
  writeTelegramUpdateOffset,
};
