import {
  a as streamProxy,
  i as ProxyStreamOptions,
  n as openClawAgentCoreRuntime,
  r as ProxyAssistantMessageEvent,
  t as Agent,
} from "../agent-core-DblDJWw5.js";
import {
  $ as createCompactionSummaryMessage,
  $t as ModelChangeEntry,
  A as CollectEntriesResult,
  An as TreePreparation,
  At as CompactResult,
  B as formatSkillInvocation,
  Bn as runAgentLoop,
  Bt as ExecutionError,
  C as getLastAssistantUsage,
  Cn as Skill,
  Ct as BeforeProviderPayloadResult,
  D as BranchPreparation,
  Dn as ToolCallResult,
  Dt as BranchSummaryError,
  E as BranchPathEntry,
  En as ToolCallEvent,
  Et as BranchSummaryEntry,
  F as serializeConversation,
  Fn as TRANSCRIPT_NOT_CONTINUABLE_ERROR_CODE,
  Ft as ContextResult,
  G as BRANCH_SUMMARY_SUFFIX,
  Gn as AgentCoreRuntimeDeps,
  Gt as FileKind,
  H as parseCommandArgs,
  Ht as FileError,
  I as uuidv7,
  In as TranscriptNotContinuableError,
  It as CustomEntry,
  J as HarnessMessage,
  Jn as resolveAgentCoreStreamFn,
  Jt as GenerateBranchSummaryOptions,
  K as COMPACTION_SUMMARY_PREFIX,
  Kn as AgentCoreStreamRuntimeDeps,
  Kt as FileOperations,
  L as InMemorySessionStorage,
  Ln as AgentEventSink,
  Lt as CustomMessageEntry,
  M as collectEntriesForBranchSummaryFromBranches,
  Mn as CoreAgentHarness,
  Mt as CompactionError,
  N as generateBranchSummary,
  Nn as Session,
  Nt as CompactionErrorCode,
  O as BranchSummaryDetails,
  On as ToolResultEvent,
  Ot as BranchSummaryErrorCode,
  P as prepareBranchEntries,
  Pn as buildSessionContext,
  Pt as ContextEvent,
  Q as createBranchSummaryMessage,
  Qt as MessageEntry,
  R as JsonlSessionStorage,
  Rn as agentLoop,
  Rt as ExecutionEnv,
  S as generateSummary,
  Sn as Shell,
  St as BeforeProviderPayloadEvent,
  T as shouldCompact,
  Tn as ThinkingLevelSelectEvent,
  Tt as BeforeProviderRequestResult,
  U as substituteArgs,
  Un as AgentOptions,
  Ut as FileErrorCode,
  V as formatPromptTemplateInvocation,
  Vn as runAgentLoopContinue,
  Vt as ExecutionErrorCode,
  W as BRANCH_SUMMARY_PREFIX,
  Wn as AgentCoreCompletionRuntimeDeps,
  Wt as FileInfo,
  X as bashExecutionToText,
  Xt as LabelEntry,
  Y as asAgentMessage,
  Yt as JsonlSessionMetadata,
  Z as convertToLlm,
  Zt as LeafEntry,
  _ as compact,
  _n as SessionStorage,
  _t as AgentHarnessResources,
  a as TruncationResult,
  an as ResourcesUpdateEvent,
  at as validateToolCall,
  b as findCutPoint,
  bn as SessionTreeEvent,
  bt as BeforeAgentStartEvent,
  c as truncateLine,
  cn as SessionBeforeCompactResult,
  ct as AbortResult,
  d as CompactionPreparation,
  dn as SessionCompactEvent,
  dt as AgentHarnessErrorCode,
  en as ModelSelectEvent,
  et as createCustomMessage,
  f as CompactionResult,
  fn as SessionContext,
  ft as AgentHarnessEvent,
  g as calculateContextTokens,
  gn as SessionMetadata,
  gt as AgentHarnessPhase,
  h as DEFAULT_COMPACTION_SETTINGS,
  hn as SessionInfoEntry,
  ht as AgentHarnessOwnEvent,
  i as TruncationOptions,
  in as QueueUpdateEvent,
  it as validateToolArguments,
  j as collectEntriesForBranchSummary,
  jn as toError,
  jt as CompactionEntry,
  k as CollectBranchPathEntriesResult,
  kn as ToolResultPatch,
  kt as BranchSummaryResult,
  l as truncateTail,
  ln as SessionBeforeTreeEvent,
  lt as AfterProviderResponseEvent,
  m as ContextUsageEstimate,
  mn as SessionErrorCode,
  mt as AgentHarnessOptions,
  n as DEFAULT_MAX_LINES,
  nn as PendingSessionWrite,
  nt as killProcessTree,
  o as formatSize,
  on as SavePointEvent,
  ot as NodeExecutionEnv,
  p as CompactionSettings,
  pn as SessionError,
  pt as AgentHarnessEventResultMap,
  q as COMPACTION_SUMMARY_SUFFIX,
  qn as resolveAgentCoreCompleteFn,
  qt as FileSystem,
  r as GREP_MAX_LINE_LENGTH,
  rn as PromptTemplate,
  rt as signalProcessTree,
  s as truncateHead,
  sn as SessionBeforeCompactEvent,
  st as AbortEvent,
  t as DEFAULT_MAX_BYTES,
  tn as NavigateTreeResult,
  tt as KillProcessTreeOptions,
  u as CompactionDetails,
  un as SessionBeforeTreeResult,
  ut as AgentHarnessError,
  v as estimateContextTokens,
  vn as SessionTreeEntry,
  vt as AgentHarnessStreamOptions,
  w as prepareCompaction,
  wn as ThinkingLevelChangeEntry,
  wt as BeforeProviderRequestEvent,
  x as findTurnStartIndex,
  xn as SettledEvent,
  xt as BeforeAgentStartResult,
  y as estimateTokens,
  yn as SessionTreeEntryBase,
  yt as AgentHarnessStreamOptionsPatch,
  z as loadJsonlSessionMetadata,
  zn as agentLoopContinue,
  zt as ExecutionEnvExecOptions,
} from "../index--Mxo3qUC.js";
import { n as err, r as ok, t as Result } from "../result-Op6FTu_Y.js";
import {
  C as QueueMode,
  D as ToolExecutionMode,
  E as ThinkingLevel,
  S as PrepareNextTurnContext,
  T as StreamFn,
  _ as BranchSummaryMessage,
  a as AgentLoopConfig,
  b as CustomMessage,
  c as AgentState,
  d as AgentToolProgress,
  f as AgentToolResult,
  g as BeforeToolCallResult,
  h as BeforeToolCallContext,
  i as AgentEvent,
  l as AgentTool,
  m as BashExecutionMessage,
  n as AfterToolCallResult,
  o as AgentLoopTurnUpdate,
  p as AgentToolUpdateCallback,
  r as AgentContext,
  s as AgentMessage,
  t as AfterToolCallContext,
  u as AgentToolCall,
  v as CompactionSummaryMessage,
  w as ShouldStopAfterTurnContext,
  x as DeferredToolCallContext,
  y as CustomAgentMessages,
} from "../types-JQFrjdua.js";
export {
  AbortEvent,
  AbortResult,
  AfterProviderResponseEvent,
  AfterToolCallContext,
  AfterToolCallResult,
  Agent,
  AgentContext,
  AgentCoreCompletionRuntimeDeps,
  AgentCoreRuntimeDeps,
  AgentCoreStreamRuntimeDeps,
  AgentEvent,
  AgentEventSink,
  CoreAgentHarness as AgentHarness,
  CoreAgentHarness,
  AgentHarnessError,
  AgentHarnessErrorCode,
  AgentHarnessEvent,
  AgentHarnessEventResultMap,
  AgentHarnessOptions,
  AgentHarnessOwnEvent,
  AgentHarnessPhase,
  AgentHarnessResources,
  AgentHarnessStreamOptions,
  AgentHarnessStreamOptionsPatch,
  AgentLoopConfig,
  AgentLoopTurnUpdate,
  AgentMessage,
  AgentOptions,
  AgentState,
  AgentTool,
  AgentToolCall,
  AgentToolProgress,
  AgentToolResult,
  AgentToolUpdateCallback,
  BRANCH_SUMMARY_PREFIX,
  BRANCH_SUMMARY_SUFFIX,
  BashExecutionMessage,
  BeforeAgentStartEvent,
  BeforeAgentStartResult,
  BeforeProviderPayloadEvent,
  BeforeProviderPayloadResult,
  BeforeProviderRequestEvent,
  BeforeProviderRequestResult,
  BeforeToolCallContext,
  BeforeToolCallResult,
  type BranchPathEntry,
  type BranchPreparation,
  type BranchSummaryDetails,
  BranchSummaryEntry,
  BranchSummaryError,
  BranchSummaryErrorCode,
  BranchSummaryMessage,
  BranchSummaryResult,
  COMPACTION_SUMMARY_PREFIX,
  COMPACTION_SUMMARY_SUFFIX,
  type CollectBranchPathEntriesResult,
  type CollectEntriesResult,
  CompactResult,
  type CompactionDetails,
  CompactionEntry,
  CompactionError,
  CompactionErrorCode,
  CompactionPreparation,
  type CompactionResult,
  CompactionSettings,
  CompactionSummaryMessage,
  ContextEvent,
  ContextResult,
  type ContextUsageEstimate,
  CustomAgentMessages,
  CustomEntry,
  CustomMessage,
  CustomMessageEntry,
  DEFAULT_COMPACTION_SETTINGS,
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  DeferredToolCallContext,
  ExecutionEnv,
  ExecutionEnvExecOptions,
  ExecutionError,
  ExecutionErrorCode,
  FileError,
  FileErrorCode,
  FileInfo,
  FileKind,
  FileOperations,
  FileSystem,
  GREP_MAX_LINE_LENGTH,
  GenerateBranchSummaryOptions,
  HarnessMessage,
  InMemorySessionStorage,
  JsonlSessionMetadata,
  JsonlSessionStorage,
  KillProcessTreeOptions,
  LabelEntry,
  LeafEntry,
  MessageEntry,
  ModelChangeEntry,
  ModelSelectEvent,
  NavigateTreeResult,
  NodeExecutionEnv,
  PendingSessionWrite,
  PrepareNextTurnContext,
  PromptTemplate,
  ProxyAssistantMessageEvent,
  ProxyStreamOptions,
  QueueMode,
  QueueUpdateEvent,
  ResourcesUpdateEvent,
  type Result,
  SavePointEvent,
  Session,
  SessionBeforeCompactEvent,
  SessionBeforeCompactResult,
  SessionBeforeTreeEvent,
  SessionBeforeTreeResult,
  SessionCompactEvent,
  SessionContext,
  SessionError,
  SessionErrorCode,
  SessionInfoEntry,
  SessionMetadata,
  SessionStorage,
  SessionTreeEntry,
  SessionTreeEntryBase,
  SessionTreeEvent,
  SettledEvent,
  Shell,
  ShouldStopAfterTurnContext,
  Skill,
  StreamFn,
  TRANSCRIPT_NOT_CONTINUABLE_ERROR_CODE,
  ThinkingLevel,
  ThinkingLevelChangeEntry,
  ThinkingLevelSelectEvent,
  ToolCallEvent,
  ToolCallResult,
  ToolExecutionMode,
  ToolResultEvent,
  ToolResultPatch,
  TranscriptNotContinuableError,
  TreePreparation,
  TruncationOptions,
  TruncationResult,
  agentLoop,
  agentLoopContinue,
  asAgentMessage,
  bashExecutionToText,
  buildSessionContext,
  calculateContextTokens,
  collectEntriesForBranchSummary,
  collectEntriesForBranchSummaryFromBranches,
  compact,
  convertToLlm,
  createBranchSummaryMessage,
  createCompactionSummaryMessage,
  createCustomMessage,
  err,
  estimateContextTokens,
  estimateTokens,
  findCutPoint,
  findTurnStartIndex,
  formatPromptTemplateInvocation,
  formatSize,
  formatSkillInvocation,
  generateBranchSummary,
  generateSummary,
  getLastAssistantUsage,
  killProcessTree,
  loadJsonlSessionMetadata,
  ok,
  openClawAgentCoreRuntime,
  parseCommandArgs,
  prepareBranchEntries,
  prepareCompaction,
  resolveAgentCoreCompleteFn,
  resolveAgentCoreStreamFn,
  runAgentLoop,
  runAgentLoopContinue,
  serializeConversation,
  shouldCompact,
  signalProcessTree,
  streamProxy,
  substituteArgs,
  toError,
  truncateHead,
  truncateLine,
  truncateTail,
  uuidv7,
  validateToolArguments,
  validateToolCall,
};
