import {
  d as resolveAgentIdentity,
  f as resolveEffectiveMessagesConfig,
  g as resolveResponsePrefix,
  h as resolveMessagePrefix,
  m as resolveIdentityNamePrefix,
  p as resolveHumanDelayConfig,
  u as resolveAckReaction,
} from "../ack-reactions-CPe7vd_e.js";
import { t as resolveOpenClawAgentDir } from "../agent-dir-compat-ochOeoeD.js";
import {
  A as resolveAgentAvatar,
  C as ToolOwnerRef,
  D as resolveModelCatalogScope,
  E as ToolUnavailableReason,
  M as resolveAuthStorePathForDisplay,
  O as resolveProviderDiscoveryProviderIdsForCatalogScope,
  S as ToolExecutorRef,
  T as ToolPlanEntry,
  _ as ToolAvailabilityContext,
  a as toToolProtocolDescriptors,
  b as ToolAvailabilitySignal,
  c as ToolPlanContractError,
  d as evaluateToolAvailability,
  f as BuildToolPlanOptions,
  g as JsonValue,
  h as JsonPrimitive,
  i as toToolProtocolDescriptor,
  j as resolvePublicAgentAvatarSource,
  k as AgentAvatarResolution,
  l as defineToolDescriptor,
  m as JsonObject,
  n as agentCommandFromIngress,
  o as buildToolPlan,
  p as HiddenToolPlanEntry,
  r as testing,
  s as formatToolExecutorRef,
  t as agentCommand,
  u as defineToolDescriptors,
  v as ToolAvailabilityDiagnostic,
  w as ToolPlan,
  x as ToolDescriptor,
  y as ToolAvailabilityExpression,
} from "../agent-runtime-Dvsk-z1N.js";
import {
  A as listAgentIds,
  C as resolveSessionAgentIds,
  D as setAgentEffectiveModelPrimary,
  E as resolveSubagentModelFallbacksOverride,
  F as resolveDefaultAgentDir,
  I as resolveDefaultAgentId,
  L as hasSessionAutoModelFallbackProvenance,
  M as resolveAgentContextLimits,
  N as resolveAgentDir,
  O as ResolvedAgentConfig,
  P as resolveAgentWorkspaceDir,
  S as resolveSessionAgentId,
  T as resolveSubagentModelConfigSelectionResult,
  _ as resolveAgentSkillsFilter,
  a as clearAutoFallbackPrimaryProbeSelection,
  b as resolveFallbackAgentId,
  c as hasLegacyAutoFallbackWithoutOrigin,
  d as resolveAgentExecutionContract,
  f as resolveAgentExplicitModelPrimary,
  g as resolveAgentModelPrimary,
  h as resolveAgentModelFallbacksOverride,
  i as SubagentModelConfigSelectionSource,
  j as resolveAgentConfig,
  k as listAgentEntries,
  l as markAutoFallbackPrimaryProbe,
  m as resolveAgentIdsByWorkspacePath,
  n as AutoFallbackPrimaryProbe,
  o as entryMatchesAutoFallbackPrimaryProbe,
  p as resolveAgentIdByWorkspacePath,
  r as SubagentModelConfigSelectionResult,
  s as hasConfiguredModelFallbacks,
  t as AgentModelPrimaryWriteTarget,
  u as resolveAgentEffectiveModelPrimary,
  v as resolveAutoFallbackPrimaryProbe,
  w as resolveSubagentModelConfigSelection,
  x as resolveRunModelFallbacksOverride,
  y as resolveEffectiveModelFallbacks,
} from "../agent-scope-C-j0oyUV.js";
import {
  c as stripDowngradedToolCallText,
  u as stripMinimaxToolCallXml,
} from "../assistant-visible-text-Bo-pttz5.js";
import {
  A as resolveProviderAuthAliasMap,
  C as resolveAuthProfileDisplayLabel,
  D as resolveAuthProfileOrderWithMetadata,
  E as resolveAuthProfileOrder,
  I as CLAUDE_CLI_PROFILE_ID,
  L as CODEX_CLI_PROFILE_ID,
  M as AuthCredentialReasonCode,
  O as ProviderAuthAliasLookupParams,
  P as TokenExpiryState,
  S as formatAuthDoctorHint,
  T as resolveAuthProfileEligibility,
  _ as upsertAuthProfileWithLock,
  a as markAuthProfileFailure,
  b as refreshOAuthCredentialForRuntime,
  c as clearExpiredCooldowns,
  d as repairOAuthProfileIdMismatch,
  f as suggestOAuthProfileIdForLegacyDefault,
  g as upsertAuthProfile,
  h as setAuthProfileOrder,
  i as markAuthProfileCooldown,
  j as resolveProviderIdForAuth,
  k as resetProviderAuthAliasMapCacheForTest,
  l as getSoonestCooldownExpiry,
  n as clearAuthProfileCooldown,
  o as resolveProfileUnusableUntilForDisplay,
  p as markAuthProfileSuccess,
  r as markAuthProfileBlockedUntil,
  s as resolveProfilesUnavailableReason,
  t as calculateAuthProfileCooldownMs,
  u as isProfileInCooldown,
  v as dedupeProfileIds,
  w as AuthProfileEligibilityReasonCode,
  x as resolveApiKeyForProfile,
  y as listProfilesForProvider,
} from "../auth-profiles-BzT-kajT.js";
import {
  C as readReactionParams,
  D as scheduleToolProgress,
  E as readStringParam,
  O as stringifyToolPayload,
  S as readPositiveIntegerParam,
  T as readStringOrNumberParam,
  _ as parseAvailableTags,
  a as PublicToolProgress,
  b as readNonNegativeIntegerParam,
  c as ToolAuthorizationError,
  d as createActionGate,
  f as emitToolProgress,
  g as normalizeToolModelOverride,
  h as imageResultFromFile,
  i as AvailableTag,
  k as toolProgressResult,
  l as ToolInputError,
  m as imageResult,
  n as AgentToolWithMeta,
  o as ReactionParams,
  p as failedTextResult,
  r as AnyAgentTool,
  s as StringParamOptions,
  t as ActionGate,
  u as asToolParamsRecord,
  v as payloadTextResult,
  w as readStringArrayParam,
  x as readNumberParam,
  y as readFiniteNumberParam,
} from "../common-CuQ9SS3Z.js";
import {
  a as normalizeTimestamp,
  c as withNormalizedTimestamp,
  i as formatUserTime,
  n as TimeFormatPreference,
  o as resolveUserTimeFormat,
  r as formatDateStamp,
  s as resolveUserTimezone,
  t as ResolvedTimeFormat,
} from "../date-time-C_aF3jiN.js";
import {
  n as DEFAULT_MODEL,
  r as DEFAULT_PROVIDER,
  t as DEFAULT_CONTEXT_TOKENS,
} from "../defaults-DZhrVvBP.js";
import {
  a as extractAssistantVisibleText,
  c as formatReasoningMessage,
  d as promoteThinkingTagsToBlocks,
  f as sanitizeAssistantVisibleStreamText,
  h as stripModelSpecialTokens,
  i as extractAssistantThinking,
  l as inferToolMetaFromArgs,
  m as stripThinkingTagsFromText,
  n as extractAssistantCommentaryText,
  o as extractThinkingFromTaggedStream,
  p as splitThinkingTaggedText,
  r as extractAssistantText,
  s as extractThinkingFromTaggedText,
  t as THINKING_TAG_SCAN_RE,
  u as isAssistantMessage,
} from "../embedded-agent-utils-Dd_88m8_.js";
import {
  A as EnvApiKeyResult,
  C as ProviderAuthError,
  D as isProviderAuthError,
  E as isMissingProviderAuthError,
  O as requireApiKey,
  S as MissingProviderAuthError,
  T as formatMissingAuthError,
  _ as resolveModelAuthMode,
  a as applyAuthHeaderOverride,
  b as resolveUsableCustomProviderApiKey,
  c as canUseProfileAsProviderEntryApiKey,
  d as getCustomProviderApiKey,
  f as hasAvailableAuthForProvider,
  g as resolveApiKeyForProvider,
  h as hasUsableCustomProviderApiKey,
  i as RuntimeProviderAuthLookup,
  j as resolveEnvApiKey,
  k as resolveAwsSdkEnvVarName,
  l as createRuntimeProviderAuthLookup,
  m as hasSyntheticLocalProviderAuthConfig,
  n as ProviderCredentialPrecedence,
  o as applyLocalNoAuthHeaderOverride,
  p as hasRuntimeAvailableProviderAuth,
  r as ProviderEntryApiKeyBindingResolution,
  s as applySecretRefHeaderSentinels,
  t as ModelAuthMode,
  u as getApiKeyForModel,
  v as resolveProviderEntryApiKeyBinding,
  w as ResolvedProviderAuth,
  x as shouldPreferExplicitConfigApiKeyAuth,
  y as resolveProviderEntryApiKeyProfileReference,
} from "../model-auth-DQnRyl6R.js";
import {
  _ as resolveNonEnvSecretRefHeaderValueMarker,
  a as NON_ENV_SECRETREF_MARKER,
  c as SECRETREF_ENV_HEADER_MARKER_PREFIX,
  d as isNonSecretApiKeyMarker,
  f as isOAuthApiKeyMarker,
  g as resolveNonEnvSecretRefApiKeyMarker,
  h as resolveEnvSecretRefHeaderValueMarker,
  i as MINIMAX_OAUTH_MARKER,
  l as isAwsSdkAuthMarker,
  m as listKnownNonSecretApiKeyMarkers,
  n as CUSTOM_LOCAL_AUTH_MARKER,
  o as OAUTH_API_KEY_MARKER_PREFIX,
  p as isSecretRefHeaderValueMarker,
  r as GCP_VERTEX_CREDENTIALS_MARKER,
  s as OLLAMA_LOCAL_AUTH_MARKER,
  t as CODEX_APP_SERVER_AUTH_MARKER,
  u as isKnownEnvApiKeyMarker,
  v as resolveOAuthApiKeyMarker,
} from "../model-auth-markers-BhPapeFt.js";
import {
  a as modelSupportsDocument,
  c as resetModelCatalogCacheForTest,
  d as findModelInCatalog,
  f as modelSupportsInput,
  i as loadModelCatalogSnapshot,
  l as setModelCatalogImportForTest,
  n as loadManifestModelCatalog,
  o as modelSupportsVision,
  r as loadModelCatalog,
  s as resetModelCatalogCache,
  t as LoadModelCatalogParams,
  u as findModelCatalogEntry,
} from "../model-catalog-BMUFGpPy.js";
import {
  n as ModelCatalogSnapshot,
  r as ModelInputType,
  t as ModelCatalogEntry,
} from "../model-catalog.types-DCVmZqMZ.js";
import {
  C as resolveConfiguredModelRef,
  D as resolveThinkingDefaultWithRuntimeCatalog,
  E as resolveThinkingDefault,
  O as resolveDefaultModelForAgent,
  S as resolveBareModelDefaultProvider,
  T as resolveModelRefFromString,
  _ as buildConfiguredModelCatalog,
  a as resolveAllowedModelRef,
  b as inferUniqueProviderFromConfiguredModels,
  c as resolvePersistedModelRef,
  d as resolveReasoningDefault,
  f as resolveSubagentSpawnModelSelection,
  g as buildConfiguredAllowlistKeys,
  h as ModelRefStatus,
  i as normalizeStoredOverrideModel,
  k as resolveSubagentConfiguredModelSelection,
  l as resolvePersistedOverrideModelRef,
  m as ModelAliasIndex,
  n as canonicalizeCaseOnlyCatalogModelRef,
  o as resolveAllowlistModelKey,
  p as isCliProvider,
  r as getModelRefStatus,
  s as resolveConfiguredSubagentSpawnModelSelection,
  t as buildAllowedModelSet,
  u as resolvePersistedSelectedModelRef,
  v as buildModelAliasIndex,
  w as resolveHooksGmailModel,
  x as normalizeModelSelection,
  y as inferUniqueProviderFromCatalog,
} from "../model-selection-BItXqx03.js";
import {
  a as legacyModelKey,
  c as normalizeProviderId,
  i as findNormalizedProviderValue,
  l as normalizeProviderIdForAuth,
  n as ModelRef,
  o as modelKey,
  r as findNormalizedProviderKey,
  s as normalizeModelRef,
  t as ModelManifestNormalizationContext,
  u as parseModelRef,
} from "../model-selection-normalize-Bv4Vn4_c.js";
import {
  a as resolveSandboxPath,
  i as resolveSandboxInputPath,
  n as assertSandboxPath,
  o as resolveSandboxedMediaSource,
  r as resolveAllowedManagedMediaPath,
  t as assertMediaNotDataUrl,
} from "../sandbox-paths-DAVxv7sM.js";
import { a as resolveAgentIdFromSessionKey } from "../session-key-COxKqlXJ.js";
import {
  a as findPersistedAuthProfileCredential,
  c as loadAuthProfileStoreForSecretsRuntime,
  d as resolvePersistedAuthProfileOwnerAgentDir,
  f as saveAuthProfileStore,
  i as ensureAuthProfileStoreWithoutExternalProfiles,
  l as loadAuthProfileStoreWithoutExternalProfiles,
  n as ensureAuthProfileStore,
  o as loadAuthProfileStore,
  s as loadAuthProfileStoreForRuntime,
  t as clearRuntimeAuthProfileStoreSnapshots,
  u as replaceRuntimeAuthProfileStoreSnapshots,
} from "../store-TQsl5_Yq.js";
import { r as ThinkLevel } from "../thinking.shared-0bZWY054.js";
import { n as textResult, t as jsonResult } from "../tool-results-DtJKrUlx.js";
import {
  A as setTtsProvider,
  C as resolveTtsProviderOrder,
  D as setTtsEnabled,
  E as setTtsAutoMode,
  F as textToSpeechStream,
  I as textToSpeechTelephony,
  M as synthesizeSpeech,
  N as testApi,
  O as setTtsMaxLength,
  P as textToSpeech,
  S as resolveTtsPrefsPath,
  T as setSummarizationEnabled,
  _ as listTtsPersonas,
  a as TtsSynthesisStreamResult,
  b as resolveTtsAutoMode,
  c as getLastTtsAttempt,
  d as getTtsPersona,
  f as getTtsProvider,
  g as listSpeechVoices,
  h as isTtsProviderConfigured,
  i as TtsSynthesisResult,
  j as streamSpeech,
  k as setTtsPersona,
  l as getResolvedSpeechProviderConfig,
  m as isTtsEnabled,
  n as TtsResult,
  o as TtsTelephonyResult,
  p as isSummarizationEnabled,
  r as TtsStreamResult,
  s as buildTtsSystemPromptHint,
  u as getTtsMaxLength,
  v as maybeApplyTtsToPayload,
  w as setLastTtsAttempt,
  x as resolveTtsConfig,
  y as resolveExplicitTtsOverrides,
} from "../tts-runtime-O3eYgWAr.js";
import {
  a as optionalPositiveIntegerSchema,
  i as optionalNonNegativeIntegerSchema,
  n as channelTargetsSchema,
  o as optionalStringEnum,
  r as optionalFiniteNumberSchema,
  s as stringEnum,
  t as channelTargetSchema,
} from "../typebox-WKHUFEwH.js";
import {
  a as AuthProfileFailureReason,
  c as OAuthCredential,
  d as TokenCredential,
  i as AuthProfileCredential,
  n as AuthProfileBlockedReason,
  o as AuthProfileIdRepairResult,
  r as AuthProfileBlockedSource,
  s as AuthProfileStore,
  t as ApiKeyCredential,
  u as ProfileUsageStats,
} from "../types-Dzb4Vh4b.js";
import {
  Gu as PreparedSimpleCompletionModelForAgent,
  Iu as BlockReplyChunking,
  Ju as prepareSimpleCompletionModel,
  Ku as SimpleCompletionModelOptions,
  Ll as TtsDirectiveOverrides,
  Lu as EmbeddedBlockChunker,
  Rl as TtsDirectiveParseResult,
  Uu as AgentSimpleCompletionSelection,
  Wu as PreparedSimpleCompletionModel,
  Xu as resolveSimpleCompletionSelectionForAgent,
  Yu as prepareSimpleCompletionModelForAgent,
  dc as CronStyleNow,
  fc as appendCronStyleCurrentTimeLine,
  fl as ResolvedTtsConfig,
  pc as resolveCronStyleNow,
  pl as ResolvedTtsModelOverrides,
  qu as completeWithPreparedSimpleCompletionModel,
} from "../types-Ga3mNO_F.js";
import {
  a as normalizeWhitespace,
  i as markdownToText,
  n as extractBasicHtmlContent,
  o as truncateText,
  r as htmlToMarkdown,
  t as ExtractMode,
} from "../web-fetch-utils-Cx-FHkJu.js";
import {
  a as normalizeCacheKey,
  c as resolveCacheTtlMs,
  d as withTimeout,
  f as writeCache,
  g as withTrustedWebToolsEndpoint,
  h as withStrictWebToolsEndpoint,
  i as ReadResponseTextResult,
  l as resolvePositiveTimeoutSeconds,
  m as withSelfHostedWebToolsEndpoint,
  n as DEFAULT_CACHE_TTL_MINUTES,
  o as readCache,
  p as fetchWithWebToolsNetworkGuard,
  r as DEFAULT_TIMEOUT_SECONDS,
  s as readResponseText,
  t as CacheEntry,
  u as resolveTimeoutSeconds,
} from "../web-shared-BA33fpFU.js";
export {
  ActionGate,
  AgentAvatarResolution,
  AgentModelPrimaryWriteTarget,
  AgentSimpleCompletionSelection,
  AgentToolWithMeta,
  AnyAgentTool,
  type ApiKeyCredential,
  type AuthCredentialReasonCode,
  type AuthProfileBlockedReason,
  type AuthProfileBlockedSource,
  type AuthProfileCredential,
  type AuthProfileEligibilityReasonCode,
  type AuthProfileFailureReason,
  type AuthProfileIdRepairResult,
  type AuthProfileStore,
  AutoFallbackPrimaryProbe,
  AvailableTag,
  BlockReplyChunking,
  type BuildToolPlanOptions,
  CLAUDE_CLI_PROFILE_ID,
  CODEX_APP_SERVER_AUTH_MARKER,
  CODEX_CLI_PROFILE_ID,
  CUSTOM_LOCAL_AUTH_MARKER,
  CacheEntry,
  CronStyleNow,
  DEFAULT_CACHE_TTL_MINUTES,
  DEFAULT_CONTEXT_TOKENS,
  DEFAULT_MODEL,
  DEFAULT_PROVIDER,
  DEFAULT_TIMEOUT_SECONDS,
  EmbeddedBlockChunker,
  type EnvApiKeyResult,
  ExtractMode,
  GCP_VERTEX_CREDENTIALS_MARKER,
  type HiddenToolPlanEntry,
  type JsonObject,
  type JsonPrimitive,
  type JsonValue,
  LoadModelCatalogParams,
  MINIMAX_OAUTH_MARKER,
  MissingProviderAuthError,
  type ModelAliasIndex,
  ModelAuthMode,
  type ModelCatalogEntry,
  type ModelCatalogSnapshot,
  type ModelInputType,
  type ModelManifestNormalizationContext,
  type ModelRef,
  type ModelRefStatus,
  NON_ENV_SECRETREF_MARKER,
  OAUTH_API_KEY_MARKER_PREFIX,
  type OAuthCredential,
  OLLAMA_LOCAL_AUTH_MARKER,
  PreparedSimpleCompletionModel,
  PreparedSimpleCompletionModelForAgent,
  type ProfileUsageStats,
  ProviderAuthAliasLookupParams,
  ProviderAuthError,
  ProviderCredentialPrecedence,
  ProviderEntryApiKeyBindingResolution,
  PublicToolProgress,
  ReactionParams,
  ReadResponseTextResult,
  type ResolvedAgentConfig,
  type ResolvedProviderAuth,
  ResolvedTimeFormat,
  type ResolvedTtsConfig,
  type ResolvedTtsModelOverrides,
  RuntimeProviderAuthLookup,
  SECRETREF_ENV_HEADER_MARKER_PREFIX,
  SimpleCompletionModelOptions,
  StringParamOptions,
  SubagentModelConfigSelectionResult,
  SubagentModelConfigSelectionSource,
  THINKING_TAG_SCAN_RE,
  type ThinkLevel,
  TimeFormatPreference,
  type TokenCredential,
  type TokenExpiryState,
  ToolAuthorizationError,
  type ToolAvailabilityContext,
  type ToolAvailabilityDiagnostic,
  type ToolAvailabilityExpression,
  type ToolAvailabilitySignal,
  type ToolDescriptor,
  type ToolExecutorRef,
  ToolInputError,
  type ToolOwnerRef,
  type ToolPlan,
  ToolPlanContractError,
  type ToolPlanEntry,
  type ToolUnavailableReason,
  type TtsDirectiveOverrides,
  type TtsDirectiveParseResult,
  type TtsResult,
  type TtsStreamResult,
  type TtsSynthesisResult,
  type TtsSynthesisStreamResult,
  type TtsTelephonyResult,
  setModelCatalogImportForTest as __setModelCatalogImportForTest,
  setModelCatalogImportForTest,
  testing as __testing,
  testing,
  testApi as _test,
  testApi,
  agentCommand,
  agentCommandFromIngress,
  appendCronStyleCurrentTimeLine,
  applyAuthHeaderOverride,
  applyLocalNoAuthHeaderOverride,
  applySecretRefHeaderSentinels,
  asToolParamsRecord,
  assertMediaNotDataUrl,
  assertSandboxPath,
  buildAllowedModelSet,
  buildConfiguredAllowlistKeys,
  buildConfiguredModelCatalog,
  buildModelAliasIndex,
  buildToolPlan,
  buildTtsSystemPromptHint,
  calculateAuthProfileCooldownMs,
  canUseProfileAsProviderEntryApiKey,
  canonicalizeCaseOnlyCatalogModelRef,
  channelTargetSchema,
  channelTargetsSchema,
  clearAuthProfileCooldown,
  clearAutoFallbackPrimaryProbeSelection,
  clearExpiredCooldowns,
  clearRuntimeAuthProfileStoreSnapshots,
  completeWithPreparedSimpleCompletionModel,
  createActionGate,
  createRuntimeProviderAuthLookup,
  dedupeProfileIds,
  defineToolDescriptor,
  defineToolDescriptors,
  emitToolProgress,
  ensureAuthProfileStore,
  ensureAuthProfileStoreWithoutExternalProfiles,
  entryMatchesAutoFallbackPrimaryProbe,
  evaluateToolAvailability,
  extractAssistantCommentaryText,
  extractAssistantText,
  extractAssistantThinking,
  extractAssistantVisibleText,
  extractBasicHtmlContent,
  extractThinkingFromTaggedStream,
  extractThinkingFromTaggedText,
  failedTextResult,
  fetchWithWebToolsNetworkGuard,
  findModelCatalogEntry,
  findModelInCatalog,
  findNormalizedProviderKey,
  findNormalizedProviderValue,
  findPersistedAuthProfileCredential,
  formatAuthDoctorHint,
  formatDateStamp,
  formatMissingAuthError,
  formatReasoningMessage,
  formatToolExecutorRef,
  formatUserTime,
  getApiKeyForModel,
  getCustomProviderApiKey,
  getLastTtsAttempt,
  getModelRefStatus,
  getResolvedSpeechProviderConfig,
  getSoonestCooldownExpiry,
  getTtsMaxLength,
  getTtsPersona,
  getTtsProvider,
  hasAvailableAuthForProvider,
  hasConfiguredModelFallbacks,
  hasLegacyAutoFallbackWithoutOrigin,
  hasRuntimeAvailableProviderAuth,
  hasSessionAutoModelFallbackProvenance,
  hasSyntheticLocalProviderAuthConfig,
  hasUsableCustomProviderApiKey,
  htmlToMarkdown,
  imageResult,
  imageResultFromFile,
  inferToolMetaFromArgs,
  inferUniqueProviderFromCatalog,
  inferUniqueProviderFromConfiguredModels,
  isAssistantMessage,
  isAwsSdkAuthMarker,
  isCliProvider,
  isKnownEnvApiKeyMarker,
  isMissingProviderAuthError,
  isNonSecretApiKeyMarker,
  isOAuthApiKeyMarker,
  isProfileInCooldown,
  isProviderAuthError,
  isSecretRefHeaderValueMarker,
  isSummarizationEnabled,
  isTtsEnabled,
  isTtsProviderConfigured,
  jsonResult,
  legacyModelKey,
  listAgentEntries,
  listAgentIds,
  listKnownNonSecretApiKeyMarkers,
  listProfilesForProvider,
  listSpeechVoices,
  listTtsPersonas,
  loadAuthProfileStore,
  loadAuthProfileStoreForRuntime,
  loadAuthProfileStoreForSecretsRuntime,
  loadAuthProfileStoreWithoutExternalProfiles,
  loadManifestModelCatalog,
  loadModelCatalog,
  loadModelCatalogSnapshot,
  markAuthProfileBlockedUntil,
  markAuthProfileCooldown,
  markAuthProfileFailure,
  markAuthProfileSuccess,
  markAutoFallbackPrimaryProbe,
  markdownToText,
  maybeApplyTtsToPayload,
  modelKey,
  modelSupportsDocument,
  modelSupportsInput,
  modelSupportsVision,
  normalizeCacheKey,
  normalizeModelRef,
  normalizeModelSelection,
  normalizeProviderId,
  normalizeProviderIdForAuth,
  normalizeStoredOverrideModel,
  normalizeTimestamp,
  normalizeToolModelOverride,
  normalizeWhitespace,
  optionalFiniteNumberSchema,
  optionalNonNegativeIntegerSchema,
  optionalPositiveIntegerSchema,
  optionalStringEnum,
  parseAvailableTags,
  parseModelRef,
  payloadTextResult,
  prepareSimpleCompletionModel,
  prepareSimpleCompletionModelForAgent,
  promoteThinkingTagsToBlocks,
  readCache,
  readFiniteNumberParam,
  readNonNegativeIntegerParam,
  readNumberParam,
  readPositiveIntegerParam,
  readReactionParams,
  readResponseText,
  readStringArrayParam,
  readStringOrNumberParam,
  readStringParam,
  refreshOAuthCredentialForRuntime,
  repairOAuthProfileIdMismatch,
  replaceRuntimeAuthProfileStoreSnapshots,
  requireApiKey,
  resetModelCatalogCache,
  resetModelCatalogCacheForTest,
  resetProviderAuthAliasMapCacheForTest,
  resolveAckReaction,
  resolveAgentAvatar,
  resolveAgentConfig,
  resolveAgentContextLimits,
  resolveAgentDir,
  resolveAgentEffectiveModelPrimary,
  resolveAgentExecutionContract,
  resolveAgentExplicitModelPrimary,
  resolveAgentIdByWorkspacePath,
  resolveAgentIdFromSessionKey,
  resolveAgentIdentity,
  resolveAgentIdsByWorkspacePath,
  resolveAgentModelFallbacksOverride,
  resolveAgentModelPrimary,
  resolveAgentSkillsFilter,
  resolveAgentWorkspaceDir,
  resolveAllowedManagedMediaPath,
  resolveAllowedModelRef,
  resolveAllowlistModelKey,
  resolveApiKeyForProfile,
  resolveApiKeyForProvider,
  resolveAuthProfileDisplayLabel,
  resolveAuthProfileEligibility,
  resolveAuthProfileOrder,
  resolveAuthProfileOrderWithMetadata,
  resolveAuthStorePathForDisplay,
  resolveAutoFallbackPrimaryProbe,
  resolveAwsSdkEnvVarName,
  resolveBareModelDefaultProvider,
  resolveCacheTtlMs,
  resolveConfiguredModelRef,
  resolveConfiguredSubagentSpawnModelSelection,
  resolveCronStyleNow,
  resolveDefaultAgentDir,
  resolveDefaultAgentId,
  resolveDefaultModelForAgent,
  resolveEffectiveMessagesConfig,
  resolveEffectiveModelFallbacks,
  resolveEnvApiKey,
  resolveEnvSecretRefHeaderValueMarker,
  resolveExplicitTtsOverrides,
  resolveFallbackAgentId,
  resolveHooksGmailModel,
  resolveHumanDelayConfig,
  resolveIdentityNamePrefix,
  resolveMessagePrefix,
  resolveModelAuthMode,
  resolveModelCatalogScope,
  resolveModelRefFromString,
  resolveNonEnvSecretRefApiKeyMarker,
  resolveNonEnvSecretRefHeaderValueMarker,
  resolveOAuthApiKeyMarker,
  resolveOpenClawAgentDir,
  resolvePersistedAuthProfileOwnerAgentDir,
  resolvePersistedModelRef,
  resolvePersistedOverrideModelRef,
  resolvePersistedSelectedModelRef,
  resolvePositiveTimeoutSeconds,
  resolveProfileUnusableUntilForDisplay,
  resolveProfilesUnavailableReason,
  resolveProviderAuthAliasMap,
  resolveProviderDiscoveryProviderIdsForCatalogScope,
  resolveProviderEntryApiKeyBinding,
  resolveProviderEntryApiKeyProfileReference,
  resolveProviderIdForAuth,
  resolvePublicAgentAvatarSource,
  resolveReasoningDefault,
  resolveResponsePrefix,
  resolveRunModelFallbacksOverride,
  resolveSandboxInputPath,
  resolveSandboxPath,
  resolveSandboxedMediaSource,
  resolveSessionAgentId,
  resolveSessionAgentIds,
  resolveSimpleCompletionSelectionForAgent,
  resolveSubagentConfiguredModelSelection,
  resolveSubagentModelConfigSelection,
  resolveSubagentModelConfigSelectionResult,
  resolveSubagentModelFallbacksOverride,
  resolveSubagentSpawnModelSelection,
  resolveThinkingDefault,
  resolveThinkingDefaultWithRuntimeCatalog,
  resolveTimeoutSeconds,
  resolveTtsAutoMode,
  resolveTtsConfig,
  resolveTtsPrefsPath,
  resolveTtsProviderOrder,
  resolveUsableCustomProviderApiKey,
  resolveUserTimeFormat,
  resolveUserTimezone,
  sanitizeAssistantVisibleStreamText,
  saveAuthProfileStore,
  scheduleToolProgress,
  setAgentEffectiveModelPrimary,
  setAuthProfileOrder,
  setLastTtsAttempt,
  setSummarizationEnabled,
  setTtsAutoMode,
  setTtsEnabled,
  setTtsMaxLength,
  setTtsPersona,
  setTtsProvider,
  shouldPreferExplicitConfigApiKeyAuth,
  splitThinkingTaggedText,
  streamSpeech,
  stringEnum,
  stringifyToolPayload,
  stripDowngradedToolCallText,
  stripMinimaxToolCallXml,
  stripModelSpecialTokens,
  stripThinkingTagsFromText,
  suggestOAuthProfileIdForLegacyDefault,
  synthesizeSpeech,
  textResult,
  textToSpeech,
  textToSpeechStream,
  textToSpeechTelephony,
  toToolProtocolDescriptor,
  toToolProtocolDescriptors,
  toolProgressResult,
  truncateText,
  upsertAuthProfile,
  upsertAuthProfileWithLock,
  withNormalizedTimestamp,
  withSelfHostedWebToolsEndpoint,
  withStrictWebToolsEndpoint,
  withTimeout,
  withTrustedWebToolsEndpoint,
  writeCache,
};
