import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { t as AllowlistMatch } from "../allowlist-match-Bmdv70ad.js";
import { t as ChatType } from "../chat-type-B6XXSSnm.js";
import {
  C as readReactionParams,
  E as readStringParam,
  d as createActionGate,
  w as readStringArrayParam,
  x as readNumberParam,
} from "../common-CuQ9SS3Z.js";
import {
  n as deleteAccountFromConfigSection,
  r as setAccountEnabledInConfigSection,
  t as clearAccountEntryFields,
} from "../config-helpers-DAeK6gXx.js";
import {
  i as buildJsonChannelConfigSchema,
  o as emptyChannelConfigSchema,
  r as buildChannelConfigSchema,
} from "../config-schema-CpUUoa8V.js";
import {
  _ as TailscaleStatusCommandResult,
  a as buildThreadAwareOutboundSessionRoute,
  b as resolveTailscalePublishedHost,
  c as defineChannelPluginEntry,
  d as getChatChannelMeta,
  f as recoverCurrentThreadSessionId,
  g as resolveGatewayBindUrl,
  h as GatewayBindUrlResult,
  i as buildChannelOutboundSessionRoute,
  l as defineSetupPluginEntry,
  m as stripTargetKindPrefix,
  n as ThreadAwareOutboundSessionRouteRecoveryContext,
  o as createChannelPluginBase,
  p as stripChannelTargetPrefix,
  r as ThreadAwareOutboundSessionRouteThreadSource,
  s as createChatChannelPlugin,
  t as ChannelOutboundSessionRouteParams,
  u as ensureConfiguredAcpBindingReady,
  v as TailscaleStatusCommandRunner,
  x as resolveTailscaleServeGatewayUrlsWithRunner,
  y as resolveTailnetHostWithRunner,
} from "../core-UJInsb1U.js";
import { i as resolveGlobalDedupeCache, r as createDedupeCache } from "../dedupe-DlnrYV_t.js";
import {
  n as delegateCompactionToRuntime,
  t as buildMemorySystemPromptAddition,
} from "../delegate-BRW9iUXY.js";
import { n as formatZonedTimestamp } from "../format-datetime-D-Jf_Pqu.js";
import {
  n as formatPairingApproveHint,
  r as parseOptionalDelimitedEntries,
} from "../helpers-D1ImsQvd.js";
import { t as HistoryEntry } from "../history.types-Bc8mCALh.js";
import {
  at as PluginHookReplyDispatchContext,
  ct as PluginHookReplyPayload,
  dt as PluginHookReplyPayloadSendingResult,
  lt as PluginHookReplyPayloadSendingContext,
  ot as PluginHookReplyDispatchEvent,
  st as PluginHookReplyDispatchResult,
  ut as PluginHookReplyPayloadSendingEvent,
} from "../hook-types-BPL4xByC.js";
import { r as enqueueKeyedTask, t as KeyedAsyncQueue } from "../keyed-async-queue-Co67NYfr.js";
import {
  h as UnifiedModelCatalogSource,
  m as UnifiedModelCatalogKind,
  p as UnifiedModelCatalogEntry,
} from "../manifest-registry-CHEq75Tu.js";
import {
  c as MemoryPluginPublicArtifact,
  l as MemoryPluginPublicArtifactsProvider,
  s as MemoryPluginCapability,
} from "../memory-state-wPutFXhr.js";
import { i as resolveClientIp, r as isTrustedProxyAddress } from "../net-F7HGAsK5.js";
import { b as parseStrictPositiveInteger } from "../number-coercion-C7PMvT3i.js";
import { n as ChannelOutboundAdapter, u as OutboundIdentity } from "../outbound.types-Bu7WWq9f.js";
import { f as resolveGatewayPort } from "../paths-CAFnjuPj.js";
import { t as resolveConfiguredAcpBindingRecord } from "../persistent-bindings.resolve-D8pUaJkT.js";
import {
  $ as PluginSessionActionResult,
  $t as ProviderThinkingPolicyContext,
  A as OpenClawPluginServiceContext,
  At as ProviderModernModelPolicyContext,
  B as PluginControlUiDescriptor,
  Bt as ProviderReasoningOutputMode,
  Ct as ProviderCatalogContext,
  Dt as ProviderDiscoveryContext,
  F as PluginAgentEventSubscriptionRegistration,
  G as PluginNextTurnInjection,
  Gt as ProviderReplaySessionState,
  H as PluginHeartbeatPromptContributionResult,
  Ht as ProviderReplayPolicy,
  I as PluginAgentTurnPrepareEvent,
  It as ProviderPrepareDynamicModelContext,
  J as PluginRunContextGetParams,
  Jt as ProviderResolveTransportTurnStateContext,
  K as PluginNextTurnInjectionEnqueueResult,
  L as PluginAgentTurnPrepareResult,
  Lt as ProviderPrepareExtraParamsContext,
  N as PluginAgentEventEmitParams,
  Nt as ProviderNormalizeResolvedModelContext,
  P as PluginAgentEventEmitResult,
  Pt as ProviderNormalizeToolSchemasContext,
  Q as PluginSessionActionRegistration,
  Qt as ProviderSanitizeReplayHistoryContext,
  R as PluginCommandContext,
  Rt as ProviderPrepareRuntimeAuthContext,
  St as ProviderCacheTtlEligibilityContext,
  Tt as ProviderDefaultThinkingPolicyContext,
  U as PluginJsonValue,
  Ut as ProviderReplayPolicyContext,
  V as PluginHeartbeatPromptContributionEvent,
  Vt as ProviderReasoningOutputModeContext,
  W as PluginLogger,
  Wt as ProviderReplaySessionEntry,
  X as PluginRuntimeLifecycleRegistration,
  Xt as ProviderResolveWebSocketSessionPolicyContext,
  Y as PluginRunContextPatch,
  Yt as ProviderResolveUsageAuthContext,
  Z as PluginSessionActionContext,
  Zt as ProviderResolvedUsageAuth,
  _ as OpenClawPluginCommandDefinition,
  _t as ProviderAuthResult,
  a as AnyAgentTool,
  an as ProviderWebSocketSessionPolicy,
  at as PluginSessionSchedulerJobRegistration,
  bt as ProviderBuiltInModelSuppressionContext,
  cn as SpeechProviderPlugin,
  ct as PluginSessionTurnUnscheduleByTagResult,
  dn as UnifiedModelCatalogProviderPlugin,
  en as ProviderThinkingProfile,
  et as PluginSessionAttachmentParams,
  ft as ProviderAugmentModelCatalogContext,
  g as OpenClawPluginApi,
  gt as ProviderAuthMethodNonInteractiveContext,
  ht as ProviderAuthMethod,
  i as AgentPromptSurfaceKind,
  in as ProviderValidateReplayTurnsContext,
  it as PluginSessionSchedulerJobHandle,
  k as OpenClawPluginService,
  kt as ProviderFetchUsageSnapshotContext,
  lt as PluginToolMetadataRegistration,
  mt as ProviderAuthDoctorHintContext,
  n as AgentPromptGuidance,
  nn as ProviderTransportTurnState,
  nt as PluginSessionExtensionProjection,
  o as MediaUnderstandingProviderPlugin,
  on as ProviderWrapStreamFnContext,
  ot as PluginSessionTurnScheduleParams,
  pt as ProviderAuthContext,
  q as PluginNextTurnInjectionRecord,
  qt as ProviderResolveDynamicModelContext,
  r as AgentPromptGuidanceEntry,
  rn as ProviderUsageAuthToken,
  rt as PluginSessionExtensionRegistration,
  sn as RealtimeTranscriptionProviderPlugin,
  st as PluginSessionTurnUnscheduleByTagParams,
  t as AgentHarness,
  tn as ProviderToolSchemaDiagnostic,
  tt as PluginSessionAttachmentResult,
  un as UnifiedModelCatalogProviderContext,
  ut as PluginTrustedToolPolicyRegistration,
  v as OpenClawPluginConfigSchema,
  vt as ProviderBuildMissingAuthMessageContext,
  wt as ProviderCatalogResult,
  xt as ProviderBuiltInModelSuppressionResult,
  y as OpenClawPluginDefinition,
  yn as definePluginEntry,
  yt as ProviderBuildUnknownModelHintContext,
  z as PluginCommandResult,
  zt as ProviderPreparedRuntimeAuth,
} from "../plugin-entry-DPCR66aO.js";
import { n as PollInput } from "../polls-CfHkU59X.js";
import { i as WizardPrompter } from "../prompts-CWXx5gsI.js";
import {
  c as UsageWindow,
  o as ProviderUsageSnapshot,
  s as UsageProviderId,
} from "../provider-usage.types-CSw7pG9h.js";
import { r as ReplyPayload } from "../reply-payload-D9hNZyN3.js";
import { f as NormalizedLocation, p as OutboundLocation } from "../reply-payload-DPFdJynw.js";
import {
  i as buildAgentSessionKey,
  n as RoutePeer,
  r as RoutePeerKind,
} from "../resolve-route-CtaxCE-K.js";
import {
  c as tryReadSecretFileSync,
  n as loadSecretFileSync,
  o as SecretFileReadOptions,
  r as DEFAULT_SECRET_FILE_MAX_BYTES,
  s as readSecretFileSync,
  t as SecretFileReadResult,
} from "../secret-file-DbiHRw7A.js";
import { a as generateSecureUuid, i as generateSecureToken } from "../secure-random-BTcaoAnv.js";
import { o as resolveThreadSessionKeys } from "../session-key-COxKqlXJ.js";
import {
  s as migrateBaseNameToDefaultAccount,
  t as applyAccountNameToChannelSection,
} from "../setup-helpers-CD5ZaV-J.js";
import {
  i as normalizeHyphenSlug,
  n as normalizeAtHashSlug,
} from "../string-normalization-BUWquf-_.js";
import { n as createSubsystemLogger } from "../subsystem-BvPn7HK_.js";
import { t as jsonResult } from "../tool-results-DtJKrUlx.js";
import {
  n as channelTargetsSchema,
  o as optionalStringEnum,
  s as stringEnum,
  t as channelTargetSchema,
} from "../typebox-WKHUFEwH.js";
import { r as GatewayRequestHandlerOptions } from "../types-Dz3ohwUV.js";
import {
  Bl as OpenClawPluginActiveModelContext,
  Hl as OpenClawPluginToolContext,
  Js as buildPluginConfigSchema,
  Lc as ContextEngineSessionTarget,
  Ul as OpenClawPluginToolFactory,
  Ys as emptyPluginConfigSchema,
  Zc as RuntimeLogger,
  cr as PluginRuntime,
  nd as ProviderRuntimeModel,
  qs as buildJsonPluginConfigSchema,
} from "../types-Ga3mNO_F.js";
import { r as ChannelConfigUiHint } from "../types.config-D1pSqbn8.js";
import {
  E as ChannelOutboundSessionRoute,
  N as ChannelSetupInput,
  T as ChannelMeta,
  m as ChannelGroupContext,
  r as ChannelAccountSnapshot,
  t as BaseProbeResult,
  u as ChannelDirectoryEntry,
  w as ChannelMessagingAdapter,
  y as ChannelMessageActionContext,
} from "../types.core-CcwzPNhX.js";
import { i as OpenClawConfig } from "../types.openclaw-DDo8sH3F.js";
import { t as ChannelPlugin } from "../types.plugin-BGk2f9vp.js";
import { t as ChannelMessageActionName } from "../types.public-CV2EbDei.js";
import { S as isSecretRef } from "../types.secrets-C15Z_eLX.js";
export {
  type AgentHarness,
  type AgentPromptGuidance,
  type AgentPromptGuidanceEntry,
  type AgentPromptSurfaceKind,
  type AllowlistMatch,
  type AnyAgentTool,
  type BaseProbeResult,
  type ChannelAccountSnapshot,
  type ChannelConfigUiHint,
  type ChannelDirectoryEntry,
  type ChannelGroupContext,
  type ChannelMessageActionContext,
  type ChannelMessageActionName,
  type ChannelMessagingAdapter,
  type ChannelMeta,
  type ChannelOutboundAdapter,
  type ChannelOutboundSessionRoute,
  ChannelOutboundSessionRouteParams,
  type ChannelPlugin,
  type ChannelSetupInput,
  type ChatType,
  type ContextEngineSessionTarget,
  DEFAULT_ACCOUNT_ID,
  DEFAULT_SECRET_FILE_MAX_BYTES,
  type GatewayBindUrlResult,
  type GatewayRequestHandlerOptions,
  type HistoryEntry,
  KeyedAsyncQueue,
  type MediaUnderstandingProviderPlugin,
  type MemoryPluginCapability,
  type MemoryPluginPublicArtifact,
  type MemoryPluginPublicArtifactsProvider,
  type NormalizedLocation,
  type OpenClawConfig,
  type OpenClawPluginActiveModelContext,
  type OpenClawPluginApi,
  type OpenClawPluginCommandDefinition,
  type OpenClawPluginConfigSchema,
  type OpenClawPluginDefinition,
  type OpenClawPluginService,
  type OpenClawPluginServiceContext,
  type OpenClawPluginToolContext,
  type OpenClawPluginToolFactory,
  type OutboundIdentity,
  type OutboundLocation,
  type PluginAgentEventEmitParams,
  type PluginAgentEventEmitResult,
  type PluginAgentEventSubscriptionRegistration,
  type PluginAgentTurnPrepareEvent,
  type PluginAgentTurnPrepareResult,
  type PluginCommandContext,
  type PluginCommandResult,
  type PluginControlUiDescriptor,
  type PluginHeartbeatPromptContributionEvent,
  type PluginHeartbeatPromptContributionResult,
  type PluginHookReplyDispatchContext,
  type PluginHookReplyDispatchEvent,
  type PluginHookReplyDispatchResult,
  type PluginHookReplyPayload,
  type PluginHookReplyPayloadSendingContext,
  type PluginHookReplyPayloadSendingEvent,
  type PluginHookReplyPayloadSendingResult,
  type PluginJsonValue,
  type PluginLogger,
  type PluginNextTurnInjection,
  type PluginNextTurnInjectionEnqueueResult,
  type PluginNextTurnInjectionRecord,
  type PluginRunContextGetParams,
  type PluginRunContextPatch,
  type PluginRuntime,
  type PluginRuntimeLifecycleRegistration,
  type PluginSessionActionContext,
  type PluginSessionActionRegistration,
  type PluginSessionActionResult,
  type PluginSessionAttachmentParams,
  type PluginSessionAttachmentResult,
  type PluginSessionExtensionProjection,
  type PluginSessionExtensionRegistration,
  type PluginSessionSchedulerJobHandle,
  type PluginSessionSchedulerJobRegistration,
  type PluginSessionTurnScheduleParams,
  type PluginSessionTurnUnscheduleByTagParams,
  type PluginSessionTurnUnscheduleByTagResult,
  type PluginToolMetadataRegistration,
  type PluginTrustedToolPolicyRegistration,
  type PollInput,
  type ProviderAugmentModelCatalogContext,
  type ProviderAuthContext,
  type ProviderAuthDoctorHintContext,
  type ProviderAuthMethod,
  type ProviderAuthMethodNonInteractiveContext,
  type ProviderAuthResult,
  type ProviderBuildMissingAuthMessageContext,
  type ProviderBuildUnknownModelHintContext,
  type ProviderBuiltInModelSuppressionContext,
  type ProviderBuiltInModelSuppressionResult,
  type ProviderCacheTtlEligibilityContext,
  type ProviderCatalogContext,
  type ProviderCatalogResult,
  type ProviderDefaultThinkingPolicyContext,
  type ProviderDiscoveryContext,
  type ProviderFetchUsageSnapshotContext,
  type ProviderModernModelPolicyContext,
  type ProviderNormalizeResolvedModelContext,
  type ProviderNormalizeToolSchemasContext,
  type ProviderPrepareDynamicModelContext,
  type ProviderPrepareExtraParamsContext,
  type ProviderPrepareRuntimeAuthContext,
  type ProviderPreparedRuntimeAuth,
  type ProviderReasoningOutputMode,
  type ProviderReasoningOutputModeContext,
  type ProviderReplayPolicy,
  type ProviderReplayPolicyContext,
  type ProviderReplaySessionEntry,
  type ProviderReplaySessionState,
  type ProviderResolveDynamicModelContext,
  type ProviderResolveTransportTurnStateContext,
  type ProviderResolveUsageAuthContext,
  type ProviderResolveWebSocketSessionPolicyContext,
  type ProviderResolvedUsageAuth,
  type ProviderRuntimeModel,
  type ProviderSanitizeReplayHistoryContext,
  type ProviderThinkingPolicyContext,
  type ProviderThinkingProfile,
  type ProviderToolSchemaDiagnostic,
  type ProviderTransportTurnState,
  type ProviderUsageAuthToken,
  type ProviderUsageSnapshot,
  type ProviderValidateReplayTurnsContext,
  type ProviderWebSocketSessionPolicy,
  type ProviderWrapStreamFnContext,
  type RealtimeTranscriptionProviderPlugin,
  type ReplyPayload,
  type RoutePeer,
  type RoutePeerKind,
  type RuntimeLogger,
  type SecretFileReadOptions,
  type SecretFileReadResult,
  type SpeechProviderPlugin,
  type TailscaleStatusCommandResult,
  type TailscaleStatusCommandRunner,
  ThreadAwareOutboundSessionRouteRecoveryContext,
  ThreadAwareOutboundSessionRouteThreadSource,
  type UnifiedModelCatalogEntry,
  type UnifiedModelCatalogKind,
  type UnifiedModelCatalogProviderContext,
  type UnifiedModelCatalogProviderPlugin,
  type UnifiedModelCatalogSource,
  type UsageProviderId,
  type UsageWindow,
  type WizardPrompter,
  applyAccountNameToChannelSection,
  buildAgentSessionKey,
  buildChannelConfigSchema,
  buildChannelOutboundSessionRoute,
  buildJsonChannelConfigSchema,
  buildJsonPluginConfigSchema,
  buildMemorySystemPromptAddition,
  buildPluginConfigSchema,
  buildThreadAwareOutboundSessionRoute,
  channelTargetSchema,
  channelTargetsSchema,
  clearAccountEntryFields,
  createActionGate,
  createChannelPluginBase,
  createChatChannelPlugin,
  createDedupeCache,
  createSubsystemLogger,
  defineChannelPluginEntry,
  definePluginEntry,
  defineSetupPluginEntry,
  delegateCompactionToRuntime,
  deleteAccountFromConfigSection,
  emptyChannelConfigSchema,
  emptyPluginConfigSchema,
  enqueueKeyedTask,
  ensureConfiguredAcpBindingReady,
  formatPairingApproveHint,
  formatZonedTimestamp,
  generateSecureToken,
  generateSecureUuid,
  getChatChannelMeta,
  isSecretRef,
  isTrustedProxyAddress,
  jsonResult,
  loadSecretFileSync,
  migrateBaseNameToDefaultAccount,
  normalizeAccountId,
  normalizeAtHashSlug,
  normalizeHyphenSlug,
  optionalStringEnum,
  parseOptionalDelimitedEntries,
  parseStrictPositiveInteger,
  readNumberParam,
  readReactionParams,
  readSecretFileSync,
  readStringArrayParam,
  readStringParam,
  recoverCurrentThreadSessionId,
  resolveClientIp,
  resolveConfiguredAcpBindingRecord,
  resolveGatewayBindUrl,
  resolveGatewayPort,
  resolveGlobalDedupeCache,
  resolveTailnetHostWithRunner,
  resolveTailscalePublishedHost,
  resolveTailscaleServeGatewayUrlsWithRunner,
  resolveThreadSessionKeys,
  setAccountEnabledInConfigSection,
  stringEnum,
  stripChannelTargetPrefix,
  stripTargetKindPrefix,
  tryReadSecretFileSync,
};
