import { t as formatApprovalDisplayPath } from "../approval-display-paths-DlQSsCnq.js";
import {
  a as isExecApprovalChannelRuntimeTerminalStartError,
  i as createExecApprovalChannelRuntime,
  n as deliverApprovalRequestViaChannelNativePlan,
  o as resolveChannelNativeApprovalDeliveryPlan,
  r as ExecApprovalChannelRuntimeTerminalStartError,
  t as createChannelNativeApprovalRuntime,
} from "../approval-native-runtime-BZ9rGhrh.js";
import { t as createAsyncLock } from "../async-lock-CaiUOILd.js";
import "../parse-finite-number-Z7n6tXLk.js";
import {
  n as recordChannelActivity,
  r as resetChannelActivityForTest,
  t as getChannelActivity,
} from "../channel-activity-4piA219h.js";
import { n as resolveGlobalDedupeCache, t as createDedupeCache } from "../dedupe-BqZ2YTEC.js";
import { t as drainPendingDeliveries } from "../delivery-queue-runtime-DjDMps_8.js";
import {
  f as isDiagnosticsEnabled,
  m as onDiagnosticEvent,
  n as emitDiagnosticEvent,
  t as areDiagnosticsEnabledForProcess,
} from "../diagnostic-events-5-gsFhkM.js";
import {
  n as matchesDiagnosticFlag,
  r as resolveDiagnosticFlags,
  t as isDiagnosticFlagEnabled,
} from "../diagnostic-flags-DoJxaJiY.js";
import {
  a as normalizeEnv,
  i as logAcceptedEnvOption,
  n as isTruthyEnvValue,
  o as normalizeZaiEnv,
  r as isVitestRuntimeEnv,
  s as resolveEnvNormalizationKeys,
  t as expandEnvNormalizationKeys,
} from "../env-Di-LcxqW.js";
import { n as stringifyNonErrorCause, r as toErrorObject } from "../error-coercion-CrJRoLe1.js";
import {
  a as hasErrnoCode,
  i as formatUncaughtError,
  n as extractErrorCode,
  o as isErrno,
  r as formatErrorMessage,
  s as readErrorName,
  t as collectErrorGraphCandidates,
} from "../errors-BoHeli7m.js";
import {
  i as sanitizeExecApprovalWarningText,
  n as sanitizeExecApprovalDisplayText,
  r as sanitizeExecApprovalDisplayTextWithStatus,
  t as resolveExecApprovalCommandDisplay,
} from "../exec-approval-command-display-SUzu7-Pq.js";
import {
  a as buildExecApprovalCommandText,
  c as buildExecApprovalUnavailableReplyPayload,
  d as buildTypedExecApprovalPendingReplyPayload,
  f as buildTypedExecApprovalPresentation,
  g as parseExecApprovalCommandText,
  h as getExecApprovalReplyMetadata,
  i as buildExecApprovalActionDescriptors,
  l as buildTypedApprovalActionDescriptors,
  m as getExecApprovalApproverDmNoticeText,
  n as buildApprovalPresentation,
  o as buildExecApprovalPendingReplyPayload,
  p as formatExecApprovalExpiresIn,
  r as buildApprovalPresentationFromActionDescriptors,
  s as buildExecApprovalPresentation,
  t as buildApprovalInteractiveReplyFromActionDescriptors,
  u as buildTypedApprovalPresentation,
} from "../exec-approval-reply-Djiq6tOJ.js";
import {
  i as resolveExecApprovalSessionTarget,
  n as resolveApprovalRequestSessionConversation,
  r as resolveApprovalRequestSessionTarget,
  t as resolveApprovalRequestOriginTarget,
} from "../exec-approval-session-target-GSisVfGX.js";
import {
  a as isSafeBinUsage,
  c as resolveAllowAlwaysPatterns,
  i as evaluateShellAllowlistWithAuthorization,
  l as resolveSafeBins,
  n as evaluateExecAllowlistWithAuthorization,
  o as normalizeSafeBins,
  r as evaluateShellAllowlist,
  s as resolveAllowAlwaysPatternEntries,
  t as evaluateExecAllowlist,
} from "../exec-approvals-allowlist-Bc6wvPEu.js";
import {
  a as isWindowsPlatform,
  i as analyzeWindowsShellCommand,
  n as resolvePlannedSegmentArgv,
  o as tokenizeWindowsSegment,
  r as analyzeArgvCommand,
  s as windowsEscapeArg,
  t as buildEnforcedShellCommand,
} from "../exec-approvals-analysis-C-pXO6pp.js";
import {
  $ as resolveExecPolicyForMode,
  A as persistAllowAlwaysDecision,
  C as normalizeExecApprovalUnavailableDecisions,
  D as normalizeExecMode,
  E as normalizeExecHost,
  F as requestExecApprovalViaSocket,
  G as resolveExecApprovalsDisplayPath,
  H as resolveExecApprovalRequestAllowedDecisions,
  I as requireValidExecTarget,
  J as resolveExecApprovalsPath,
  K as resolveExecApprovalsFromFile,
  L as requiresExecApproval,
  M as readExecApprovalsSnapshot,
  N as recordAllowlistMatchesUse,
  O as normalizeExecSecurity,
  P as recordAllowlistUse,
  Q as resolveExecModePolicy,
  R as resolveAllowAlwaysPatternCoverage,
  S as minSecurity,
  T as normalizeExecAsk,
  U as resolveExecApprovalUnavailableDecisions,
  V as resolveExecApprovalAllowedDecisions,
  W as resolveExecApprovals,
  X as resolveExecApprovalsTranscriptPath,
  Y as resolveExecApprovalsSocketPath,
  Z as resolveExecModeFromPolicy,
  a as OPTIONAL_EXEC_APPROVAL_DECISIONS,
  b as maxAsk,
  c as commandRequiresSecurityAuditSuppressionApproval,
  d as ensureExecApprovals,
  et as restoreExecApprovalsSnapshot,
  g as isExecApprovalDecisionAllowed,
  h as hasNodeCommandAllowAlwaysMarker,
  i as EXEC_TARGET_VALUES,
  j as persistAllowAlwaysPatterns,
  k as normalizeExecTarget,
  m as hasExactCommandDurableExecApproval,
  n as DEFAULT_EXEC_APPROVAL_DECISIONS,
  nt as saveExecApprovals,
  o as addAllowlistEntry,
  p as hasDurableExecApproval,
  r as DEFAULT_EXEC_APPROVAL_TIMEOUT_MS,
  s as addDurableCommandApproval,
  t as DEFAULT_EXEC_APPROVAL_ASK_FALLBACK,
  v as loadExecApprovals,
  w as normalizeExecApprovals,
  x as mergeExecApprovalsSocketDefaults,
  z as resolveAllowAlwaysPersistenceDecision,
} from "../exec-approvals-Bz218bS2.js";
import {
  a as resolveApprovalAuditTrustPath,
  c as resolveExecutableTrustPath,
  d as resolveExecutionTargetTrustPath,
  f as resolvePolicyAllowlistCandidatePath,
  h as resolvePolicyTargetTrustPath,
  i as resolveApprovalAuditCandidatePath,
  l as resolveExecutionTargetCandidatePath,
  m as resolvePolicyTargetResolution,
  n as parseExecArgvToken,
  o as resolveCommandResolution,
  p as resolvePolicyTargetCandidatePath,
  r as resolveAllowlistCandidatePath,
  s as resolveCommandResolutionFromArgv,
  t as matchAllowlist,
  u as resolveExecutionTargetResolution,
} from "../exec-command-resolution-CApTmCLK.js";
import { n as wrapFetchWithAbortSignal, t as resolveFetch } from "../fetch-B_uBy4WI.js";
import {
  a as withStrictGuardedFetchMode,
  i as retainSafeHeadersForCrossOriginRedirectHeaders,
  o as withTrustedEnvProxyGuardedFetchMode,
  r as fetchWithSsrFGuard,
  s as withTrustedExplicitProxyGuardedFetchMode,
  t as GUARDED_FETCH_MODE,
} from "../fetch-guard-Da47iiZE.js";
import {
  n as buildTimeoutAbortSignal,
  r as fetchWithTimeout,
  t as bindAbortRelay,
} from "../fetch-timeout-CAJNUHY1.js";
import {
  a as resetFileLockStateForTest,
  i as drainFileLockStateForTest,
  n as FILE_LOCK_TIMEOUT_ERROR_CODE,
  o as withFileLock,
  r as acquireFileLock,
} from "../file-lock-C2Kr7iLJ.js";
import {
  i as formatDurationSeconds,
  n as formatDurationHuman,
  r as formatDurationPrecise,
  t as formatDurationCompact,
} from "../format-duration-DKk9BtRb.js";
import {
  C as resolveAbsolutePathForRead,
  S as findExistingAncestor,
  _ as resolveLocalPathFromRootsSync,
  a as walkDirectory,
  b as assertAbsolutePathInput,
  c as withTimeout,
  g as readLocalFileFromRoots,
  i as writeFileWithinRoot,
  l as movePathToTrash,
  n as readFileWithinRoot,
  o as walkDirectorySync,
  r as writeExternalFileWithinRoot,
  s as readSecureFile,
  t as ensureAbsoluteDirectory,
  v as pathExists,
  w as resolveAbsolutePathForWrite,
  x as canonicalPathFromExistingAncestor,
  y as pathExistsSync,
} from "../fs-safe-RNq3oO57.js";
import {
  a as resolveIndicatorType,
  i as resetHeartbeatEventsForTest,
  n as getLastHeartbeatEvent,
  r as onHeartbeatEvent,
  t as emitHeartbeatEvent,
} from "../heartbeat-events-DlT3VAUF.js";
import {
  n as resolveHeartbeatIntervalMs,
  r as resolveHeartbeatSummaryForAgent,
  t as isHeartbeatEnabledForAgent,
} from "../heartbeat-summary-CrfY3Te7.js";
import { t as resolveHeartbeatVisibility } from "../heartbeat-visibility-BWEWr0c7.js";
import {
  a as resolveOsHomeRelativePath,
  c as resolveUserPath,
  i as resolveOsHomeDir,
  n as resolveEffectiveHomeDir,
  o as resolveRequiredHomeDir,
  r as resolveHomeRelativePath,
  s as resolveRequiredOsHomeDir,
  t as expandHomePrefix,
} from "../home-dir-DxrrpDft.js";
import { t as normalizeHostname } from "../hostname-DAZapKzN.js";
import {
  a as isRequestBodyLimitError,
  c as readRequestBodyWithLimit,
  f as requestBodyErrorToText,
  i as installRequestBodyLimitGuard,
  n as DEFAULT_WEBHOOK_MAX_BODY_BYTES,
  p as testApi,
  r as RequestBodyLimitError,
  s as readJsonBodyWithLimit,
  t as DEFAULT_WEBHOOK_BODY_TIMEOUT_MS,
} from "../http-body-aoMvQQlg.js";
import {
  n as resolveAgentOutboundIdentity,
  t as normalizeOutboundIdentity,
} from "../identity-SEW64WfD.js";
import {
  a as readRootJsonObjectSync,
  c as tryReadJsonSync,
  i as readJsonSync,
  l as writeJson,
  o as readRootJsonSync,
  s as readRootStructuredFileSync,
  t as JsonFileReadError,
  u as writeJsonSync,
} from "../json-7OTJmMaB.js";
import "../file-lock-CsC2zkbH.js";
import {
  a as readJsonIfExists,
  i as readJsonFileStrict,
  n as readJson,
  o as tryReadJson,
  r as readJsonFile,
  s as writeTextAtomic,
  t as readDurableJsonFile,
} from "../json-files-CTWRDHag.js";
import { t as pruneMapToMaxSize } from "../map-size-DAGm21RM.js";
import "../local-file-access-CBe_wA_B.js";
import {
  E as resolveExpiresAtMsFromEpochSeconds,
  O as resolveNonNegativeIntegerOption,
  T as resolveExpiresAtMsFromDurationSeconds,
  _ as parseStrictFiniteNumber,
  b as parseStrictPositiveInteger,
  f as clampTimerTimeoutMs,
  g as parseFiniteNumber,
  h as nonNegativeSecondsToSafeMilliseconds,
  n as MAX_TIMER_TIMEOUT_MS,
  p as finiteSecondsToTimerSafeMilliseconds,
  r as MAX_TIMER_TIMEOUT_SECONDS,
  v as parseStrictInteger,
  w as resolveExpiresAtMsFromDurationOrEpoch,
  x as positiveSecondsToSafeMilliseconds,
  y as parseStrictNonNegativeInteger,
} from "../number-coercion-CJQ8TR--.js";
import {
  C as FsSafeError,
  S as trySafeFileURLToPath,
  _ as basenameFromMediaSource,
  b as isWindowsNetworkPath,
  g as assertNoWindowsNetworkPath,
  i as isPathInside,
  v as hasEncodedFileUrlSeparator,
  x as safeFileURLToPath,
} from "../path-DILYn_gk.js";
import "../backoff-Z63_cX9p.js";
import {
  a as PLUGIN_APPROVAL_TITLE_MAX_LENGTH,
  c as buildPluginApprovalRequestMessage,
  d as resolvePluginApprovalTimeoutMs,
  i as PLUGIN_APPROVAL_DESCRIPTION_MAX_LENGTH,
  l as buildPluginApprovalResolvedMessage,
  n as DEFAULT_PLUGIN_APPROVAL_TIMEOUT_MS,
  o as approvalDecisionLabel,
  r as MAX_PLUGIN_APPROVAL_TIMEOUT_MS,
  s as buildPluginApprovalExpiredMessage,
  t as DEFAULT_PLUGIN_APPROVAL_DECISIONS,
  u as resolvePluginApprovalRequestAllowedDecisions,
} from "../plugin-approvals-D2muXfhg.js";
import { t as stripInternalRuntimeScaffolding } from "../protocol-scaffolding-DMClPiYZ.js";
import {
  a as matchesNoProxy,
  c as shouldUseEnvHttpProxyForUrl,
  i as hasProxyEnvConfigured,
  n as hasEnvHttpProxyAgentConfigured,
  o as resolveEnvHttpProxyAgentOptions,
  r as hasEnvHttpProxyConfigured,
  s as resolveEnvHttpProxyUrl,
  t as PROXY_ENV_KEYS,
} from "../proxy-env-5nRGQyQD.js";
import {
  i as resolveProxyFetchFromEnv,
  n as getProxyUrlFromFetch,
  r as makeProxyFetch,
  t as PROXY_FETCH_PROXY_URL,
} from "../proxy-fetch-BNm7PiNO.js";
import {
  a as resolveRegularFileAppendFlags,
  i as readRegularFileSync,
  n as appendRegularFileSync,
  o as statRegularFile,
  r as readRegularFile,
  s as statRegularFileSync,
  t as appendRegularFile,
} from "../regular-file-CuvhUtZS.js";
import { t as retryAsync } from "../retry-CcVvEFm0.js";
import {
  n as createChannelApiRetryRunner,
  r as createRateLimitRetryRunner,
  t as CHANNEL_API_RETRY_DEFAULTS,
} from "../retry-policy-ib5882j9.js";
import { t as runTasksWithConcurrency } from "../run-with-concurrency-BHgpSCM6.js";
import { n as fetchWithRuntimeDispatcher } from "../runtime-fetch-0IXFHW_8.js";
import { n as createRuntimeOutboundDelegates } from "../runtime-forwarders-Dxil5z45.js";
import { t as sanitizeForPlainText } from "../sanitize-text-BCxyPW9Z.js";
import {
  i as normalizeScpRemotePath,
  n as isSafeScpRemotePath,
  r as normalizeScpRemoteHost,
  t as isSafeScpRemoteHost,
} from "../scp-host-BtrM4IVE.js";
import { t as loadSecretFileSync } from "../secret-file-BMs7qbMt.js";
import {
  a as tryReadSecretFileSync,
  i as readSecretFileSync,
  n as PRIVATE_SECRET_DIR_MODE,
  o as writeSecretFileAtomic,
  r as PRIVATE_SECRET_FILE_MODE,
  t as DEFAULT_SECRET_FILE_MAX_BYTES,
} from "../secret-file-C3z_7aGt.js";
import {
  a as generateSecureUuid,
  i as generateSecureToken,
  n as generateSecureHex,
  r as generateSecureInt,
  t as generateSecureFraction,
} from "../secure-random-Ds4AFLgz.js";
import {
  a as root,
  i as readLocalFileSafely,
  r as openLocalFileSafely,
  u as resolveOpenedFileRealPathForHandle,
} from "../secure-temp-dir-DMUMnweR.js";
import {
  n as resolveOutboundSendDep,
  t as resolveLegacyOutboundSendDepKeys,
} from "../send-deps-DjbvQHZ4.js";
import { r as sanitizeUntrustedFileName } from "../sibling-temp-B46XkYIp.js";
import {
  a as resolveRetryConfig,
  n as computeBackoff,
  s as sleepWithAbort,
} from "../src-Dqmh2693.js";
import {
  _ as resolvePinnedHostnameWithPolicy,
  a as createPinnedDispatcher,
  b as ssrfPolicyFromHttpBaseUrlAllowedOrigin,
  c as isBlockedHostnameOrIp,
  d as isPrivateNetworkAllowedByPolicy,
  f as isSameSsrFPolicy,
  g as resolvePinnedHostname,
  h as normalizeHostnameAllowlist,
  i as closeDispatcher,
  l as isHostnameAllowedByPattern,
  m as mergeSsrFPolicies,
  n as assertHostnameAllowedWithPolicy,
  o as createPinnedLookup,
  p as matchesHostnameAllowlist,
  r as assertPublicHostname,
  s as isBlockedHostname,
  t as SsrFBlockedError,
  u as isPrivateIpAddress,
  v as resolveSsrFPolicyForUrl,
  x as ssrfPolicyFromHttpBaseUrlFakeIpHostnameAllowlist,
  y as ssrfPolicyFromHttpBaseUrlAllowedHostname,
} from "../ssrf-keFRGQLq.js";
import {
  a as isHttpsUrlAllowedByHostnameSuffixAllowlist,
  c as normalizeHostnameSuffixAllowlist,
  d as ssrfPolicyFromPrivateNetworkOptIn,
  i as hasLegacyFlatAllowPrivateNetworkAlias,
  l as ssrfPolicyFromAllowPrivateNetwork,
  n as buildHostnameAllowlistPolicyFromSuffixAllowlist,
  o as isPrivateNetworkOptInEnabled,
  r as createLegacyPrivateNetworkDoctorContract,
  s as migrateLegacyFlatAllowPrivateNetworkAlias,
  t as assertHttpUrlTargetsPrivateNetwork,
  u as ssrfPolicyFromDangerouslyAllowPrivateNetwork,
} from "../ssrf-policy-zxv5oRW2.js";
import {
  a as enqueueSystemEvent,
  c as isSystemEventContextChanged,
  d as resetSystemEventsForTest,
  f as resolveSystemEventDeliveryContext,
  i as drainSystemEvents,
  l as peekSystemEventEntries,
  n as consumeSystemEventEntries,
  o as enqueueSystemEventEntry,
  r as drainSystemEventEntries,
  s as hasSystemEvents,
  t as consumeSelectedSystemEventEntries,
  u as peekSystemEvents,
} from "../system-events-CIAdjAwz.js";
import {
  n as hasSystemMark,
  r as prefixSystemMessage,
  t as SYSTEM_MARK,
} from "../system-message-Dltw0_t9.js";
import {
  n as resolvePreferredOpenClawTmpDir,
  t as POSIX_OPENCLAW_TMP_DIR,
} from "../tmp-openclaw-dir-uPgNO8da.js";
import { t as waitForTransportReady } from "../transport-ready-B0PBRD38.js";
import {
  a as forceResetGlobalDispatcher,
  i as ensureGlobalUndiciStreamTimeouts,
  n as ensureGlobalUndiciDispatcherStreamTimeouts,
  o as globalUndiciStreamTimeoutMs,
  r as ensureGlobalUndiciEnvProxyDispatcher,
  s as resetGlobalUndiciStreamTimeoutsForTests,
  t as DEFAULT_UNDICI_STREAM_TIMEOUT_MS,
} from "../undici-global-dispatcher-BoVfmODy.js";
import {
  d as isWSLEnv,
  f as isWSLSync,
  l as isWSL,
  p as resetWSLStateForTests,
  u as isWSL2Sync,
} from "../undici-runtime-Bm6J6FAw.js";
//#region src/plugin-sdk/infra-runtime.ts
/**
 * @deprecated Shipped compat only; preserves the old substring semantics for
 * external plugins. Core chat classification now maps canonical failover
 * reasons (see gateway resolveChatErrorKindFromError). Removal with the next
 * plugin-SDK major.
 */
function detectErrorKind(err) {
  if (err === void 0) return;
  const message = formatErrorMessage(err).toLowerCase();
  const code = extractErrorCode(err)?.toLowerCase();
  if (
    message.includes("refusal") ||
    message.includes("content_filter") ||
    message.includes("sensitive") ||
    message.includes("unhandled stop reason: refusal_policy")
  )
    return "refusal";
  if (
    message.includes("rate limit") ||
    message.includes("too many requests") ||
    message.includes("429") ||
    code === "429"
  )
    return "rate_limit";
  if (message.includes("timeout") || code === "etimedout" || code === "timeout") return "timeout";
  if (
    message.includes("context length") ||
    message.includes("too many tokens") ||
    message.includes("token limit") ||
    message.includes("context_window")
  )
    return "context_length";
}
//#endregion
export {
  CHANNEL_API_RETRY_DEFAULTS,
  DEFAULT_EXEC_APPROVAL_ASK_FALLBACK,
  DEFAULT_EXEC_APPROVAL_DECISIONS,
  DEFAULT_EXEC_APPROVAL_TIMEOUT_MS,
  DEFAULT_PLUGIN_APPROVAL_DECISIONS,
  DEFAULT_PLUGIN_APPROVAL_TIMEOUT_MS,
  DEFAULT_SECRET_FILE_MAX_BYTES,
  DEFAULT_UNDICI_STREAM_TIMEOUT_MS,
  DEFAULT_WEBHOOK_BODY_TIMEOUT_MS,
  DEFAULT_WEBHOOK_MAX_BODY_BYTES,
  EXEC_TARGET_VALUES,
  ExecApprovalChannelRuntimeTerminalStartError,
  FILE_LOCK_TIMEOUT_ERROR_CODE,
  FsSafeError,
  GUARDED_FETCH_MODE,
  JsonFileReadError,
  MAX_PLUGIN_APPROVAL_TIMEOUT_MS,
  MAX_TIMER_TIMEOUT_MS,
  MAX_TIMER_TIMEOUT_SECONDS,
  OPTIONAL_EXEC_APPROVAL_DECISIONS,
  PLUGIN_APPROVAL_DESCRIPTION_MAX_LENGTH,
  PLUGIN_APPROVAL_TITLE_MAX_LENGTH,
  POSIX_OPENCLAW_TMP_DIR,
  PRIVATE_SECRET_DIR_MODE,
  PRIVATE_SECRET_FILE_MODE,
  PROXY_ENV_KEYS,
  PROXY_FETCH_PROXY_URL,
  RequestBodyLimitError,
  SYSTEM_MARK,
  SsrFBlockedError,
  testApi as __test__,
  testApi,
  acquireFileLock,
  addAllowlistEntry,
  addDurableCommandApproval,
  analyzeArgvCommand,
  analyzeWindowsShellCommand,
  appendRegularFile,
  appendRegularFileSync,
  approvalDecisionLabel,
  areDiagnosticsEnabledForProcess,
  assertAbsolutePathInput,
  assertHostnameAllowedWithPolicy,
  assertHttpUrlTargetsPrivateNetwork,
  assertNoWindowsNetworkPath,
  assertPublicHostname,
  basenameFromMediaSource,
  bindAbortRelay,
  buildApprovalInteractiveReplyFromActionDescriptors,
  buildApprovalPresentation,
  buildApprovalPresentationFromActionDescriptors,
  buildEnforcedShellCommand,
  buildExecApprovalActionDescriptors,
  buildExecApprovalCommandText,
  buildExecApprovalPendingReplyPayload,
  buildExecApprovalPresentation,
  buildExecApprovalUnavailableReplyPayload,
  buildHostnameAllowlistPolicyFromSuffixAllowlist,
  buildPluginApprovalExpiredMessage,
  buildPluginApprovalRequestMessage,
  buildPluginApprovalResolvedMessage,
  buildTimeoutAbortSignal,
  buildTypedApprovalActionDescriptors,
  buildTypedApprovalPresentation,
  buildTypedExecApprovalPendingReplyPayload,
  buildTypedExecApprovalPresentation,
  canonicalPathFromExistingAncestor,
  clampTimerTimeoutMs,
  closeDispatcher,
  collectErrorGraphCandidates,
  commandRequiresSecurityAuditSuppressionApproval,
  computeBackoff,
  consumeSelectedSystemEventEntries,
  consumeSystemEventEntries,
  createAsyncLock,
  createChannelApiRetryRunner,
  createChannelNativeApprovalRuntime,
  createDedupeCache,
  createExecApprovalChannelRuntime,
  createLegacyPrivateNetworkDoctorContract,
  createPinnedDispatcher,
  createPinnedLookup,
  createRateLimitRetryRunner,
  createRuntimeOutboundDelegates,
  deliverApprovalRequestViaChannelNativePlan,
  detectErrorKind,
  drainFileLockStateForTest,
  drainPendingDeliveries,
  drainSystemEventEntries,
  drainSystemEvents,
  emitDiagnosticEvent,
  emitHeartbeatEvent,
  enqueueSystemEvent,
  enqueueSystemEventEntry,
  ensureAbsoluteDirectory,
  ensureExecApprovals,
  ensureGlobalUndiciDispatcherStreamTimeouts,
  ensureGlobalUndiciEnvProxyDispatcher,
  ensureGlobalUndiciStreamTimeouts,
  evaluateExecAllowlist,
  evaluateExecAllowlistWithAuthorization,
  evaluateShellAllowlist,
  evaluateShellAllowlistWithAuthorization,
  expandEnvNormalizationKeys,
  expandHomePrefix,
  extractErrorCode,
  fetchWithRuntimeDispatcher,
  fetchWithSsrFGuard,
  fetchWithTimeout,
  findExistingAncestor,
  finiteSecondsToTimerSafeMilliseconds,
  forceResetGlobalDispatcher,
  formatApprovalDisplayPath,
  formatDurationCompact,
  formatDurationHuman,
  formatDurationPrecise,
  formatDurationSeconds,
  formatErrorMessage,
  formatExecApprovalExpiresIn,
  formatUncaughtError,
  generateSecureFraction,
  generateSecureHex,
  generateSecureInt,
  generateSecureToken,
  generateSecureUuid,
  getChannelActivity,
  getExecApprovalApproverDmNoticeText,
  getExecApprovalReplyMetadata,
  getLastHeartbeatEvent,
  getProxyUrlFromFetch,
  globalUndiciStreamTimeoutMs,
  hasDurableExecApproval,
  hasEncodedFileUrlSeparator,
  hasEnvHttpProxyAgentConfigured,
  hasEnvHttpProxyConfigured,
  hasErrnoCode,
  hasExactCommandDurableExecApproval,
  hasLegacyFlatAllowPrivateNetworkAlias,
  hasNodeCommandAllowAlwaysMarker,
  hasProxyEnvConfigured,
  hasSystemEvents,
  hasSystemMark,
  installRequestBodyLimitGuard,
  isBlockedHostname,
  isBlockedHostnameOrIp,
  isDiagnosticFlagEnabled,
  isDiagnosticsEnabled,
  isErrno,
  isExecApprovalChannelRuntimeTerminalStartError,
  isExecApprovalDecisionAllowed,
  isHeartbeatEnabledForAgent,
  isHostnameAllowedByPattern,
  isHttpsUrlAllowedByHostnameSuffixAllowlist,
  isPathInside,
  isPrivateIpAddress,
  isPrivateNetworkAllowedByPolicy,
  isPrivateNetworkOptInEnabled,
  isRequestBodyLimitError,
  isSafeBinUsage,
  isSafeScpRemoteHost,
  isSafeScpRemotePath,
  isSameSsrFPolicy,
  isSystemEventContextChanged,
  isTruthyEnvValue,
  isVitestRuntimeEnv,
  isWSL,
  isWSL2Sync,
  isWSLEnv,
  isWSLSync,
  isWindowsNetworkPath,
  isWindowsPlatform,
  loadExecApprovals,
  loadSecretFileSync,
  logAcceptedEnvOption,
  makeProxyFetch,
  matchAllowlist,
  matchesDiagnosticFlag,
  matchesHostnameAllowlist,
  matchesNoProxy,
  maxAsk,
  mergeExecApprovalsSocketDefaults,
  mergeSsrFPolicies,
  migrateLegacyFlatAllowPrivateNetworkAlias,
  minSecurity,
  movePathToTrash,
  nonNegativeSecondsToSafeMilliseconds,
  normalizeEnv,
  normalizeExecApprovalUnavailableDecisions,
  normalizeExecApprovals,
  normalizeExecAsk,
  normalizeExecHost,
  normalizeExecMode,
  normalizeExecSecurity,
  normalizeExecTarget,
  normalizeHostname,
  normalizeHostnameAllowlist,
  normalizeHostnameSuffixAllowlist,
  normalizeOutboundIdentity,
  normalizeSafeBins,
  normalizeScpRemoteHost,
  normalizeScpRemotePath,
  normalizeZaiEnv,
  onDiagnosticEvent,
  onHeartbeatEvent,
  openLocalFileSafely,
  parseExecApprovalCommandText,
  parseExecArgvToken,
  parseFiniteNumber,
  parseStrictFiniteNumber,
  parseStrictInteger,
  parseStrictNonNegativeInteger,
  parseStrictPositiveInteger,
  pathExists,
  pathExistsSync,
  peekSystemEventEntries,
  peekSystemEvents,
  persistAllowAlwaysDecision,
  persistAllowAlwaysPatterns,
  positiveSecondsToSafeMilliseconds,
  prefixSystemMessage,
  pruneMapToMaxSize,
  readDurableJsonFile,
  readErrorName,
  readExecApprovalsSnapshot,
  readFileWithinRoot,
  readJson,
  readJsonBodyWithLimit,
  readJsonFile,
  readJsonFileStrict,
  tryReadJsonSync as readJsonFileSync,
  tryReadJsonSync,
  readJsonIfExists,
  readJsonSync,
  readLocalFileFromRoots,
  readLocalFileSafely,
  readRegularFile,
  readRegularFileSync,
  readRequestBodyWithLimit,
  readRootJsonObjectSync,
  readRootJsonSync,
  readRootStructuredFileSync,
  readSecretFileSync,
  readSecureFile,
  recordAllowlistMatchesUse,
  recordAllowlistUse,
  recordChannelActivity,
  requestBodyErrorToText,
  requestExecApprovalViaSocket,
  requireValidExecTarget,
  requiresExecApproval,
  resetChannelActivityForTest,
  resetFileLockStateForTest,
  resetGlobalUndiciStreamTimeoutsForTests,
  resetHeartbeatEventsForTest,
  resetSystemEventsForTest,
  resetWSLStateForTests,
  resolveAbsolutePathForRead,
  resolveAbsolutePathForWrite,
  resolveAgentOutboundIdentity,
  resolveAllowAlwaysPatternCoverage,
  resolveAllowAlwaysPatternEntries,
  resolveAllowAlwaysPatterns,
  resolveAllowAlwaysPersistenceDecision,
  resolveAllowlistCandidatePath,
  resolveApprovalAuditCandidatePath,
  resolveApprovalAuditTrustPath,
  resolveApprovalRequestOriginTarget,
  resolveApprovalRequestSessionConversation,
  resolveApprovalRequestSessionTarget,
  resolveChannelNativeApprovalDeliveryPlan,
  resolveCommandResolution,
  resolveCommandResolutionFromArgv,
  resolveNonNegativeIntegerOption as resolveDedupeNonNegativeInteger,
  resolveDiagnosticFlags,
  resolveEffectiveHomeDir,
  resolveEnvHttpProxyAgentOptions,
  resolveEnvHttpProxyUrl,
  resolveEnvNormalizationKeys,
  resolveExecApprovalAllowedDecisions,
  resolveExecApprovalCommandDisplay,
  resolveExecApprovalRequestAllowedDecisions,
  resolveExecApprovalSessionTarget,
  resolveExecApprovalUnavailableDecisions,
  resolveExecApprovals,
  resolveExecApprovalsDisplayPath,
  resolveExecApprovalsFromFile,
  resolveExecApprovalsPath,
  resolveExecApprovalsSocketPath,
  resolveExecApprovalsTranscriptPath,
  resolveExecModeFromPolicy,
  resolveExecModePolicy,
  resolveExecPolicyForMode,
  resolveExecutableTrustPath,
  resolveExecutionTargetCandidatePath,
  resolveExecutionTargetResolution,
  resolveExecutionTargetTrustPath,
  resolveExpiresAtMsFromDurationOrEpoch,
  resolveExpiresAtMsFromDurationSeconds,
  resolveExpiresAtMsFromEpochSeconds,
  resolveFetch,
  resolveGlobalDedupeCache,
  resolveHeartbeatIntervalMs,
  resolveHeartbeatSummaryForAgent,
  resolveHeartbeatVisibility,
  resolveHomeRelativePath,
  resolveIndicatorType,
  resolveLegacyOutboundSendDepKeys,
  resolveLocalPathFromRootsSync,
  resolveOpenedFileRealPathForHandle,
  resolveOsHomeDir,
  resolveOsHomeRelativePath,
  resolveOutboundSendDep,
  resolvePinnedHostname,
  resolvePinnedHostnameWithPolicy,
  resolvePlannedSegmentArgv,
  resolvePluginApprovalRequestAllowedDecisions,
  resolvePluginApprovalTimeoutMs,
  resolvePolicyAllowlistCandidatePath,
  resolvePolicyTargetCandidatePath,
  resolvePolicyTargetResolution,
  resolvePolicyTargetTrustPath,
  resolvePreferredOpenClawTmpDir,
  resolveProxyFetchFromEnv,
  resolveRegularFileAppendFlags,
  resolveRequiredHomeDir,
  resolveRequiredOsHomeDir,
  resolveRetryConfig,
  resolveSafeBins,
  resolveSsrFPolicyForUrl,
  resolveSystemEventDeliveryContext,
  resolveUserPath,
  restoreExecApprovalsSnapshot,
  retainSafeHeadersForCrossOriginRedirectHeaders,
  retryAsync,
  root,
  runTasksWithConcurrency,
  safeFileURLToPath,
  sanitizeExecApprovalDisplayText,
  sanitizeExecApprovalDisplayTextWithStatus,
  sanitizeExecApprovalWarningText,
  sanitizeForPlainText,
  sanitizeUntrustedFileName,
  saveExecApprovals,
  shouldUseEnvHttpProxyForUrl,
  sleepWithAbort,
  ssrfPolicyFromAllowPrivateNetwork,
  ssrfPolicyFromDangerouslyAllowPrivateNetwork,
  ssrfPolicyFromHttpBaseUrlAllowedHostname,
  ssrfPolicyFromHttpBaseUrlAllowedOrigin,
  ssrfPolicyFromHttpBaseUrlFakeIpHostnameAllowlist,
  ssrfPolicyFromPrivateNetworkOptIn,
  statRegularFile,
  statRegularFileSync,
  stringifyNonErrorCause,
  stripInternalRuntimeScaffolding,
  toErrorObject,
  tokenizeWindowsSegment,
  tryReadJson,
  tryReadSecretFileSync,
  trySafeFileURLToPath,
  waitForTransportReady,
  walkDirectory,
  walkDirectorySync,
  windowsEscapeArg,
  withFileLock,
  withStrictGuardedFetchMode,
  withTimeout,
  withTrustedEnvProxyGuardedFetchMode,
  withTrustedExplicitProxyGuardedFetchMode,
  wrapFetchWithAbortSignal,
  writeExternalFileWithinRoot,
  writeFileWithinRoot,
  writeJson,
  writeJson as writeJsonAtomic,
  writeJsonSync,
  writeSecretFileAtomic as writePrivateSecretFileAtomic,
  writeTextAtomic,
};
