import {
  n as listProviderPluginCommandSpecs,
  t as getPluginCommandSpecs,
} from "../command-specs-BOef40SY.js";
import {
  a as registerPluginCommand,
  c as clearPluginCommands,
  i as testing,
  l as clearPluginCommandsForPlugin,
  n as listPluginCommands,
  o as validateCommandName,
  r as matchPluginCommand,
  s as validatePluginCommandDefinition,
  t as executePluginCommand,
  u as listRegisteredPluginAgentPromptGuidance,
} from "../commands-BM8gUVov.js";
import { r as AnyAgentTool } from "../common-CuQ9SS3Z.js";
import {
  a as PluginConversationBindingResolvedEvent,
  i as PluginConversationBindingResolutionDecision,
  n as PluginConversationBindingRequestParams,
  r as PluginConversationBindingRequestResult,
  t as PluginConversationBinding,
} from "../conversation-binding.types-FpB9wxq5.js";
import {
  a as resetGlobalHookRunner,
  i as initializeGlobalHookRunner,
  n as getGlobalPluginRegistry,
  o as runGlobalGatewayStopSafely,
  r as hasGlobalHooks,
  t as getGlobalHookRunner,
} from "../hook-runner-global-CTCX7Vbc.js";
import {
  $ as PluginHookLlmOutputEvent,
  $t as PluginHookMessageReceivedEvent,
  A as PluginHookBeforeMessageWriteEvent,
  At as PluginHookToolResultPersistContext,
  B as PluginHookGatewayCronCreateInput,
  Bt as isPluginHookName,
  C as PluginHookBeforeInstallContext,
  Ct as PluginHookSubagentSpawnedEvent,
  D as PluginHookBeforeInstallResult,
  Dt as PluginHookToolContext,
  E as PluginHookBeforeInstallRequest,
  Et as PluginHookSubagentTargetKind,
  F as PluginHookCronChangedEvent,
  Ft as PluginInstallSourcePathKind,
  G as PluginHookGatewayCronRunStatus,
  Gt as PluginHeartbeatPromptContributionResult,
  H as PluginHookGatewayCronJob,
  Ht as PluginAgentTurnPrepareEvent,
  I as PluginHookCronReconciledContext,
  It as PluginInstallTargetType,
  J as PluginHookGatewayStartEvent,
  Jt as PluginNextTurnInjectionRecord,
  K as PluginHookGatewayCronService,
  Kt as PluginNextTurnInjection,
  L as PluginHookCronReconciledEvent,
  Lt as PromptInjectionHookName,
  M as PluginHookBeforeResetEvent,
  Mt as PluginHookToolResultPersistResult,
  N as PluginHookBeforeToolCallEvent,
  Nt as PluginInstallFinding,
  O as PluginHookBeforeInstallSkill,
  Ot as PluginHookToolInputKind,
  P as PluginHookContextWindowSource,
  Pt as PluginInstallRequestKind,
  Q as PluginHookLlmInputEvent,
  Qt as PluginHookMessageContext,
  R as PluginHookDeprecation,
  Rt as isConversationHookName,
  S as PluginHookBeforeInstallBuiltinScan,
  St as PluginHookSubagentEndedEvent,
  T as PluginHookBeforeInstallPlugin,
  Tt as PluginHookSubagentSpawningResult,
  U as PluginHookGatewayCronJobState,
  Ut as PluginAgentTurnPrepareResult,
  V as PluginHookGatewayCronDeliveryStatus,
  Vt as isPromptInjectionHookName,
  W as PluginHookGatewayCronRemoveResult,
  Wt as PluginHeartbeatPromptContributionEvent,
  X as PluginHookHandlerMap,
  Xt as PluginHookInboundClaimContext,
  Y as PluginHookGatewayStopEvent,
  Yt as PluginJsonValue,
  Z as PluginHookInboundClaimResult,
  Zt as PluginHookInboundClaimEvent,
  _ as PluginHookBeforeAgentRunResult,
  _n as stripPromptMutationFieldsFromLegacyHookResult,
  _t as PluginHookSessionEndReason,
  a as DeprecatedPluginHookName,
  an as PluginApprovalResolution,
  at as PluginHookReplyDispatchContext,
  b as PluginHookBeforeDispatchEvent,
  bt as PluginHookSubagentDeliveryTargetEvent,
  c as PluginHookAfterCompactionEvent,
  cn as PLUGIN_PROMPT_MUTATION_RESULT_FIELDS,
  ct as PluginHookReplyPayload,
  d as PluginHookAgentEndEvent,
  dn as PluginHookBeforeAgentStartResult,
  dt as PluginHookReplyPayloadSendingResult,
  en as PluginHookMessageSendingEvent,
  et as PluginHookModelCallBaseEvent,
  f as PluginHookBeforeAgentFinalizeEvent,
  fn as PluginHookBeforeModelResolveAttachment,
  ft as PluginHookReplyUsageState,
  g as PluginHookBeforeAgentRunEvent,
  gn as PluginHookBeforePromptBuildResult,
  gt as PluginHookSessionEndEvent,
  h as PluginHookBeforeAgentReplyResult,
  hn as PluginHookBeforePromptBuildEvent,
  ht as PluginHookSessionContext,
  i as DEPRECATED_PLUGIN_HOOK_NAMES,
  it as PluginHookRegistration,
  j as PluginHookBeforeMessageWriteResult,
  jt as PluginHookToolResultPersistEvent,
  k as PluginHookBeforeInstallSkillInstallSpec,
  kt as PluginHookToolKind,
  l as PluginHookAfterToolCallEvent,
  ln as PluginHookBeforeAgentStartEvent,
  lt as PluginHookReplyPayloadSendingContext,
  m as PluginHookBeforeAgentReplyEvent,
  mn as PluginHookBeforeModelResolveResult,
  mt as PluginHookResolveExecEnvEvent,
  n as ConversationHookName,
  nn as PluginHookMessageSentEvent,
  nt as PluginHookModelCallStartedEvent,
  o as PLUGIN_HOOK_NAMES,
  on as PluginApprovalResolutions,
  ot as PluginHookReplyDispatchEvent,
  p as PluginHookBeforeAgentFinalizeResult,
  pn as PluginHookBeforeModelResolveEvent,
  pt as PluginHookResolveExecEnvContext,
  q as PluginHookGatewayCronUpdateInput,
  qt as PluginNextTurnInjectionEnqueueResult,
  r as DEPRECATED_PLUGIN_HOOKS,
  rt as PluginHookName,
  s as PROMPT_INJECTION_HOOK_NAMES,
  sn as PluginHookBeforeToolCallResult,
  st as PluginHookReplyDispatchResult,
  t as CONVERSATION_HOOK_NAMES,
  tn as PluginHookMessageSendingResult,
  tt as PluginHookModelCallEndedEvent,
  u as PluginHookAgentContext,
  un as PluginHookBeforeAgentStartOverrideResult,
  ut as PluginHookReplyPayloadSendingEvent,
  v as PluginHookBeforeCompactionEvent,
  vt as PluginHookSessionStartEvent,
  w as PluginHookBeforeInstallEvent,
  wt as PluginHookSubagentSpawningEvent,
  x as PluginHookBeforeDispatchResult,
  xt as PluginHookSubagentDeliveryTargetResult,
  y as PluginHookBeforeDispatchContext,
  yt as PluginHookSubagentContext,
  z as PluginHookGatewayContext,
  zt as isDeprecatedPluginHookName,
} from "../hook-types-BPL4xByC.js";
import { t as normalizePluginHttpPath } from "../http-path-BQYXN9ah.js";
import {
  n as registerPluginHttpRoute,
  r as withPluginHttpRouteRegistry,
  t as PluginHttpRouteHandler,
} from "../http-registry-Bu61EERF.js";
import {
  _ as PluginConfigUiHint,
  f as PluginKind,
  g as PluginBundleFormat,
  v as PluginDiagnostic,
  y as PluginFormat,
} from "../manifest-registry-CHEq75Tu.js";
import { t as PluginOrigin } from "../plugin-origin.types-DOQEvsWL.js";
import {
  a as PluginInteractiveMatch,
  c as clearPluginInteractiveHandlers,
  d as createInteractiveConversationBindingHelpers,
  i as startLazyPluginServiceModule,
  l as clearPluginInteractiveHandlersForPlugin,
  n as LazyPluginServiceHandle,
  o as dispatchPluginInteractiveHandler,
  r as defaultLoadOverrideModule,
  s as InteractiveRegistrationResult,
  t as getPluginRuntimeGatewayRequestScope,
  u as registerPluginInteractiveHandler,
} from "../plugin-runtime-BIrVN1rn.js";
import {
  g as PluginHookChannelSenderContext,
  h as PluginHookChannelContext,
  m as PluginHookChannelChatContext,
} from "../templating-h3OQefFR.js";
import {
  $ as OpenClawPluginServiceContext,
  $i as CliBackendPlugin,
  $n as WorkerProvider,
  $t as ProviderNonInteractiveApiKeyResult,
  $u as ProviderDefaultThinkingPolicyContext,
  A as OpenClawPluginDefinition,
  Ai as PluginSessionActionContext,
  An as ProviderResolveWebSocketSessionPolicyContext,
  At as ProviderBuildUnknownModelHintContext,
  B as OpenClawPluginModule,
  Bi as PluginSessionTurnUnscheduleByTagParams,
  Bl as OpenClawPluginActiveModelContext,
  Bn as ProviderValidateReplayTurnsContext,
  Bt as ProviderDeferSyntheticProfileAuthContext,
  C as OpenClawPluginApi,
  Ci as PluginAgentEventEmitParams,
  Cn as ProviderReplayToolCallIdMode,
  Ct as ProviderAuthContext,
  D as OpenClawPluginCliRegistrar,
  Di as PluginRunContextGetParams,
  Dn as ProviderResolvePromptOverlayContext,
  Dt as ProviderAuthMethodNonInteractiveContext,
  E as OpenClawPluginCliContext,
  Ei as PluginControlUiDescriptor,
  En as ProviderResolveNonInteractiveApiKeyParams,
  Et as ProviderAuthMethod,
  F as OpenClawPluginHttpRouteHandler,
  Fi as PluginSessionExtensionProjection,
  Fn as ProviderToolSchemaDiagnostic,
  Ft as ProviderCatalogContext,
  G as OpenClawPluginNodeInvokePolicyContext,
  Gn as SpeechProviderPlugin,
  Gt as ProviderExtraParamsForTransportResult,
  H as OpenClawPluginNodeInvokeApprovalDecision,
  Hi as PluginToolMetadataRegistration,
  Hl as OpenClawPluginToolContext,
  Hn as ProviderWrapStreamFnContext,
  Ht as ProviderDiscoveryOrder,
  I as OpenClawPluginHttpRouteMatch,
  Ii as PluginSessionExtensionRegistration,
  In as ProviderTransformSystemPromptContext,
  It as ProviderCatalogOrder,
  J as OpenClawPluginReloadRegistration,
  Jn as UnifiedModelCatalogProviderPlugin,
  Jt as ProviderFollowupFallbackRouteContext,
  K as OpenClawPluginNodeInvokePolicyResult,
  Ka as AgentHarness,
  Kn as TranscriptSourceProvider,
  Kt as ProviderFailoverErrorContext,
  L as OpenClawPluginHttpRouteParams,
  Li as PluginSessionSchedulerJobHandle,
  Ln as ProviderTransportThinkingLevel,
  Lt as ProviderCatalogResult,
  M as OpenClawPluginGatewayRuntimeScopeSurface,
  Mi as PluginSessionActionResult,
  Mn as ProviderRuntimeProviderConfig,
  Mt as ProviderBuiltInModelSuppressionResult,
  N as OpenClawPluginHostedMediaResolver,
  Ni as PluginSessionAttachmentParams,
  Nn as ProviderSanitizeReplayHistoryContext,
  Nt as ProviderCacheTtlEligibilityContext,
  O as OpenClawPluginCommandDefinition,
  Oi as PluginRunContextPatch,
  On as ProviderResolveTransportTurnStateContext,
  Ot as ProviderAuthResult,
  P as OpenClawPluginHttpRouteAuth,
  Pi as PluginSessionAttachmentResult,
  Pn as ProviderSystemPromptContributionContext,
  Pt as ProviderCapabilities,
  Q as OpenClawPluginService,
  Qi as CliBackendNormalizeConfigContext,
  Qn as WorkerProfile,
  Qt as ProviderNonInteractiveApiKeyCredentialParams,
  R as OpenClawPluginHttpRouteUpgradeHandler,
  Ri as PluginSessionSchedulerJobRegistration,
  Rn as ProviderTransportTurnState,
  Rt as ProviderCreateEmbeddingProviderContext,
  S as OpenClawPluginAgentEventsApi,
  Si as PluginLogger,
  Sn as ProviderReplaySessionState,
  St as ProviderAugmentModelCatalogContext,
  T as OpenClawPluginCliCommandDescriptor,
  Ti as PluginAgentEventSubscriptionRegistration,
  Tn as ProviderResolveDynamicModelContext,
  Tt as ProviderAuthKind,
  U as OpenClawPluginNodeInvokePolicy,
  Ui as PluginTrustedToolPolicyRegistration,
  Ul as OpenClawPluginToolFactory,
  Un as RealtimeTranscriptionProviderPlugin,
  Ut as ProviderDiscoveryResult,
  V as OpenClawPluginNodeCliFeatureOptions,
  Vi as PluginSessionTurnUnscheduleByTagResult,
  Vl as OpenClawPluginHookOptions,
  Vn as ProviderWebSocketSessionPolicy,
  Vt as ProviderDiscoveryContext,
  W as OpenClawPluginNodeInvokePolicyApprovalRuntime,
  Wl as OpenClawPluginToolOptions,
  Wn as RealtimeVoiceProviderPlugin,
  Wt as ProviderExtraParamsForTransportContext,
  X as OpenClawPluginSecurityAuditCollector,
  Xi as CliBackendExecutionMode,
  Xn as WorkerLease,
  Xt as ProviderModelSelectedContext,
  Y as OpenClawPluginRunContextApi,
  Yi as CliBackendAuthEpochMode,
  Yn as VideoGenerationProviderPlugin,
  Yt as ProviderFollowupFallbackRouteResult,
  Z as OpenClawPluginSecurityAuditContext,
  Zc as RuntimeLogger,
  Zi as CliBackendNativeToolMode,
  Zn as WorkerLeaseStatus,
  Zt as ProviderModernModelPolicyContext,
  _ as MigrationSummary,
  _a as OpenClawAgentToolResult,
  _n as ProviderReasoningOutputModeContext,
  _t as PluginSetupAutoEnableContext,
  _u as WebSearchRuntimeMetadataContext,
  a as ImageGenerationProviderPlugin,
  aa as CliBackendSideQuestionToolMode,
  ad as ProviderAuthOptionBag,
  an as ProviderPlugin,
  ar as OpenClawPluginNodeHostCommandAvailabilityContext,
  at as PluginCommandDiagnosticsSession,
  au as WebFetchProviderContext,
  b as OpenClawGatewayDiscoveryService,
  bi as ProviderNormalizeConfigContext,
  bn as ProviderReplaySanitizeMode,
  bt as PluginTextTransformRegistration,
  c as MigrationDetection,
  ca as PluginTextReplacement,
  cd as ProviderResolveExternalAuthProfilesContext,
  cn as ProviderPluginWizard,
  cr as PluginRuntime,
  ct as PluginConfigMigration,
  cu as WebFetchProviderToolDefinition,
  d as MigrationItemKind,
  da as AgentToolResultMiddlewareContext,
  dd as ProviderSyntheticAuthResult,
  dn as ProviderPreferRuntimeResolvedModelContext,
  dt as PluginInteractiveHandlerRegistration,
  du as WebSearchProviderContext,
  ea as CliBackendPrepareExecutionContext,
  ed as ProviderThinkingPolicyContext,
  en as ProviderNormalizeModelIdContext,
  er as WorkerProviderError,
  et as OpenClawPluginSessionApi,
  f as MigrationItemStatus,
  fa as AgentToolResultMiddlewareEvent,
  fn as ProviderPrepareDynamicModelContext,
  ft as PluginInteractiveHandlerResult,
  fu as WebSearchProviderId,
  g as MigrationProviderPreparation,
  ga as AgentToolResultMiddlewareRuntime,
  gn as ProviderReasoningOutputMode,
  gt as PluginRegistrationMode,
  gu as WebSearchProviderToolExecutionContext,
  h as MigrationProviderPlugin,
  ha as AgentToolResultMiddlewareResult,
  hn as ProviderPreparedRuntimeAuth,
  ht as PluginRealtimeVoiceProviderEntry,
  hu as WebSearchProviderToolDefinition,
  i as AgentPromptSurfaceKind,
  in as ProviderOAuthProfileIdRepair,
  ir as OpenClawPluginNodeHostCommand,
  it as PluginCommandContext,
  iu as WebFetchCredentialResolutionSource,
  j as OpenClawPluginGatewayMethod,
  ji as PluginSessionActionRegistration,
  jn as ProviderResolvedUsageAuth,
  jt as ProviderBuiltInModelSuppressionContext,
  k as OpenClawPluginConfigSchema,
  ki as PluginRuntimeLifecycleRegistration,
  kn as ProviderResolveUsageAuthContext,
  kt as ProviderBuildMissingAuthMessageContext,
  l as MigrationItem,
  la as PluginTextTransforms,
  ld as ProviderResolveExternalOAuthProfilesContext,
  ln as ProviderPluginWizardModelPicker,
  lt as PluginConfigValidation,
  lu as WebFetchRuntimeMetadataContext,
  m as MigrationProviderContext,
  ma as AgentToolResultMiddlewareOptions,
  mn as ProviderPrepareRuntimeAuthContext,
  mt as PluginRealtimeTranscriptionProviderEntry,
  mu as WebSearchProviderSetupContext,
  n as AgentPromptGuidance,
  na as CliBackendResolveExecutionArgs,
  nd as ProviderRuntimeModel,
  nn as ProviderNormalizeToolSchemasContext,
  nr as WorkerSshIdentity,
  nt as OpenClawPluginSessionStateApi,
  nu as PluginWebFetchProviderEntry,
  o as MediaUnderstandingProviderPlugin,
  oa as CliBackendThinkingLevel,
  od as ProviderExternalAuthProfile,
  on as ProviderPluginCatalog,
  or as OpenClawPluginNodeHostCommandIo,
  ot as PluginCommandHandler,
  ou as WebFetchProviderId,
  p as MigrationPlan,
  pa as AgentToolResultMiddlewareHarness,
  pn as ProviderPrepareExtraParamsContext,
  pt as PluginInteractiveRegistration,
  pu as WebSearchProviderPlugin,
  q as OpenClawPluginNodeInvokeTransportResult,
  qn as UnifiedModelCatalogProviderContext,
  qt as ProviderFetchUsageSnapshotContext,
  r as AgentPromptGuidanceEntry,
  ra as CliBackendResolveExecutionArgsContext,
  rn as ProviderNormalizeTransportContext,
  rr as WorkerSshIdentityRequest,
  rt as OpenClawPluginSessionWorkflowApi,
  ru as PluginWebSearchProviderEntry,
  s as MigrationApplyResult,
  sa as CliBundleMcpMode,
  sd as ProviderExternalOAuthProfile,
  sn as ProviderPluginDiscovery,
  st as PluginCommandResult,
  su as WebFetchProviderPlugin,
  t as AGENT_PROMPT_SURFACE_KINDS,
  ta as CliBackendPreparedExecution,
  td as ProviderThinkingProfile,
  tn as ProviderNormalizeResolvedModelContext,
  tr as WorkerSshEndpoint,
  tt as OpenClawPluginSessionControlsApi,
  u as MigrationItemAction,
  ua as AgentToolResultMiddleware,
  ud as ProviderResolveSyntheticAuthContext,
  un as ProviderPluginWizardSetup,
  ut as PluginEmbeddingProvider,
  uu as WebSearchCredentialResolutionSource,
  v as MusicGenerationProviderPlugin,
  vn as ProviderReplayPolicy,
  vt as PluginSetupAutoEnableProbe,
  w as OpenClawPluginChannelRegistration,
  wi as PluginAgentEventEmitResult,
  wn as ProviderResolveAuthProfileIdContext,
  wt as ProviderAuthDoctorHintContext,
  x as OpenClawPluginAgentApi,
  xi as ProviderResolveConfigApiKeyContext,
  xn as ProviderReplaySessionEntry,
  xt as PluginTranscriptsSourceProviderEntry,
  y as OpenClawGatewayDiscoveryAdvertiseContext,
  yi as ProviderApplyConfigDefaultsContext,
  yn as ProviderReplayPolicyContext,
  yt as PluginSpeechProviderEntry,
  z as OpenClawPluginLifecycleApi,
  zi as PluginSessionTurnScheduleParams,
  zn as ProviderUsageAuthToken,
  zt as ProviderCreateStreamFnContext,
} from "../types-Ga3mNO_F.js";
export {
  AGENT_PROMPT_SURFACE_KINDS,
  type AgentHarness,
  AgentPromptGuidance,
  AgentPromptGuidanceEntry,
  AgentPromptSurfaceKind,
  type AgentToolResultMiddleware,
  type AgentToolResultMiddlewareContext,
  type AgentToolResultMiddlewareEvent,
  type AgentToolResultMiddlewareHarness,
  type AgentToolResultMiddlewareOptions,
  type AgentToolResultMiddlewareResult,
  type AgentToolResultMiddlewareRuntime,
  type AnyAgentTool,
  CONVERSATION_HOOK_NAMES,
  type CliBackendAuthEpochMode,
  type CliBackendExecutionMode,
  type CliBackendNativeToolMode,
  type CliBackendNormalizeConfigContext,
  type CliBackendPlugin,
  type CliBackendPrepareExecutionContext,
  type CliBackendPreparedExecution,
  type CliBackendResolveExecutionArgs,
  type CliBackendResolveExecutionArgsContext,
  type CliBackendSideQuestionToolMode,
  type CliBackendThinkingLevel,
  type CliBundleMcpMode,
  ConversationHookName,
  DEPRECATED_PLUGIN_HOOKS,
  DEPRECATED_PLUGIN_HOOK_NAMES,
  DeprecatedPluginHookName,
  ImageGenerationProviderPlugin,
  type InteractiveRegistrationResult,
  LazyPluginServiceHandle,
  MediaUnderstandingProviderPlugin,
  MigrationApplyResult,
  MigrationDetection,
  MigrationItem,
  MigrationItemAction,
  MigrationItemKind,
  MigrationItemStatus,
  MigrationPlan,
  MigrationProviderContext,
  MigrationProviderPlugin,
  MigrationProviderPreparation,
  MigrationSummary,
  MusicGenerationProviderPlugin,
  type OpenClawAgentToolResult,
  OpenClawGatewayDiscoveryAdvertiseContext,
  OpenClawGatewayDiscoveryService,
  type OpenClawPluginActiveModelContext,
  OpenClawPluginAgentApi,
  OpenClawPluginAgentEventsApi,
  OpenClawPluginApi,
  OpenClawPluginChannelRegistration,
  OpenClawPluginCliCommandDescriptor,
  OpenClawPluginCliContext,
  OpenClawPluginCliRegistrar,
  OpenClawPluginCommandDefinition,
  OpenClawPluginConfigSchema,
  OpenClawPluginDefinition,
  OpenClawPluginGatewayMethod,
  OpenClawPluginGatewayRuntimeScopeSurface,
  type OpenClawPluginHookOptions,
  OpenClawPluginHostedMediaResolver,
  OpenClawPluginHttpRouteAuth,
  OpenClawPluginHttpRouteHandler,
  OpenClawPluginHttpRouteMatch,
  OpenClawPluginHttpRouteParams,
  OpenClawPluginHttpRouteUpgradeHandler,
  OpenClawPluginLifecycleApi,
  OpenClawPluginModule,
  OpenClawPluginNodeCliFeatureOptions,
  type OpenClawPluginNodeHostCommand,
  type OpenClawPluginNodeHostCommandAvailabilityContext,
  type OpenClawPluginNodeHostCommandIo,
  OpenClawPluginNodeInvokeApprovalDecision,
  OpenClawPluginNodeInvokePolicy,
  OpenClawPluginNodeInvokePolicyApprovalRuntime,
  OpenClawPluginNodeInvokePolicyContext,
  OpenClawPluginNodeInvokePolicyResult,
  OpenClawPluginNodeInvokeTransportResult,
  OpenClawPluginReloadRegistration,
  OpenClawPluginRunContextApi,
  OpenClawPluginSecurityAuditCollector,
  OpenClawPluginSecurityAuditContext,
  OpenClawPluginService,
  OpenClawPluginServiceContext,
  OpenClawPluginSessionApi,
  OpenClawPluginSessionControlsApi,
  OpenClawPluginSessionStateApi,
  OpenClawPluginSessionWorkflowApi,
  type OpenClawPluginToolContext,
  type OpenClawPluginToolFactory,
  type OpenClawPluginToolOptions,
  PLUGIN_HOOK_NAMES,
  PLUGIN_PROMPT_MUTATION_RESULT_FIELDS,
  PROMPT_INJECTION_HOOK_NAMES,
  type PluginAgentEventEmitParams,
  type PluginAgentEventEmitResult,
  type PluginAgentEventSubscriptionRegistration,
  type PluginAgentTurnPrepareEvent,
  type PluginAgentTurnPrepareResult,
  type PluginApprovalResolution,
  PluginApprovalResolutions,
  type PluginBundleFormat,
  PluginCommandContext,
  PluginCommandDiagnosticsSession,
  PluginCommandHandler,
  PluginCommandResult,
  PluginConfigMigration,
  type PluginConfigUiHint,
  PluginConfigValidation,
  type PluginControlUiDescriptor,
  type PluginConversationBinding,
  type PluginConversationBindingRequestParams,
  type PluginConversationBindingRequestResult,
  type PluginConversationBindingResolutionDecision,
  type PluginConversationBindingResolvedEvent,
  type PluginDiagnostic,
  PluginEmbeddingProvider,
  type PluginFormat,
  type PluginHeartbeatPromptContributionEvent,
  type PluginHeartbeatPromptContributionResult,
  PluginHookAfterCompactionEvent,
  PluginHookAfterToolCallEvent,
  PluginHookAgentContext,
  PluginHookAgentEndEvent,
  PluginHookBeforeAgentFinalizeEvent,
  PluginHookBeforeAgentFinalizeResult,
  PluginHookBeforeAgentReplyEvent,
  PluginHookBeforeAgentReplyResult,
  PluginHookBeforeAgentRunEvent,
  PluginHookBeforeAgentRunResult,
  type PluginHookBeforeAgentStartEvent,
  type PluginHookBeforeAgentStartOverrideResult,
  type PluginHookBeforeAgentStartResult,
  PluginHookBeforeCompactionEvent,
  PluginHookBeforeDispatchContext,
  PluginHookBeforeDispatchEvent,
  PluginHookBeforeDispatchResult,
  PluginHookBeforeInstallBuiltinScan,
  PluginHookBeforeInstallContext,
  PluginHookBeforeInstallEvent,
  PluginHookBeforeInstallPlugin,
  PluginHookBeforeInstallRequest,
  PluginHookBeforeInstallResult,
  PluginHookBeforeInstallSkill,
  PluginHookBeforeInstallSkillInstallSpec,
  PluginHookBeforeMessageWriteEvent,
  PluginHookBeforeMessageWriteResult,
  type PluginHookBeforeModelResolveAttachment,
  type PluginHookBeforeModelResolveEvent,
  type PluginHookBeforeModelResolveResult,
  type PluginHookBeforePromptBuildEvent,
  type PluginHookBeforePromptBuildResult,
  PluginHookBeforeResetEvent,
  PluginHookBeforeToolCallEvent,
  type PluginHookBeforeToolCallResult,
  type PluginHookChannelChatContext,
  type PluginHookChannelContext,
  type PluginHookChannelSenderContext,
  PluginHookContextWindowSource,
  PluginHookCronChangedEvent,
  PluginHookCronReconciledContext,
  PluginHookCronReconciledEvent,
  PluginHookDeprecation,
  PluginHookGatewayContext,
  PluginHookGatewayCronCreateInput,
  PluginHookGatewayCronDeliveryStatus,
  PluginHookGatewayCronJob,
  PluginHookGatewayCronJobState,
  PluginHookGatewayCronRemoveResult,
  PluginHookGatewayCronRunStatus,
  PluginHookGatewayCronService,
  PluginHookGatewayCronUpdateInput,
  PluginHookGatewayStartEvent,
  PluginHookGatewayStopEvent,
  PluginHookHandlerMap,
  type PluginHookInboundClaimContext,
  type PluginHookInboundClaimEvent,
  PluginHookInboundClaimResult,
  PluginHookLlmInputEvent,
  PluginHookLlmOutputEvent,
  type PluginHookMessageContext,
  type PluginHookMessageReceivedEvent,
  type PluginHookMessageSendingEvent,
  type PluginHookMessageSendingResult,
  type PluginHookMessageSentEvent,
  PluginHookModelCallBaseEvent,
  PluginHookModelCallEndedEvent,
  PluginHookModelCallStartedEvent,
  PluginHookName,
  PluginHookRegistration,
  PluginHookReplyDispatchContext,
  PluginHookReplyDispatchEvent,
  PluginHookReplyDispatchResult,
  PluginHookReplyPayload,
  PluginHookReplyPayloadSendingContext,
  PluginHookReplyPayloadSendingEvent,
  PluginHookReplyPayloadSendingResult,
  PluginHookReplyUsageState,
  PluginHookResolveExecEnvContext,
  PluginHookResolveExecEnvEvent,
  PluginHookSessionContext,
  PluginHookSessionEndEvent,
  PluginHookSessionEndReason,
  PluginHookSessionStartEvent,
  PluginHookSubagentContext,
  PluginHookSubagentDeliveryTargetEvent,
  PluginHookSubagentDeliveryTargetResult,
  PluginHookSubagentEndedEvent,
  PluginHookSubagentSpawnedEvent,
  PluginHookSubagentSpawningEvent,
  PluginHookSubagentSpawningResult,
  PluginHookSubagentTargetKind,
  PluginHookToolContext,
  PluginHookToolInputKind,
  PluginHookToolKind,
  PluginHookToolResultPersistContext,
  PluginHookToolResultPersistEvent,
  PluginHookToolResultPersistResult,
  PluginHttpRouteHandler,
  PluginInstallFinding,
  PluginInstallRequestKind,
  PluginInstallSourcePathKind,
  PluginInstallTargetType,
  PluginInteractiveHandlerRegistration,
  PluginInteractiveHandlerResult,
  PluginInteractiveMatch,
  PluginInteractiveRegistration,
  type PluginJsonValue,
  type PluginKind,
  type PluginLogger,
  type PluginNextTurnInjection,
  type PluginNextTurnInjectionEnqueueResult,
  type PluginNextTurnInjectionRecord,
  type PluginOrigin,
  PluginRealtimeTranscriptionProviderEntry,
  PluginRealtimeVoiceProviderEntry,
  PluginRegistrationMode,
  type PluginRunContextGetParams,
  type PluginRunContextPatch,
  type PluginRuntime,
  type PluginRuntimeLifecycleRegistration,
  type PluginSessionActionContext,
  type PluginSessionActionRegistration,
  type PluginSessionActionResult,
  type PluginSessionAttachmentParams,
  type PluginSessionAttachmentResult,
  type PluginSessionExtensionProjection,
  type PluginSessionExtensionRegistration,
  type PluginSessionSchedulerJobHandle,
  type PluginSessionSchedulerJobRegistration,
  type PluginSessionTurnScheduleParams,
  type PluginSessionTurnUnscheduleByTagParams,
  type PluginSessionTurnUnscheduleByTagResult,
  PluginSetupAutoEnableContext,
  PluginSetupAutoEnableProbe,
  PluginSpeechProviderEntry,
  type PluginTextReplacement,
  PluginTextTransformRegistration,
  type PluginTextTransforms,
  type PluginToolMetadataRegistration,
  PluginTranscriptsSourceProviderEntry,
  type PluginTrustedToolPolicyRegistration,
  type PluginWebFetchProviderEntry,
  type PluginWebSearchProviderEntry,
  PromptInjectionHookName,
  type ProviderApplyConfigDefaultsContext,
  ProviderAugmentModelCatalogContext,
  ProviderAuthContext,
  ProviderAuthDoctorHintContext,
  ProviderAuthKind,
  ProviderAuthMethod,
  ProviderAuthMethodNonInteractiveContext,
  type ProviderAuthOptionBag,
  ProviderAuthResult,
  ProviderBuildMissingAuthMessageContext,
  ProviderBuildUnknownModelHintContext,
  ProviderBuiltInModelSuppressionContext,
  ProviderBuiltInModelSuppressionResult,
  ProviderCacheTtlEligibilityContext,
  ProviderCapabilities,
  ProviderCatalogContext,
  ProviderCatalogOrder,
  ProviderCatalogResult,
  ProviderCreateEmbeddingProviderContext,
  ProviderCreateStreamFnContext,
  type ProviderDefaultThinkingPolicyContext,
  ProviderDeferSyntheticProfileAuthContext,
  ProviderDiscoveryContext,
  ProviderDiscoveryOrder,
  ProviderDiscoveryResult,
  type ProviderExternalAuthProfile,
  type ProviderExternalOAuthProfile,
  ProviderExtraParamsForTransportContext,
  ProviderExtraParamsForTransportResult,
  ProviderFailoverErrorContext,
  ProviderFetchUsageSnapshotContext,
  ProviderFollowupFallbackRouteContext,
  ProviderFollowupFallbackRouteResult,
  ProviderModelSelectedContext,
  ProviderModernModelPolicyContext,
  ProviderNonInteractiveApiKeyCredentialParams,
  ProviderNonInteractiveApiKeyResult,
  type ProviderNormalizeConfigContext,
  ProviderNormalizeModelIdContext,
  ProviderNormalizeResolvedModelContext,
  ProviderNormalizeToolSchemasContext,
  ProviderNormalizeTransportContext,
  ProviderOAuthProfileIdRepair,
  ProviderPlugin,
  ProviderPluginCatalog,
  ProviderPluginDiscovery,
  ProviderPluginWizard,
  ProviderPluginWizardModelPicker,
  ProviderPluginWizardSetup,
  ProviderPreferRuntimeResolvedModelContext,
  ProviderPrepareDynamicModelContext,
  ProviderPrepareExtraParamsContext,
  ProviderPrepareRuntimeAuthContext,
  ProviderPreparedRuntimeAuth,
  ProviderReasoningOutputMode,
  ProviderReasoningOutputModeContext,
  ProviderReplayPolicy,
  ProviderReplayPolicyContext,
  ProviderReplaySanitizeMode,
  ProviderReplaySessionEntry,
  ProviderReplaySessionState,
  ProviderReplayToolCallIdMode,
  ProviderResolveAuthProfileIdContext,
  type ProviderResolveConfigApiKeyContext,
  ProviderResolveDynamicModelContext,
  type ProviderResolveExternalAuthProfilesContext,
  type ProviderResolveExternalOAuthProfilesContext,
  ProviderResolveNonInteractiveApiKeyParams,
  ProviderResolvePromptOverlayContext,
  type ProviderResolveSyntheticAuthContext,
  ProviderResolveTransportTurnStateContext,
  ProviderResolveUsageAuthContext,
  ProviderResolveWebSocketSessionPolicyContext,
  ProviderResolvedUsageAuth,
  type ProviderRuntimeModel,
  ProviderRuntimeProviderConfig,
  ProviderSanitizeReplayHistoryContext,
  type ProviderSyntheticAuthResult,
  ProviderSystemPromptContributionContext,
  type ProviderThinkingPolicyContext,
  type ProviderThinkingProfile,
  ProviderToolSchemaDiagnostic,
  ProviderTransformSystemPromptContext,
  ProviderTransportThinkingLevel,
  ProviderTransportTurnState,
  ProviderUsageAuthToken,
  ProviderValidateReplayTurnsContext,
  ProviderWebSocketSessionPolicy,
  ProviderWrapStreamFnContext,
  RealtimeTranscriptionProviderPlugin,
  RealtimeVoiceProviderPlugin,
  type RuntimeLogger,
  SpeechProviderPlugin,
  TranscriptSourceProvider,
  UnifiedModelCatalogProviderContext,
  UnifiedModelCatalogProviderPlugin,
  VideoGenerationProviderPlugin,
  type WebFetchCredentialResolutionSource,
  type WebFetchProviderContext,
  type WebFetchProviderId,
  type WebFetchProviderPlugin,
  type WebFetchProviderToolDefinition,
  type WebFetchRuntimeMetadataContext,
  type WebSearchCredentialResolutionSource,
  type WebSearchProviderContext,
  type WebSearchProviderId,
  type WebSearchProviderPlugin,
  type WebSearchProviderSetupContext,
  type WebSearchProviderToolDefinition,
  type WebSearchProviderToolExecutionContext,
  type WebSearchRuntimeMetadataContext,
  WorkerLease,
  WorkerLeaseStatus,
  WorkerProfile,
  WorkerProvider,
  WorkerProviderError,
  WorkerSshEndpoint,
  WorkerSshIdentity,
  WorkerSshIdentityRequest,
  testing as __testing,
  testing,
  clearPluginCommands,
  clearPluginCommandsForPlugin,
  clearPluginInteractiveHandlers,
  clearPluginInteractiveHandlersForPlugin,
  createInteractiveConversationBindingHelpers,
  defaultLoadOverrideModule,
  dispatchPluginInteractiveHandler,
  executePluginCommand,
  getGlobalHookRunner,
  getGlobalPluginRegistry,
  getPluginCommandSpecs,
  getPluginRuntimeGatewayRequestScope,
  hasGlobalHooks,
  initializeGlobalHookRunner,
  isConversationHookName,
  isDeprecatedPluginHookName,
  isPluginHookName,
  isPromptInjectionHookName,
  listPluginCommands,
  listProviderPluginCommandSpecs,
  listRegisteredPluginAgentPromptGuidance,
  matchPluginCommand,
  normalizePluginHttpPath,
  registerPluginCommand,
  registerPluginHttpRoute,
  registerPluginInteractiveHandler,
  resetGlobalHookRunner,
  runGlobalGatewayStopSafely,
  startLazyPluginServiceModule,
  stripPromptMutationFieldsFromLegacyHookResult,
  validateCommandName,
  validatePluginCommandDefinition,
  withPluginHttpRouteRegistry,
};
