import {
  a as PluginConversationBindingResolvedEvent,
  n as PluginConversationBindingRequestParams,
  r as PluginConversationBindingRequestResult,
  t as PluginConversationBinding,
} from "../conversation-binding.types-FpB9wxq5.js";
import {
  Xt as PluginHookInboundClaimContext,
  Z as PluginHookInboundClaimResult,
  Zt as PluginHookInboundClaimEvent,
} from "../hook-types-BPL4xByC.js";
import {
  h as UnifiedModelCatalogSource,
  m as UnifiedModelCatalogKind,
  p as UnifiedModelCatalogEntry,
} from "../manifest-registry-CHEq75Tu.js";
import {
  $ as PluginSessionActionResult,
  $t as ProviderThinkingPolicyContext,
  A as OpenClawPluginServiceContext,
  At as ProviderModernModelPolicyContext,
  B as PluginControlUiDescriptor,
  Bt as ProviderReasoningOutputMode,
  C as OpenClawPluginNodeInvokePolicy,
  Ct as ProviderCatalogContext,
  D as OpenClawPluginSecurityAuditCollector,
  Dt as ProviderDiscoveryContext,
  E as OpenClawPluginReloadRegistration,
  Et as ProviderDeferSyntheticProfileAuthContext,
  F as PluginAgentEventSubscriptionRegistration,
  Ft as ProviderNormalizeTransportContext,
  G as PluginNextTurnInjection,
  Gt as ProviderReplaySessionState,
  H as PluginHeartbeatPromptContributionResult,
  Ht as ProviderReplayPolicy,
  I as PluginAgentTurnPrepareEvent,
  It as ProviderPrepareDynamicModelContext,
  J as PluginRunContextGetParams,
  Jt as ProviderResolveTransportTurnStateContext,
  K as PluginNextTurnInjectionEnqueueResult,
  Kt as ProviderResolveConfigApiKeyContext,
  L as PluginAgentTurnPrepareResult,
  Lt as ProviderPrepareExtraParamsContext,
  M as OpenClawPluginToolFactory,
  Mt as ProviderNormalizeModelIdContext,
  N as PluginAgentEventEmitParams,
  Nt as ProviderNormalizeResolvedModelContext,
  O as OpenClawPluginSecurityAuditContext,
  Ot as ProviderFailoverErrorContext,
  P as PluginAgentEventEmitResult,
  Pt as ProviderNormalizeToolSchemasContext,
  Q as PluginSessionActionRegistration,
  Qt as ProviderSanitizeReplayHistoryContext,
  R as PluginCommandContext,
  Rt as ProviderPrepareRuntimeAuthContext,
  S as OpenClawPluginNodeHostCommandAvailabilityContext,
  St as ProviderCacheTtlEligibilityContext,
  T as OpenClawPluginNodeInvokePolicyResult,
  Tt as ProviderDefaultThinkingPolicyContext,
  U as PluginJsonValue,
  Ut as ProviderReplayPolicyContext,
  V as PluginHeartbeatPromptContributionEvent,
  Vt as ProviderReasoningOutputModeContext,
  W as PluginLogger,
  Wt as ProviderReplaySessionEntry,
  X as PluginRuntimeLifecycleRegistration,
  Xt as ProviderResolveWebSocketSessionPolicyContext,
  Y as PluginRunContextPatch,
  Yt as ProviderResolveUsageAuthContext,
  Z as PluginSessionActionContext,
  Zt as ProviderResolvedUsageAuth,
  _ as OpenClawPluginCommandDefinition,
  _n as WorkerSshIdentity,
  _t as ProviderAuthResult,
  a as AnyAgentTool,
  an as ProviderWebSocketSessionPolicy,
  at as PluginSessionSchedulerJobRegistration,
  b as OpenClawPluginHttpRouteHandler,
  bt as ProviderBuiltInModelSuppressionContext,
  c as MigrationDetection,
  cn as SpeechProviderPlugin,
  ct as PluginSessionTurnUnscheduleByTagResult,
  d as MigrationProviderContext,
  dn as UnifiedModelCatalogProviderPlugin,
  dt as ProviderApplyConfigDefaultsContext,
  en as ProviderThinkingProfile,
  et as PluginSessionAttachmentParams,
  f as MigrationProviderPlugin,
  fn as WorkerLease,
  ft as ProviderAugmentModelCatalogContext,
  g as OpenClawPluginApi,
  gn as WorkerSshEndpoint,
  gt as ProviderAuthMethodNonInteractiveContext,
  h as OpenClawGatewayDiscoveryService,
  hn as WorkerProvider,
  ht as ProviderAuthMethod,
  i as AgentPromptSurfaceKind,
  in as ProviderValidateReplayTurnsContext,
  it as PluginSessionSchedulerJobHandle,
  j as OpenClawPluginToolContext,
  jt as ProviderNormalizeConfigContext,
  k as OpenClawPluginService,
  kt as ProviderFetchUsageSnapshotContext,
  l as MigrationItem,
  ln as TranscriptSourceProvider,
  lt as PluginToolMetadataRegistration,
  m as OpenClawGatewayDiscoveryAdvertiseContext,
  mn as WorkerProfile,
  mt as ProviderAuthDoctorHintContext,
  n as AgentPromptGuidance,
  nn as ProviderTransportTurnState,
  nt as PluginSessionExtensionProjection,
  o as MediaUnderstandingProviderPlugin,
  on as ProviderWrapStreamFnContext,
  ot as PluginSessionTurnScheduleParams,
  p as MigrationSummary,
  pn as WorkerLeaseStatus,
  pt as ProviderAuthContext,
  q as PluginNextTurnInjectionRecord,
  qt as ProviderResolveDynamicModelContext,
  r as AgentPromptGuidanceEntry,
  rn as ProviderUsageAuthToken,
  rt as PluginSessionExtensionRegistration,
  s as MigrationApplyResult,
  sn as RealtimeTranscriptionProviderPlugin,
  st as PluginSessionTurnUnscheduleByTagParams,
  t as AgentHarness,
  tn as ProviderToolSchemaDiagnostic,
  tt as PluginSessionAttachmentResult,
  u as MigrationPlan,
  un as UnifiedModelCatalogProviderContext,
  ut as PluginTrustedToolPolicyRegistration,
  v as OpenClawPluginConfigSchema,
  vn as WorkerSshIdentityRequest,
  vt as ProviderBuildMissingAuthMessageContext,
  w as OpenClawPluginNodeInvokePolicyContext,
  wt as ProviderCatalogResult,
  x as OpenClawPluginNodeHostCommand,
  xt as ProviderBuiltInModelSuppressionResult,
  y as OpenClawPluginDefinition,
  yn as definePluginEntry,
  yt as ProviderBuildUnknownModelHintContext,
  z as PluginCommandResult,
  zt as ProviderPreparedRuntimeAuth,
} from "../plugin-entry-DPCR66aO.js";
import {
  Js as buildPluginConfigSchema,
  Ys as emptyPluginConfigSchema,
  er as WorkerProviderError,
  nd as ProviderRuntimeModel,
  qs as buildJsonPluginConfigSchema,
} from "../types-Ga3mNO_F.js";
import { i as OpenClawConfig } from "../types.openclaw-DDo8sH3F.js";
export {
  AgentHarness,
  AgentPromptGuidance,
  AgentPromptGuidanceEntry,
  AgentPromptSurfaceKind,
  AnyAgentTool,
  MediaUnderstandingProviderPlugin,
  MigrationApplyResult,
  MigrationDetection,
  MigrationItem,
  MigrationPlan,
  MigrationProviderContext,
  MigrationProviderPlugin,
  MigrationSummary,
  type OpenClawConfig,
  OpenClawGatewayDiscoveryAdvertiseContext,
  OpenClawGatewayDiscoveryService,
  OpenClawPluginApi,
  OpenClawPluginCommandDefinition,
  OpenClawPluginConfigSchema,
  OpenClawPluginDefinition,
  OpenClawPluginHttpRouteHandler,
  OpenClawPluginNodeHostCommand,
  OpenClawPluginNodeHostCommandAvailabilityContext,
  OpenClawPluginNodeInvokePolicy,
  OpenClawPluginNodeInvokePolicyContext,
  OpenClawPluginNodeInvokePolicyResult,
  OpenClawPluginReloadRegistration,
  OpenClawPluginSecurityAuditCollector,
  OpenClawPluginSecurityAuditContext,
  OpenClawPluginService,
  OpenClawPluginServiceContext,
  OpenClawPluginToolContext,
  OpenClawPluginToolFactory,
  PluginAgentEventEmitParams,
  PluginAgentEventEmitResult,
  PluginAgentEventSubscriptionRegistration,
  PluginAgentTurnPrepareEvent,
  PluginAgentTurnPrepareResult,
  PluginCommandContext,
  PluginCommandResult,
  PluginControlUiDescriptor,
  type PluginConversationBinding,
  type PluginConversationBindingRequestParams,
  type PluginConversationBindingRequestResult,
  type PluginConversationBindingResolvedEvent,
  PluginHeartbeatPromptContributionEvent,
  PluginHeartbeatPromptContributionResult,
  type PluginHookInboundClaimContext,
  type PluginHookInboundClaimEvent,
  type PluginHookInboundClaimResult,
  PluginJsonValue,
  PluginLogger,
  PluginNextTurnInjection,
  PluginNextTurnInjectionEnqueueResult,
  PluginNextTurnInjectionRecord,
  PluginRunContextGetParams,
  PluginRunContextPatch,
  PluginRuntimeLifecycleRegistration,
  PluginSessionActionContext,
  PluginSessionActionRegistration,
  PluginSessionActionResult,
  PluginSessionAttachmentParams,
  PluginSessionAttachmentResult,
  PluginSessionExtensionProjection,
  PluginSessionExtensionRegistration,
  PluginSessionSchedulerJobHandle,
  PluginSessionSchedulerJobRegistration,
  PluginSessionTurnScheduleParams,
  PluginSessionTurnUnscheduleByTagParams,
  PluginSessionTurnUnscheduleByTagResult,
  PluginToolMetadataRegistration,
  PluginTrustedToolPolicyRegistration,
  ProviderApplyConfigDefaultsContext,
  ProviderAugmentModelCatalogContext,
  ProviderAuthContext,
  ProviderAuthDoctorHintContext,
  ProviderAuthMethod,
  ProviderAuthMethodNonInteractiveContext,
  ProviderAuthResult,
  ProviderBuildMissingAuthMessageContext,
  ProviderBuildUnknownModelHintContext,
  ProviderBuiltInModelSuppressionContext,
  ProviderBuiltInModelSuppressionResult,
  ProviderCacheTtlEligibilityContext,
  ProviderCatalogContext,
  ProviderCatalogResult,
  ProviderDefaultThinkingPolicyContext,
  ProviderDeferSyntheticProfileAuthContext,
  ProviderDiscoveryContext,
  ProviderFailoverErrorContext,
  ProviderFetchUsageSnapshotContext,
  ProviderModernModelPolicyContext,
  ProviderNormalizeConfigContext,
  ProviderNormalizeModelIdContext,
  ProviderNormalizeResolvedModelContext,
  ProviderNormalizeToolSchemasContext,
  ProviderNormalizeTransportContext,
  ProviderPrepareDynamicModelContext,
  ProviderPrepareExtraParamsContext,
  ProviderPrepareRuntimeAuthContext,
  ProviderPreparedRuntimeAuth,
  ProviderReasoningOutputMode,
  ProviderReasoningOutputModeContext,
  ProviderReplayPolicy,
  ProviderReplayPolicyContext,
  ProviderReplaySessionEntry,
  ProviderReplaySessionState,
  ProviderResolveConfigApiKeyContext,
  ProviderResolveDynamicModelContext,
  ProviderResolveTransportTurnStateContext,
  ProviderResolveUsageAuthContext,
  ProviderResolveWebSocketSessionPolicyContext,
  ProviderResolvedUsageAuth,
  type ProviderRuntimeModel,
  ProviderSanitizeReplayHistoryContext,
  ProviderThinkingPolicyContext,
  ProviderThinkingProfile,
  ProviderToolSchemaDiagnostic,
  ProviderTransportTurnState,
  ProviderUsageAuthToken,
  ProviderValidateReplayTurnsContext,
  ProviderWebSocketSessionPolicy,
  ProviderWrapStreamFnContext,
  RealtimeTranscriptionProviderPlugin,
  SpeechProviderPlugin,
  TranscriptSourceProvider,
  type UnifiedModelCatalogEntry,
  type UnifiedModelCatalogKind,
  UnifiedModelCatalogProviderContext,
  UnifiedModelCatalogProviderPlugin,
  type UnifiedModelCatalogSource,
  WorkerLease,
  WorkerLeaseStatus,
  WorkerProfile,
  WorkerProvider,
  WorkerProviderError,
  WorkerSshEndpoint,
  WorkerSshIdentity,
  WorkerSshIdentityRequest,
  buildJsonPluginConfigSchema,
  buildPluginConfigSchema,
  definePluginEntry,
  emptyPluginConfigSchema,
};
