import { t as DEFAULT_CONTEXT_TOKENS } from "../defaults-DZhrVvBP.js";
import {
  a as resolveClaudeMythos5ModelIdentity,
  c as supportsClaudeAdaptiveThinking,
  i as resolveClaudeModelIdentity,
  l as supportsClaudeNativeMaxEffort,
  n as requiresClaudeMandatoryAdaptiveThinking,
  o as resolveClaudeNativeThinkingLevelMap,
  r as resolveClaudeFable5ModelIdentity,
  s as resolveClaudeSonnet5ModelIdentity,
  t as requiresClaudeDefaultSampling,
  u as supportsClaudeNativeXhighEffort,
} from "../index-oDFIyDjc.js";
import {
  h as UnifiedModelCatalogSource,
  m as UnifiedModelCatalogKind,
  p as UnifiedModelCatalogEntry,
} from "../manifest-registry-CHEq75Tu.js";
import {
  n as resolveMoonshotThinkingType,
  t as createMoonshotThinkingWrapper,
} from "../moonshot-thinking-Ci6Hu4xD.js";
import {
  A as resolveGpt5PromptOverlayMode,
  B as sanitizeGoogleGeminiReplayHistory,
  C as GPT5_FRIENDLY_CHAT_PROMPT_OVERLAY,
  D as isGpt5ModelId,
  E as Gpt5PromptOverlayMode,
  F as buildNativeAnthropicReplayPolicyForModel,
  I as buildOpenAICompatibleReplayPolicy,
  L as buildPassthroughGeminiSanitizingReplayPolicy,
  M as buildAnthropicReplayPolicyForModel,
  N as buildGoogleGeminiReplayPolicy,
  O as normalizeGpt5PromptOverlayMode,
  P as buildHybridAnthropicOrOpenAIReplayPolicy,
  R as buildStrictAnthropicReplayPolicy,
  S as GPT5_BEHAVIOR_CONTRACT,
  T as GPT5_HEARTBEAT_PROMPT_OVERLAY,
  _ as hasNativeWebSearchTool,
  a as ProviderReplayFamily,
  b as resolveToolCallArgumentsEncoding,
  c as modelCostsEqual,
  d as normalizeProviderId,
  f as isClaudeAdaptiveThinkingDefaultModelId,
  g as applyModelCompatPatch,
  h as matchesExactOrPrefix,
  i as PASSTHROUGH_GEMINI_REPLAY_HOOKS,
  j as resolveGpt5SystemPromptContribution,
  k as renderGpt5PromptOverlay,
  l as normalizeAntigravityPreviewModelId,
  m as cloneFirstTemplateModel,
  n as NATIVE_ANTHROPIC_REPLAY_HOOKS,
  o as buildProviderReplayFamilyHooks,
  p as resolveClaudeThinkingProfile,
  r as OPENAI_COMPATIBLE_REPLAY_HOOKS,
  s as isProxyReasoningUnsupportedModelHint,
  t as ANTHROPIC_BY_MODEL_REPLAY_HOOKS,
  u as normalizeGooglePreviewModelId,
  v as hasToolSchemaProfile,
  w as GPT5_FRIENDLY_PROMPT_OVERLAY,
  x as resolveUnsupportedToolSchemaKeywords,
  y as normalizeModelCompat,
  z as resolveTaggedReasoningOutputMode,
} from "../provider-model-shared-BImyLrKQ.js";
import {
  S as resolveProviderEndpoint,
  m as ProviderEndpointResolution,
  p as ProviderEndpointClass,
} from "../provider-request-config-CKlP6x21.js";
import {
  Jn as UnifiedModelCatalogProviderPlugin,
  an as ProviderPlugin,
  qn as UnifiedModelCatalogProviderContext,
} from "../types-Ga3mNO_F.js";
import {
  a as ModelApi,
  m as ModelProviderDeclarationConfig,
  o as ModelCompatConfig,
  s as ModelDefinitionConfig,
  t as BedrockDiscoveryConfig,
} from "../types.models-BqJSiNyu.js";
export {
  ANTHROPIC_BY_MODEL_REPLAY_HOOKS,
  type BedrockDiscoveryConfig,
  DEFAULT_CONTEXT_TOKENS,
  GPT5_BEHAVIOR_CONTRACT,
  GPT5_FRIENDLY_CHAT_PROMPT_OVERLAY,
  GPT5_FRIENDLY_PROMPT_OVERLAY,
  GPT5_HEARTBEAT_PROMPT_OVERLAY,
  type Gpt5PromptOverlayMode,
  type ModelApi,
  type ModelCompatConfig,
  type ModelDefinitionConfig,
  type ModelProviderDeclarationConfig as ModelProviderConfig,
  NATIVE_ANTHROPIC_REPLAY_HOOKS,
  OPENAI_COMPATIBLE_REPLAY_HOOKS,
  PASSTHROUGH_GEMINI_REPLAY_HOOKS,
  type ProviderEndpointClass,
  type ProviderEndpointResolution,
  type ProviderPlugin,
  ProviderReplayFamily,
  type UnifiedModelCatalogEntry,
  type UnifiedModelCatalogKind,
  type UnifiedModelCatalogProviderContext,
  type UnifiedModelCatalogProviderPlugin,
  type UnifiedModelCatalogSource,
  applyModelCompatPatch,
  buildAnthropicReplayPolicyForModel,
  buildGoogleGeminiReplayPolicy,
  buildHybridAnthropicOrOpenAIReplayPolicy,
  buildNativeAnthropicReplayPolicyForModel,
  buildOpenAICompatibleReplayPolicy,
  buildPassthroughGeminiSanitizingReplayPolicy,
  buildProviderReplayFamilyHooks,
  buildStrictAnthropicReplayPolicy,
  cloneFirstTemplateModel,
  createMoonshotThinkingWrapper,
  hasNativeWebSearchTool,
  hasToolSchemaProfile,
  isClaudeAdaptiveThinkingDefaultModelId,
  isGpt5ModelId,
  isProxyReasoningUnsupportedModelHint,
  matchesExactOrPrefix,
  modelCostsEqual,
  normalizeAntigravityPreviewModelId,
  normalizeGooglePreviewModelId,
  normalizeGpt5PromptOverlayMode,
  normalizeModelCompat,
  normalizeProviderId,
  renderGpt5PromptOverlay,
  requiresClaudeDefaultSampling,
  requiresClaudeMandatoryAdaptiveThinking,
  resolveClaudeFable5ModelIdentity,
  resolveClaudeModelIdentity,
  resolveClaudeMythos5ModelIdentity,
  resolveClaudeNativeThinkingLevelMap,
  resolveClaudeSonnet5ModelIdentity,
  resolveClaudeThinkingProfile,
  resolveGpt5PromptOverlayMode,
  resolveGpt5SystemPromptContribution,
  resolveMoonshotThinkingType,
  resolveProviderEndpoint,
  resolveTaggedReasoningOutputMode,
  resolveToolCallArgumentsEncoding,
  resolveUnsupportedToolSchemaKeywords,
  sanitizeGoogleGeminiReplayHistory,
  supportsClaudeAdaptiveThinking,
  supportsClaudeNativeMaxEffort,
  supportsClaudeNativeXhighEffort,
};
