import { t as resolveOpenClawAgentDir } from "../agent-dir-compat-ochOeoeD.js";
import {
  F as hasUsableOAuthCredential,
  I as CLAUDE_CLI_PROFILE_ID,
  L as CODEX_CLI_PROFILE_ID,
  N as DEFAULT_OAUTH_REFRESH_MARGIN_MS,
  _ as upsertAuthProfileWithLock,
  f as suggestOAuthProfileIdForLegacyDefault,
  g as upsertAuthProfile,
  m as removeProviderAuthProfilesWithLock,
  y as listProfilesForProvider,
} from "../auth-profiles-BzT-kajT.js";
import {
  n as readClaudeCliCredentialsCached,
  r as readCodexCliCredentialsCached,
} from "../cli-credentials-ktnN0wd_.js";
import { o as resolveRequiredHomeDir } from "../home-dir-4pOw9r_P.js";
import { j as resolveEnvApiKey } from "../model-auth-DQnRyl6R.js";
import {
  d as isNonSecretApiKeyMarker,
  g as resolveNonEnvSecretRefApiKeyMarker,
  i as MINIMAX_OAUTH_MARKER,
  n as CUSTOM_LOCAL_AUTH_MARKER,
  u as isKnownEnvApiKeyMarker,
  v as resolveOAuthApiKeyMarker,
} from "../model-auth-markers-BhPapeFt.js";
import {
  n as normalizeSecretInput,
  t as normalizeOptionalSecretInput,
} from "../normalize-secret-input-DuM-MDGm.js";
import { t as createProviderApiKeyAuthMethod } from "../provider-api-key-auth-m_ndkcmp.js";
import {
  C as resolveOpenAICodexImportProfileName,
  D as CachedCopilotToken,
  E as normalizeApiKeyConfig,
  S as resolveOpenAICodexAuthIdentity,
  T as validateAnthropicSetupToken,
  _ as toFormUrlEncoded,
  a as listUsableProviderAuthProfileIds,
  b as decodeOpenAICodexJwtPayload,
  c as resolveProviderAuthProfileApiKey,
  d as COPILOT_GITHUB_API_VERSION,
  f as COPILOT_INTEGRATION_ID,
  g as generatePkceVerifierChallenge,
  h as generateHexPkceVerifierChallenge,
  i as isProviderAuthProfileConfigured,
  l as COPILOT_EDITOR_PLUGIN_VERSION,
  m as buildCopilotIdeHeaders,
  n as deriveCopilotApiBaseUrlFromToken,
  o as normalizeGithubCopilotDomain,
  p as COPILOT_USER_AGENT,
  r as isProviderApiKeyConfigured,
  s as resolveCopilotApiToken,
  t as DEFAULT_COPILOT_API_BASE_URL,
  u as COPILOT_EDITOR_VERSION,
  v as OpenAICodexAuthIdentity,
  w as buildTokenProfileId,
  x as resolveOpenAICodexAccessTokenExpiry,
  y as buildOpenAICodexCredentialExtra,
} from "../provider-auth-Dpm5W57d.js";
import {
  a as upsertApiKeyProfile,
  i as buildApiKeyCredential,
  n as WriteOAuthCredentialsOptions,
  o as writeOAuthCredentials,
  r as applyAuthProfileConfig,
  t as ApiKeyStorageOptions,
} from "../provider-auth-helpers-CAyn28uR.js";
import {
  a as normalizeSecretInputModeInput,
  c as promptSecretRefForSetup,
  i as normalizeApiKeyInput,
  n as ensureApiKeyFromOptionEnvOrPrompt,
  o as validateApiKeyInput,
  r as formatApiKeyPreview,
  s as resolveSecretInputModeForEnvSelection,
  t as ensureApiKeyFromEnvOrPrompt,
} from "../provider-auth-input-C-NKbqMc.js";
import { t as buildOauthProviderAuthResult } from "../provider-auth-result-B-vOeCns.js";
import {
  i as omitEnvKeysCaseInsensitive,
  r as listKnownProviderAuthEnvVarNames,
} from "../provider-env-vars-D_E_Txif.js";
import { n as resolveDefaultSecretProviderAlias } from "../ref-contract-BmfzmMXw.js";
import {
  n as ensureAuthProfileStore,
  p as updateAuthProfileStoreWithLock,
  r as ensureAuthProfileStoreForLocalUpdate,
} from "../store-TQsl5_Yq.js";
import { j as SecretInputMode } from "../types-Dz3ohwUV.js";
import { c as OAuthCredential, s as AuthProfileStore } from "../types-Dzb4Vh4b.js";
import { Ct as ProviderAuthContext, Ot as ProviderAuthResult } from "../types-Ga3mNO_F.js";
import { i as OpenClawConfig } from "../types.openclaw-DDo8sH3F.js";
import {
  b as coerceSecretRef,
  d as SecretInput,
  x as hasConfiguredSecretInput,
} from "../types.secrets-C15Z_eLX.js";
export {
  type ApiKeyStorageOptions,
  type AuthProfileStore,
  CLAUDE_CLI_PROFILE_ID,
  CODEX_CLI_PROFILE_ID,
  COPILOT_EDITOR_PLUGIN_VERSION,
  COPILOT_EDITOR_VERSION,
  COPILOT_GITHUB_API_VERSION,
  COPILOT_INTEGRATION_ID,
  COPILOT_USER_AGENT,
  CUSTOM_LOCAL_AUTH_MARKER,
  type CachedCopilotToken,
  DEFAULT_COPILOT_API_BASE_URL,
  DEFAULT_OAUTH_REFRESH_MARGIN_MS,
  MINIMAX_OAUTH_MARKER,
  type OAuthCredential,
  type OpenAICodexAuthIdentity,
  type OpenClawConfig,
  type ProviderAuthContext,
  type ProviderAuthResult,
  type SecretInput,
  type SecretInputMode,
  type WriteOAuthCredentialsOptions,
  applyAuthProfileConfig,
  buildApiKeyCredential,
  buildCopilotIdeHeaders,
  buildOauthProviderAuthResult,
  buildOpenAICodexCredentialExtra,
  buildTokenProfileId,
  coerceSecretRef,
  createProviderApiKeyAuthMethod,
  decodeOpenAICodexJwtPayload,
  deriveCopilotApiBaseUrlFromToken,
  ensureApiKeyFromEnvOrPrompt,
  ensureApiKeyFromOptionEnvOrPrompt,
  ensureAuthProfileStore,
  ensureAuthProfileStoreForLocalUpdate,
  formatApiKeyPreview,
  generateHexPkceVerifierChallenge,
  generatePkceVerifierChallenge,
  hasConfiguredSecretInput,
  hasUsableOAuthCredential,
  isKnownEnvApiKeyMarker,
  isNonSecretApiKeyMarker,
  isProviderApiKeyConfigured,
  isProviderAuthProfileConfigured,
  listKnownProviderAuthEnvVarNames,
  listProfilesForProvider,
  listUsableProviderAuthProfileIds,
  normalizeApiKeyConfig,
  normalizeApiKeyInput,
  normalizeGithubCopilotDomain,
  normalizeOptionalSecretInput,
  normalizeSecretInput,
  normalizeSecretInputModeInput,
  omitEnvKeysCaseInsensitive,
  promptSecretRefForSetup,
  readClaudeCliCredentialsCached,
  readCodexCliCredentialsCached,
  removeProviderAuthProfilesWithLock,
  resolveCopilotApiToken,
  resolveDefaultSecretProviderAlias,
  resolveEnvApiKey,
  resolveNonEnvSecretRefApiKeyMarker,
  resolveOAuthApiKeyMarker,
  resolveOpenAICodexAccessTokenExpiry,
  resolveOpenAICodexAuthIdentity,
  resolveOpenAICodexImportProfileName,
  resolveOpenClawAgentDir,
  resolveProviderAuthProfileApiKey,
  resolveRequiredHomeDir,
  resolveSecretInputModeForEnvSelection,
  suggestOAuthProfileIdForLegacyDefault,
  toFormUrlEncoded,
  updateAuthProfileStoreWithLock,
  upsertApiKeyProfile,
  upsertAuthProfile,
  upsertAuthProfileWithLock,
  validateAnthropicSetupToken,
  validateApiKeyInput,
  writeOAuthCredentials,
};
