import {
  n as resolveAccessGroupAllowFromMatches,
  r as resolveAccessGroupAllowFromState,
  t as expandAllowFromWithAccessGroups,
} from "../access-groups-QbJVwfug.js";
import {
  a as parseAccessGroupAllowFromEntry,
  t as ACCESS_GROUP_ALLOW_FROM_PREFIX,
} from "../allow-from-o-cfFFcK.js";
import {
  a as getChannelRecord,
  c as isBaseFieldActiveForChannelSurface,
  l as normalizeSecretStringValue,
  n as collectNestedChannelFieldAssignments,
  o as getChannelSurface,
  r as collectSimpleChannelFieldAssignments,
  s as hasConfiguredSecretInputValue,
  t as collectConditionalChannelFieldAssignments,
  u as resolveChannelAccountSurface,
} from "../channel-secret-basic-runtime-Dhe08HLa.js";
import { t as collectNestedChannelTtsAssignments } from "../channel-secret-tts-runtime-Bs1JA8tE.js";
import {
  n as filterSupplementalContextItems,
  r as shouldIncludeSupplementalContext,
  t as evaluateSupplementalContextVisibility,
} from "../context-visibility-C5CaKMWO.js";
import {
  a as resolveDmGroupAccessWithCommandGate,
  c as resolveOpenDmAllowlistAccess,
  i as resolveDmGroupAccessDecision,
  l as resolvePinnedMainDmOwnerFromAllowlist,
  n as readStoreAllowFromForDmPolicy,
  o as resolveDmGroupAccessWithLists,
  r as resolveDmAllowState,
  s as resolveEffectiveAllowFromLists,
  t as DM_GROUP_ACCESS_REASON,
} from "../dm-policy-shared-d7KFGRtT.js";
import { n as extractErrorCode, r as formatErrorMessage } from "../errors-BoHeli7m.js";
import {
  a as wrapExternalContent,
  i as sanitizeModelSpecialTokens,
  n as detectSuspiciousPatterns,
  o as wrapWebContent,
  r as getHookType,
  t as buildSafeExternalPrompt,
} from "../external-content-rRQGoatE.js";
import {
  n as mapHookExternalContentSource,
  r as resolveHookExternalContentSource,
  t as isExternalHookSession,
} from "../external-content-source-CzLOB3HH.js";
import {
  C as resolveAbsolutePathForRead,
  S as findExistingAncestor,
  _ as resolveLocalPathFromRootsSync,
  b as assertAbsolutePathInput,
  c as withTimeout,
  d as resolveExistingPathsWithinRoot,
  f as resolvePathWithinRoot,
  h as resolveWritablePathWithinRoot,
  m as resolveStrictExistingPathsWithinRoot,
  p as resolvePathsWithinRoot,
  r as writeExternalFileWithinRoot,
  t as ensureAbsoluteDirectory,
  u as pathScope,
  v as pathExists,
  w as resolveAbsolutePathForWrite,
  x as canonicalPathFromExistingAncestor,
  y as pathExistsSync,
} from "../fs-safe-RNq3oO57.js";
import { t as normalizeHostname } from "../hostname-DAZapKzN.js";
import { C as FsSafeError, i as isPathInside, r as isNotFoundPathError } from "../path-DILYn_gk.js";
import { r as ensurePortAvailable } from "../ports-miNUZKci.js";
import {
  n as privateFileStoreSync,
  t as privateFileStore,
} from "../private-file-store-BSksaLX_.js";
import { i as hasProxyEnvConfigured } from "../proxy-env-5nRGQyQD.js";
import { o as isRecord } from "../record-coerce-DHZ4bFlT.js";
import {
  C as testRegexWithBoundedInput,
  S as hasNestedRepetition,
  b as compileSafeRegex,
  c as redactSensitiveText,
  x as compileSafeRegexDetailed,
} from "../redact-CUe6Oey5.js";
import {
  a as resolveRegularFileAppendFlags,
  i as readRegularFileSync,
  n as appendRegularFileSync,
  o as statRegularFile,
  r as readRegularFile,
  s as statRegularFileSync,
  t as appendRegularFile,
} from "../regular-file-CuvhUtZS.js";
import { n as replaceFileAtomic, t as movePathWithCopyFallback } from "../replace-file-CaPU6XwS.js";
import { n as replaceFileAtomicSync } from "../replace-file-DfwQ8_Mi.js";
import {
  a as isChannelAccountEffectivelyEnabled,
  c as pushInactiveSurfaceWarning,
  i as hasOwnProperty,
  l as pushWarning,
  n as collectSecretInputAssignment,
  o as isEnabledFlag,
  r as createResolverContext,
  s as pushAssignment,
  t as applyResolvedAssignments,
} from "../runtime-shared-CE1Ki5Mc.js";
import { t as safeEqualSecret } from "../secret-equal-DRsL8lKD.js";
import { i as generateSecureToken } from "../secure-random-Ds4AFLgz.js";
import { a as root, r as openLocalFileSafely } from "../secure-temp-dir-DMUMnweR.js";
import {
  n as writeFileFromPathWithinRoot,
  r as buildUntrustedChannelMetadata,
  t as openFileWithinRoot,
} from "../security-runtime-CraX8Pqe.js";
import {
  a as parseDotPath,
  c as toDotPath,
  i as normalizePositiveTimerMs,
  l as writeJsonFileSecure,
  n as isNonEmptyString,
  o as parseEnvValue,
  r as normalizePositiveInt,
  s as readTextFileIfExists,
  t as ensureDirForFile,
  u as writeTextFileAtomic,
} from "../shared-CrrsbqCi.js";
import {
  n as writeViaSiblingTempPath,
  r as sanitizeUntrustedFileName,
  t as writeSiblingTempFile,
} from "../sibling-temp-B46XkYIp.js";
import {
  _ as resolvePinnedHostnameWithPolicy,
  c as isBlockedHostnameOrIp,
  d as isPrivateNetworkAllowedByPolicy,
  p as matchesHostnameAllowlist,
  t as SsrFBlockedError,
} from "../ssrf-keFRGQLq.js";
import {
  n as assertNoSymlinkParentsSync,
  t as assertNoSymlinkParents,
} from "../symlink-parents-D3bl9xr3.js";
import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-uPgNO8da.js";
export {
  ACCESS_GROUP_ALLOW_FROM_PREFIX,
  DM_GROUP_ACCESS_REASON,
  FsSafeError,
  FsSafeError as SafeOpenError,
  SsrFBlockedError,
  appendRegularFile,
  appendRegularFileSync,
  applyResolvedAssignments,
  assertAbsolutePathInput,
  assertNoSymlinkParents,
  assertNoSymlinkParentsSync,
  buildSafeExternalPrompt,
  buildUntrustedChannelMetadata,
  canonicalPathFromExistingAncestor,
  collectConditionalChannelFieldAssignments,
  collectNestedChannelFieldAssignments,
  collectNestedChannelTtsAssignments,
  collectSecretInputAssignment,
  collectSimpleChannelFieldAssignments,
  compileSafeRegex,
  compileSafeRegexDetailed,
  createResolverContext,
  detectSuspiciousPatterns,
  ensureAbsoluteDirectory,
  ensureDirForFile,
  ensurePortAvailable,
  evaluateSupplementalContextVisibility,
  expandAllowFromWithAccessGroups,
  extractErrorCode,
  filterSupplementalContextItems,
  findExistingAncestor,
  formatErrorMessage,
  generateSecureToken,
  getChannelRecord,
  getChannelSurface,
  getHookType,
  hasConfiguredSecretInputValue,
  hasNestedRepetition,
  hasOwnProperty,
  hasProxyEnvConfigured,
  isBaseFieldActiveForChannelSurface,
  isBlockedHostnameOrIp,
  isChannelAccountEffectivelyEnabled,
  isEnabledFlag,
  isExternalHookSession,
  isNonEmptyString,
  isNotFoundPathError,
  isPathInside,
  isPrivateNetworkAllowedByPolicy,
  isRecord,
  mapHookExternalContentSource,
  matchesHostnameAllowlist,
  movePathWithCopyFallback,
  normalizeHostname,
  normalizePositiveInt,
  normalizePositiveTimerMs,
  normalizeSecretStringValue,
  openFileWithinRoot,
  openLocalFileSafely,
  parseAccessGroupAllowFromEntry,
  parseDotPath,
  parseEnvValue,
  pathExists,
  pathExistsSync,
  pathScope,
  privateFileStore,
  privateFileStoreSync,
  pushAssignment,
  pushInactiveSurfaceWarning,
  pushWarning,
  readRegularFile,
  readRegularFileSync,
  readStoreAllowFromForDmPolicy,
  readTextFileIfExists,
  redactSensitiveText,
  replaceFileAtomic,
  replaceFileAtomicSync,
  resolveAbsolutePathForRead,
  resolveAbsolutePathForWrite,
  resolveAccessGroupAllowFromMatches,
  resolveAccessGroupAllowFromState,
  resolveChannelAccountSurface,
  resolveDmAllowState,
  resolveDmGroupAccessDecision,
  resolveDmGroupAccessWithCommandGate,
  resolveDmGroupAccessWithLists,
  resolveEffectiveAllowFromLists,
  resolveExistingPathsWithinRoot,
  resolveHookExternalContentSource,
  resolveLocalPathFromRootsSync,
  resolveOpenDmAllowlistAccess,
  resolvePathWithinRoot,
  resolvePathsWithinRoot,
  resolvePinnedHostnameWithPolicy,
  resolvePinnedMainDmOwnerFromAllowlist,
  resolvePreferredOpenClawTmpDir,
  resolveRegularFileAppendFlags,
  resolveStrictExistingPathsWithinRoot,
  resolveWritablePathWithinRoot,
  root,
  safeEqualSecret,
  sanitizeModelSpecialTokens,
  sanitizeUntrustedFileName,
  shouldIncludeSupplementalContext,
  statRegularFile,
  statRegularFileSync,
  testRegexWithBoundedInput,
  toDotPath,
  withTimeout,
  wrapExternalContent,
  wrapWebContent,
  writeExternalFileWithinRoot,
  writeFileFromPathWithinRoot,
  writeJsonFileSecure,
  writeSiblingTempFile,
  writeTextFileAtomic,
  writeViaSiblingTempPath,
};
