import { t as asBoolean } from "../boolean-CThIQsGO.js";
import { s as asFiniteNumber } from "../number-coercion-C7PMvT3i.js";
import {
  a as createProviderHttpError,
  c as formatProviderErrorPayload,
  g as truncateErrorDetail,
  h as readResponseTextLimited,
  l as formatProviderHttpErrorMessage,
  o as extractProviderErrorDetail,
  r as assertOkOrThrowProviderError,
  s as extractProviderRequestId,
  t as asObject,
} from "../provider-http-errors-CYg0W8L9.js";
import {
  a as normalizeSpeechProviderId,
  c as normalizeLanguageCode,
  d as scheduleCleanup,
  i as listSpeechProviders,
  l as normalizeSeed,
  n as getSpeechProvider,
  o as parseTtsDirectives,
  s as normalizeApplyTextNormalization,
  t as canonicalizeSpeechProviderId,
  u as requireInRange,
} from "../provider-registry-CLHsL5A5.js";
import {
  a as createOpenAiCompatibleSpeechProvider,
  i as OpenAiCompatibleSpeechProviderOptions,
  n as OpenAiCompatibleSpeechProviderConfig,
  r as OpenAiCompatibleSpeechProviderExtraJsonBodyField,
  t as OpenAiCompatibleSpeechProviderBaseUrlPolicy,
} from "../speech-DZ0eAoqC.js";
import { l as normalizeOptionalString } from "../string-coerce-DJnd-JG-.js";
import {
  Al as SpeechProviderResolveTalkOverridesContext,
  Cl as SpeechProviderConfiguredContext,
  Dl as SpeechProviderPreparedSynthesis,
  El as SpeechProviderPrepareSynthesisContext,
  Fl as SpeechTelephonySynthesisRequest,
  Gn as SpeechProviderPlugin,
  Il as SpeechVoiceOption,
  Ll as TtsDirectiveOverrides,
  Ml as SpeechSynthesisStreamRequest,
  Nl as SpeechSynthesisStreamResult,
  Ol as SpeechProviderResolveConfigContext,
  Pl as SpeechSynthesisTarget,
  Rl as TtsDirectiveParseResult,
  Sl as SpeechProviderConfig,
  Tl as SpeechProviderOverrides,
  _l as normalizeTtsAutoMode,
  bl as SpeechListVoicesRequest,
  gl as TTS_AUTO_MODES,
  jl as SpeechSynthesisRequest,
  kl as SpeechProviderResolveTalkConfigContext,
  vl as SpeechDirectiveTokenParseContext,
  xl as SpeechModelOverridePolicy,
  yl as SpeechDirectiveTokenParseResult,
} from "../types-Ga3mNO_F.js";
export {
  type OpenAiCompatibleSpeechProviderBaseUrlPolicy,
  type OpenAiCompatibleSpeechProviderConfig,
  type OpenAiCompatibleSpeechProviderExtraJsonBodyField,
  type OpenAiCompatibleSpeechProviderOptions,
  type SpeechDirectiveTokenParseContext,
  type SpeechDirectiveTokenParseResult,
  type SpeechListVoicesRequest,
  type SpeechModelOverridePolicy,
  type SpeechProviderConfig,
  type SpeechProviderConfiguredContext,
  type SpeechProviderOverrides,
  type SpeechProviderPlugin,
  type SpeechProviderPrepareSynthesisContext,
  type SpeechProviderPreparedSynthesis,
  type SpeechProviderResolveConfigContext,
  type SpeechProviderResolveTalkConfigContext,
  type SpeechProviderResolveTalkOverridesContext,
  type SpeechSynthesisRequest,
  type SpeechSynthesisStreamRequest,
  type SpeechSynthesisStreamResult,
  type SpeechSynthesisTarget,
  type SpeechTelephonySynthesisRequest,
  type SpeechVoiceOption,
  TTS_AUTO_MODES,
  type TtsDirectiveOverrides,
  type TtsDirectiveParseResult,
  asBoolean,
  asFiniteNumber,
  asObject,
  assertOkOrThrowProviderError,
  canonicalizeSpeechProviderId,
  createOpenAiCompatibleSpeechProvider,
  createProviderHttpError,
  extractProviderErrorDetail,
  extractProviderRequestId,
  formatProviderErrorPayload,
  formatProviderHttpErrorMessage,
  getSpeechProvider,
  listSpeechProviders,
  normalizeApplyTextNormalization,
  normalizeLanguageCode,
  normalizeSeed,
  normalizeSpeechProviderId,
  normalizeTtsAutoMode,
  parseTtsDirectives,
  readResponseTextLimited,
  requireInRange,
  scheduleCleanup,
  normalizeOptionalString as trimToUndefined,
  truncateErrorDetail,
};
