import { t as asBoolean } from "../boolean-CThIQsGO.js";
import { s as asFiniteNumber } from "../number-coercion-C7PMvT3i.js";
import {
  a as createProviderHttpError,
  c as formatProviderErrorPayload,
  g as truncateErrorDetail,
  h as readResponseTextLimited,
  l as formatProviderHttpErrorMessage,
  o as extractProviderErrorDetail,
  r as assertOkOrThrowProviderError,
  s as extractProviderRequestId,
  t as asObject,
} from "../provider-http-errors-CYg0W8L9.js";
import {
  a as normalizeSpeechProviderId,
  c as normalizeLanguageCode,
  d as scheduleCleanup,
  i as listSpeechProviders,
  l as normalizeSeed,
  n as getSpeechProvider,
  o as parseTtsDirectives,
  r as listLoadedSpeechProviders,
  s as normalizeApplyTextNormalization,
  t as canonicalizeSpeechProviderId,
  u as requireInRange,
} from "../provider-registry-CLHsL5A5.js";
import {
  n as summarizeText,
  t as parseSpeechDirectiveNumberOverride,
} from "../speech-core-BF13Y27a.js";
import { l as normalizeOptionalString } from "../string-coerce-DJnd-JG-.js";
import {
  Al as SpeechProviderResolveTalkOverridesContext,
  Cl as SpeechProviderConfiguredContext,
  Dl as SpeechProviderPreparedSynthesis,
  El as SpeechProviderPrepareSynthesisContext,
  Fl as SpeechTelephonySynthesisRequest,
  Gn as SpeechProviderPlugin,
  Il as SpeechVoiceOption,
  Ll as TtsDirectiveOverrides,
  Ml as SpeechSynthesisStreamRequest,
  Nl as SpeechSynthesisStreamResult,
  Ol as SpeechProviderResolveConfigContext,
  Pl as SpeechSynthesisTarget,
  Rl as TtsDirectiveParseResult,
  Sl as SpeechProviderConfig,
  Tl as SpeechProviderOverrides,
  _l as normalizeTtsAutoMode,
  bl as SpeechListVoicesRequest,
  fl as ResolvedTtsConfig,
  gl as TTS_AUTO_MODES,
  hl as resolveEffectiveTtsConfig,
  jl as SpeechSynthesisRequest,
  kl as SpeechProviderResolveTalkConfigContext,
  ml as TtsConfigResolutionContext,
  pl as ResolvedTtsModelOverrides,
  vl as SpeechDirectiveTokenParseContext,
  xl as SpeechModelOverridePolicy,
  yl as SpeechDirectiveTokenParseResult,
} from "../types-Ga3mNO_F.js";
export {
  type ResolvedTtsConfig,
  type ResolvedTtsModelOverrides,
  type SpeechDirectiveTokenParseContext,
  type SpeechDirectiveTokenParseResult,
  type SpeechListVoicesRequest,
  type SpeechModelOverridePolicy,
  type SpeechProviderConfig,
  type SpeechProviderConfiguredContext,
  type SpeechProviderOverrides,
  type SpeechProviderPlugin,
  type SpeechProviderPrepareSynthesisContext,
  type SpeechProviderPreparedSynthesis,
  type SpeechProviderResolveConfigContext,
  type SpeechProviderResolveTalkConfigContext,
  type SpeechProviderResolveTalkOverridesContext,
  type SpeechSynthesisRequest,
  type SpeechSynthesisStreamRequest,
  type SpeechSynthesisStreamResult,
  type SpeechSynthesisTarget,
  type SpeechTelephonySynthesisRequest,
  type SpeechVoiceOption,
  TTS_AUTO_MODES,
  type TtsConfigResolutionContext,
  type TtsDirectiveOverrides,
  type TtsDirectiveParseResult,
  asBoolean,
  asFiniteNumber,
  asObject,
  assertOkOrThrowProviderError,
  canonicalizeSpeechProviderId,
  createProviderHttpError,
  extractProviderErrorDetail,
  extractProviderRequestId,
  formatProviderErrorPayload,
  formatProviderHttpErrorMessage,
  getSpeechProvider,
  listLoadedSpeechProviders,
  listSpeechProviders,
  normalizeApplyTextNormalization,
  normalizeLanguageCode,
  normalizeSeed,
  normalizeSpeechProviderId,
  normalizeTtsAutoMode,
  parseSpeechDirectiveNumberOverride,
  parseTtsDirectives,
  readResponseTextLimited,
  requireInRange,
  resolveEffectiveTtsConfig,
  scheduleCleanup,
  summarizeText,
  normalizeOptionalString as trimToUndefined,
  truncateErrorDetail,
};
