import {
  $ as PluginHookLlmOutputEvent,
  $t as PluginHookMessageReceivedEvent,
  A as PluginHookBeforeMessageWriteEvent,
  At as PluginHookToolResultPersistContext,
  B as PluginHookGatewayCronCreateInput,
  Bt as isPluginHookName,
  C as PluginHookBeforeInstallContext,
  Ct as PluginHookSubagentSpawnedEvent,
  D as PluginHookBeforeInstallResult,
  Dt as PluginHookToolContext,
  E as PluginHookBeforeInstallRequest,
  Et as PluginHookSubagentTargetKind,
  F as PluginHookCronChangedEvent,
  Ft as PluginInstallSourcePathKind,
  G as PluginHookGatewayCronRunStatus,
  Gt as PluginHeartbeatPromptContributionResult,
  H as PluginHookGatewayCronJob,
  Ht as PluginAgentTurnPrepareEvent,
  I as PluginHookCronReconciledContext,
  It as PluginInstallTargetType,
  J as PluginHookGatewayStartEvent,
  K as PluginHookGatewayCronService,
  L as PluginHookCronReconciledEvent,
  Lt as PromptInjectionHookName,
  M as PluginHookBeforeResetEvent,
  Mt as PluginHookToolResultPersistResult,
  N as PluginHookBeforeToolCallEvent,
  Nt as PluginInstallFinding,
  O as PluginHookBeforeInstallSkill,
  Ot as PluginHookToolInputKind,
  P as PluginHookContextWindowSource,
  Pt as PluginInstallRequestKind,
  Q as PluginHookLlmInputEvent,
  Qt as PluginHookMessageContext,
  R as PluginHookDeprecation,
  Rt as isConversationHookName,
  S as PluginHookBeforeInstallBuiltinScan,
  St as PluginHookSubagentEndedEvent,
  T as PluginHookBeforeInstallPlugin,
  Tt as PluginHookSubagentSpawningResult,
  U as PluginHookGatewayCronJobState,
  Ut as PluginAgentTurnPrepareResult,
  V as PluginHookGatewayCronDeliveryStatus,
  Vt as isPromptInjectionHookName,
  W as PluginHookGatewayCronRemoveResult,
  Wt as PluginHeartbeatPromptContributionEvent,
  X as PluginHookHandlerMap,
  Xt as PluginHookInboundClaimContext,
  Y as PluginHookGatewayStopEvent,
  Z as PluginHookInboundClaimResult,
  Zt as PluginHookInboundClaimEvent,
  _ as PluginHookBeforeAgentRunResult,
  _n as stripPromptMutationFieldsFromLegacyHookResult,
  _t as PluginHookSessionEndReason,
  a as DeprecatedPluginHookName,
  an as PluginApprovalResolution,
  at as PluginHookReplyDispatchContext,
  b as PluginHookBeforeDispatchEvent,
  bt as PluginHookSubagentDeliveryTargetEvent,
  c as PluginHookAfterCompactionEvent,
  cn as PLUGIN_PROMPT_MUTATION_RESULT_FIELDS,
  ct as PluginHookReplyPayload,
  d as PluginHookAgentEndEvent,
  dn as PluginHookBeforeAgentStartResult,
  dt as PluginHookReplyPayloadSendingResult,
  en as PluginHookMessageSendingEvent,
  et as PluginHookModelCallBaseEvent,
  f as PluginHookBeforeAgentFinalizeEvent,
  fn as PluginHookBeforeModelResolveAttachment,
  ft as PluginHookReplyUsageState,
  g as PluginHookBeforeAgentRunEvent,
  gn as PluginHookBeforePromptBuildResult,
  gt as PluginHookSessionEndEvent,
  h as PluginHookBeforeAgentReplyResult,
  hn as PluginHookBeforePromptBuildEvent,
  ht as PluginHookSessionContext,
  i as DEPRECATED_PLUGIN_HOOK_NAMES,
  it as PluginHookRegistration,
  j as PluginHookBeforeMessageWriteResult,
  jt as PluginHookToolResultPersistEvent,
  k as PluginHookBeforeInstallSkillInstallSpec,
  kt as PluginHookToolKind,
  l as PluginHookAfterToolCallEvent,
  ln as PluginHookBeforeAgentStartEvent,
  lt as PluginHookReplyPayloadSendingContext,
  m as PluginHookBeforeAgentReplyEvent,
  mn as PluginHookBeforeModelResolveResult,
  mt as PluginHookResolveExecEnvEvent,
  n as ConversationHookName,
  nn as PluginHookMessageSentEvent,
  nt as PluginHookModelCallStartedEvent,
  o as PLUGIN_HOOK_NAMES,
  on as PluginApprovalResolutions,
  ot as PluginHookReplyDispatchEvent,
  p as PluginHookBeforeAgentFinalizeResult,
  pn as PluginHookBeforeModelResolveEvent,
  pt as PluginHookResolveExecEnvContext,
  q as PluginHookGatewayCronUpdateInput,
  r as DEPRECATED_PLUGIN_HOOKS,
  rt as PluginHookName,
  s as PROMPT_INJECTION_HOOK_NAMES,
  sn as PluginHookBeforeToolCallResult,
  st as PluginHookReplyDispatchResult,
  t as CONVERSATION_HOOK_NAMES,
  tn as PluginHookMessageSendingResult,
  tt as PluginHookModelCallEndedEvent,
  u as PluginHookAgentContext,
  un as PluginHookBeforeAgentStartOverrideResult,
  ut as PluginHookReplyPayloadSendingEvent,
  v as PluginHookBeforeCompactionEvent,
  vt as PluginHookSessionStartEvent,
  w as PluginHookBeforeInstallEvent,
  wt as PluginHookSubagentSpawningEvent,
  x as PluginHookBeforeDispatchResult,
  xt as PluginHookSubagentDeliveryTargetResult,
  y as PluginHookBeforeDispatchContext,
  yt as PluginHookSubagentContext,
  z as PluginHookGatewayContext,
  zt as isDeprecatedPluginHookName,
} from "../hook-types-BPL4xByC.js";
import {
  g as PluginHookChannelSenderContext,
  h as PluginHookChannelContext,
  m as PluginHookChannelChatContext,
} from "../templating-h3OQefFR.js";
export type {
  CONVERSATION_HOOK_NAMES,
  ConversationHookName,
  DEPRECATED_PLUGIN_HOOKS,
  DEPRECATED_PLUGIN_HOOK_NAMES,
  DeprecatedPluginHookName,
  PLUGIN_HOOK_NAMES,
  PLUGIN_PROMPT_MUTATION_RESULT_FIELDS,
  PROMPT_INJECTION_HOOK_NAMES,
  PluginAgentTurnPrepareEvent,
  PluginAgentTurnPrepareResult,
  PluginApprovalResolution,
  PluginApprovalResolutions,
  PluginHeartbeatPromptContributionEvent,
  PluginHeartbeatPromptContributionResult,
  PluginHookAfterCompactionEvent,
  PluginHookAfterToolCallEvent,
  PluginHookAgentContext,
  PluginHookAgentEndEvent,
  PluginHookBeforeAgentFinalizeEvent,
  PluginHookBeforeAgentFinalizeResult,
  PluginHookBeforeAgentReplyEvent,
  PluginHookBeforeAgentReplyResult,
  PluginHookBeforeAgentRunEvent,
  PluginHookBeforeAgentRunResult,
  PluginHookBeforeAgentStartEvent,
  PluginHookBeforeAgentStartOverrideResult,
  PluginHookBeforeAgentStartResult,
  PluginHookBeforeCompactionEvent,
  PluginHookBeforeDispatchContext,
  PluginHookBeforeDispatchEvent,
  PluginHookBeforeDispatchResult,
  PluginHookBeforeInstallBuiltinScan,
  PluginHookBeforeInstallContext,
  PluginHookBeforeInstallEvent,
  PluginHookBeforeInstallPlugin,
  PluginHookBeforeInstallRequest,
  PluginHookBeforeInstallResult,
  PluginHookBeforeInstallSkill,
  PluginHookBeforeInstallSkillInstallSpec,
  PluginHookBeforeMessageWriteEvent,
  PluginHookBeforeMessageWriteResult,
  PluginHookBeforeModelResolveAttachment,
  PluginHookBeforeModelResolveEvent,
  PluginHookBeforeModelResolveResult,
  PluginHookBeforePromptBuildEvent,
  PluginHookBeforePromptBuildResult,
  PluginHookBeforeResetEvent,
  PluginHookBeforeToolCallEvent,
  PluginHookBeforeToolCallResult,
  PluginHookChannelChatContext,
  PluginHookChannelContext,
  PluginHookChannelSenderContext,
  PluginHookContextWindowSource,
  PluginHookCronChangedEvent,
  PluginHookCronReconciledContext,
  PluginHookCronReconciledEvent,
  PluginHookDeprecation,
  PluginHookGatewayContext,
  PluginHookGatewayCronCreateInput,
  PluginHookGatewayCronDeliveryStatus,
  PluginHookGatewayCronJob,
  PluginHookGatewayCronJobState,
  PluginHookGatewayCronRemoveResult,
  PluginHookGatewayCronRunStatus,
  PluginHookGatewayCronService,
  PluginHookGatewayCronUpdateInput,
  PluginHookGatewayStartEvent,
  PluginHookGatewayStopEvent,
  PluginHookHandlerMap,
  PluginHookInboundClaimContext,
  PluginHookInboundClaimEvent,
  PluginHookInboundClaimResult,
  PluginHookLlmInputEvent,
  PluginHookLlmOutputEvent,
  PluginHookMessageContext,
  PluginHookMessageReceivedEvent,
  PluginHookMessageSendingEvent,
  PluginHookMessageSendingResult,
  PluginHookMessageSentEvent,
  PluginHookModelCallBaseEvent,
  PluginHookModelCallEndedEvent,
  PluginHookModelCallStartedEvent,
  PluginHookName,
  PluginHookRegistration,
  PluginHookReplyDispatchContext,
  PluginHookReplyDispatchEvent,
  PluginHookReplyDispatchResult,
  PluginHookReplyPayload,
  PluginHookReplyPayloadSendingContext,
  PluginHookReplyPayloadSendingEvent,
  PluginHookReplyPayloadSendingResult,
  PluginHookReplyUsageState,
  PluginHookResolveExecEnvContext,
  PluginHookResolveExecEnvEvent,
  PluginHookSessionContext,
  PluginHookSessionEndEvent,
  PluginHookSessionEndReason,
  PluginHookSessionStartEvent,
  PluginHookSubagentContext,
  PluginHookSubagentDeliveryTargetEvent,
  PluginHookSubagentDeliveryTargetResult,
  PluginHookSubagentEndedEvent,
  PluginHookSubagentSpawnedEvent,
  PluginHookSubagentSpawningEvent,
  PluginHookSubagentSpawningResult,
  PluginHookSubagentTargetKind,
  PluginHookToolContext,
  PluginHookToolInputKind,
  PluginHookToolKind,
  PluginHookToolResultPersistContext,
  PluginHookToolResultPersistEvent,
  PluginHookToolResultPersistResult,
  PluginInstallFinding,
  PluginInstallRequestKind,
  PluginInstallSourcePathKind,
  PluginInstallTargetType,
  PromptInjectionHookName,
  isConversationHookName,
  isDeprecatedPluginHookName,
  isPluginHookName,
  isPromptInjectionHookName,
  stripPromptMutationFieldsFromLegacyHookResult,
};
