import { n as isWellFormedApprovalId } from "../../approval-id-BTRnO3t1.js";
import {
  C as PluginApprovalSeveritySchema,
  E as TerminalApprovalSnapshotSchema,
  S as PluginApprovalPresentationSchema,
  T as SessionApprovalReplaySchema,
  _ as DeniedApprovalSnapshotSchema,
  a as ApprovalDecisionSchema,
  b as PendingApprovalSnapshotSchema,
  c as ApprovalGetParamsSchema,
  d as ApprovalPresentationSchema,
  f as ApprovalResolveParamsSchema,
  g as CancelledApprovalSnapshotSchema,
  h as ApprovalTerminalReasonSchema,
  l as ApprovalGetResultSchema,
  m as ApprovalSnapshotSchema,
  n as ApprovalAllowDecisionSchema,
  p as ApprovalResolveResultSchema,
  t as AllowedApprovalSnapshotSchema,
  u as ApprovalKindSchema,
  v as ExecApprovalPresentationSchema,
  w as SessionApprovalEventSchema,
  y as ExpiredApprovalSnapshotSchema,
} from "../../approvals-BSpwjSwI.js";
import { n as errorShape, t as ErrorCodes } from "../../error-codes-O0AkRNx7.js";
import {
  $ as SessionFileKindSchema,
  $a as AuditActivityToolActionV1Schema,
  $i as ConfigSchemaParamsSchema,
  $n as NodePresenceAlivePayloadSchema,
  $o as SkillsSecurityVerdictsParamsSchema,
  $r as ExecApprovalRequestParamsSchema,
  $t as SessionsCatalogReadParamsSchema,
  A as TasksCancelResultSchema,
  Aa as TalkSessionCreateResultSchema,
  Ai as CrestodianChatParamsSchema,
  An as PluginsUninstallResultSchema,
  Ao as ModelsProbeTargetResultSchema,
  Ar as FsListDirResultSchema,
  As as SkillsProposalHistoryScanParamsSchema,
  At as SessionsPatchParamsSchema,
  B as TaskSuggestionsCreateParamsSchema,
  Ba as TtsSpeakParamsSchema,
  Bi as WizardCancelParamsSchema,
  Bn as NodeListParamsSchema,
  Bo as SkillsProposalApplyResultSchema,
  Br as TickEventSchema,
  Bt as SessionsCreateParamsSchema,
  C as TerminalOpenResultSchema,
  Ca as TalkEventSchema,
  Ci as CronJobSchema,
  Cn as PluginsSessionActionParamsSchema,
  Co as AgentsListResultSchema,
  Cr as GatewaySuspendStatusParamsSchema,
  Cs as MemoryMigrationProviderPlanSchema,
  Ct as SessionsGroupsListResultSchema,
  D as TerminalTextResultSchema,
  Da as TalkSessionCancelTurnParamsSchema,
  Di as CronRunsParamsSchema,
  Dn as PluginsUiDescriptorsParamsSchema,
  Do as ModelsListParamsSchema,
  Dr as GatewaySuspendTaskBlockerSchema,
  Ds as MigrationsMemoryApplyResultSchema,
  Dt as SessionsListParamsSchema,
  E as TerminalTextParamsSchema,
  Ea as TalkSessionCancelOutputParamsSchema,
  Ei as CronRunParamsSchema,
  En as PluginsSetEnabledResultSchema,
  Eo as AuthProbeStatusSchema,
  Er as GatewaySuspendStatusRunningResultSchema,
  Es as MigrationsMemoryApplyParamsSchema,
  Et as SessionsGroupsRenameParamsSchema,
  F as TaskSuggestionEventSchema,
  Fa as TalkSessionSubmitToolResultParamsSchema,
  Fi as CrestodianSetupAuthStartResultSchema,
  Fn as NodeEventResultSchema,
  Fo as SkillsCuratorStatusResultSchema,
  Fr as GatewayFrameSchema,
  Ft as SessionsSearchHitSchema,
  G as TaskSuggestionsListResultSchema,
  Ga as AuditListParamsSchema,
  Gi as WizardStatusParamsSchema,
  Gn as NodePendingAckParamsSchema,
  Go as SkillsProposalRequestRevisionParamsSchema,
  Gt as SessionCatalogSessionSchema,
  H as TaskSuggestionsDismissParamsSchema,
  Ha as WebLoginStartParamsSchema,
  Hi as WizardNextResultSchema,
  Hn as NodePairListParamsSchema,
  Ho as SkillsProposalInspectParamsSchema,
  Hr as SnapshotSchema,
  Ht as SessionCatalogDescriptorSchema,
  I as TaskSuggestionResolutionSchema,
  Ia as TalkSessionTurnParamsSchema,
  Ii as CrestodianSetupDetectParamsSchema,
  In as NodeInvokeInputEventSchema,
  Io as SkillsDetailParamsSchema,
  Ir as HelloOkSchema,
  It as SessionsSearchParamsSchema,
  J as SessionDiffFileSchema,
  Ja as AuditActivityEventV1Schema,
  Ji as ConfigApplyParamsSchema,
  Jn as NodePendingEnqueueParamsSchema,
  Jo as SkillsProposalUpdateParamsSchema,
  Jt as SessionsCatalogArchiveResultSchema,
  K as SystemInfoParamsSchema,
  Ka as AuditListResultSchema,
  Ki as WizardStatusResultSchema,
  Kn as NodePendingDrainParamsSchema,
  Ko as SkillsProposalRequestRevisionResultSchema,
  Kt as SessionCatalogTranscriptItemSchema,
  L as TaskSuggestionSchema,
  La as TalkSessionTurnResultSchema,
  Li as CrestodianSetupDetectResultSchema,
  Ln as NodeInvokeParamsSchema,
  Lo as SkillsDetailResultSchema,
  Lr as RequestFrameSchema,
  Lt as SessionsSearchResultSchema,
  M as TasksGetResultSchema,
  Ma as TalkSessionJoinResultSchema,
  Mi as CrestodianSetupActivateParamsSchema,
  Mo as SkillsCuratorActionParamsSchema,
  Mr as ErrorShapeSchema,
  Ms as SkillsProposalHistoryStatusParamsSchema,
  Mt as SessionsPreviewParamsSchema,
  N as TasksListParamsSchema,
  Na as TalkSessionOkResultSchema,
  Ni as CrestodianSetupActivateResultSchema,
  No as SkillsCuratorActionResultSchema,
  Nr as EventFrameSchema,
  Ns as validateSkillsProposalHistoryScanParams,
  Nt as SessionsResetParamsSchema,
  O as TaskSummarySchema,
  Oa as TalkSessionCloseParamsSchema,
  Oi as CronStatusParamsSchema,
  On as PluginsUiDescriptorsResultSchema,
  Oo as ModelsProbeParamsSchema,
  Or as FsDirEntrySchema,
  Os as MigrationsMemoryPlanParamsSchema,
  P as TasksListResultSchema,
  Pa as TalkSessionSteerParamsSchema,
  Pi as CrestodianSetupAuthStartParamsSchema,
  Po as SkillsCuratorStatusParamsSchema,
  Pr as GATEWAY_SERVER_CAPS,
  Ps as validateSkillsProposalHistoryStatusParams,
  Pt as SessionsResolveParamsSchema,
  Q as SessionFileEntrySchema,
  Qa as AuditActivityOutboundMessageV1Schema,
  Qi as ConfigSchemaLookupResultSchema,
  Qn as NodePresenceActivityPayloadSchema,
  Qo as SkillsSearchResultSchema,
  Qr as ExecApprovalGetParamsSchema,
  Qt as SessionsCatalogListResultSchema,
  R as TaskSuggestionsAcceptParamsSchema,
  Ra as TalkSpeakParamsSchema,
  Ri as CrestodianSetupVerifyParamsSchema,
  Rn as NodeInvokeProgressParamsSchema,
  Ro as SkillsInstallParamsSchema,
  Rr as ResponseFrameSchema,
  Rt as SessionsSendParamsSchema,
  S as TerminalOpenParamsSchema,
  Sa as TalkConfigResultSchema,
  Si as CronGetParamsSchema,
  Sn as PluginsSearchResultSchema,
  So as AgentsListParamsSchema,
  Sr as GatewaySuspendResumeResultSchema,
  Ss as MemoryMigrationItemStatusSchema,
  St as SessionsGroupsListParamsSchema,
  T as TerminalSessionInfoSchema,
  Ta as TalkSessionAppendAudioParamsSchema,
  Ti as CronRemoveParamsSchema,
  Tn as PluginsSetEnabledParamsSchema,
  To as AgentsUpdateResultSchema,
  Tr as GatewaySuspendStatusResultSchema,
  Ts as MigrationProtocolSchemas,
  Tt as SessionsGroupsPutParamsSchema,
  U as TaskSuggestionsDismissResultSchema,
  Ua as WebLoginWaitParamsSchema,
  Ui as WizardStartParamsSchema,
  Un as NodePairRejectParamsSchema,
  Uo as SkillsProposalInspectResultSchema,
  Ur as StateVersionSchema,
  Ut as SessionCatalogHostSchema,
  V as TaskSuggestionsCreateResultSchema,
  Va as TtsSpeakResultSchema,
  Vi as WizardNextParamsSchema,
  Vn as NodePairApproveParamsSchema,
  Vo as SkillsProposalCreateParamsSchema,
  Vr as PresenceEntrySchema,
  Vt as SessionCatalogCapabilitiesSchema,
  W as TaskSuggestionsListParamsSchema,
  Wa as AuditEventSchema,
  Wi as WizardStartResultSchema,
  Wn as NodePairRemoveParamsSchema,
  Wo as SkillsProposalRecordResultSchema,
  Wt as SessionCatalogSchema,
  X as SessionFileBrowserEntrySchema,
  Xa as AuditActivityListParamsSchema,
  Xi as ConfigPatchParamsSchema,
  Xn as NodePluginToolDescriptorSchema,
  Xo as SkillsProposalsListResultSchema,
  Xt as SessionsCatalogContinueResultSchema,
  Y as SessionDiffFileStatusSchema,
  Ya as AuditActivityInboundMessageV1Schema,
  Yi as ConfigGetParamsSchema,
  Yn as NodePendingEnqueueResultSchema,
  Yo as SkillsProposalsListParamsSchema,
  Yt as SessionsCatalogContinueParamsSchema,
  Z as SessionFileBrowserResultSchema,
  Za as AuditActivityListResultSchema,
  Zi as ConfigSchemaLookupParamsSchema,
  Zn as NodePluginToolsUpdateParamsSchema,
  Zo as SkillsSearchParamsSchema,
  Zt as SessionsCatalogListParamsSchema,
  _ as TerminalDataEventSchema,
  _a as TalkClientCreateResultSchema,
  _i as WorkerEnvironmentStateSchema,
  _n as PluginsInstallParamsSchema,
  _o as AgentsFilesGetResultSchema,
  _r as GatewaySuspendPrepareBusyResultSchema,
  _s as PollParamsSchema,
  _t as SessionsFilesListParamsSchema,
  a as WorktreesCreateParamsSchema,
  aa as CommandsListParamsSchema,
  ai as ExecApprovalsSetParamsSchema,
  ao as AgentsWorkspaceFileSchema,
  ar as ChatEventSchema,
  as as SkillsUploadBeginParamsSchema,
  at as SessionsCompactParamsSchema,
  b as TerminalInputParamsSchema,
  ba as TalkClientToolCallResultSchema,
  bi as CronAddResultSchema,
  bn as PluginsListResultSchema,
  bo as AgentsFilesSetParamsSchema,
  br as GatewaySuspendPrepareResultSchema,
  bs as MAX_MEMORY_MIGRATION_ITEMS,
  bt as SessionsFilesSetResultSchema,
  c as WorktreesListParamsSchema,
  ca as ChannelsLogoutParamsSchema,
  ci as EnvironmentsCreateParamsSchema,
  cn as PushTestResultSchema,
  co as AgentsWorkspaceListParamsSchema,
  cs as ToolsCatalogParamsSchema,
  ct as SessionsCompactionListParamsSchema,
  d as WorktreesRemoveResultSchema,
  da as ChannelsStatusResultSchema,
  di as EnvironmentsDestroyResultSchema,
  dn as WebPushUnsubscribeParamsSchema,
  do as AgentsCreateParamsSchema,
  dr as ChatSendParamsSchema,
  ds as AgentEventSchema,
  dt as SessionsDeleteParamsSchema,
  ea as ConfigSchemaResponseSchema,
  ei as ExecApprovalResolveParamsSchema,
  en as SessionsCatalogReadResultSchema,
  eo as ArtifactSummarySchema,
  er as NodePresenceAliveReasonSchema,
  es as SkillsSecurityVerdictsResultSchema,
  et as SessionFileRelevanceSchema,
  f as WorktreesRestoreParamsSchema,
  fa as ChannelsStopParamsSchema,
  fi as EnvironmentsListParamsSchema,
  fn as WebPushVapidPublicKeyParamsSchema,
  fo as AgentsCreateResultSchema,
  fr as ChatToolTitlesParamsSchema,
  fs as AgentIdentityParamsSchema,
  ft as SessionsDescribeParamsSchema,
  g as TerminalCloseParamsSchema,
  ga as TalkClientCreateParamsSchema,
  gi as WorkerEnvironmentMetadataSchema,
  gn as PluginSearchResultEntrySchema,
  go as AgentsFilesGetParamsSchema,
  gr as GatewaySuspendBlockerSchema,
  gs as MessageActionParamsSchema,
  gt as SessionsFilesGetResultSchema,
  h as TerminalAttachResultSchema,
  ha as TalkCatalogResultSchema,
  hi as EnvironmentsStatusResultSchema,
  hn as PluginSearchPackageSchema,
  ho as AgentsFileEntrySchema,
  hr as LogsTailResultSchema,
  ht as SessionsFilesGetParamsSchema,
  i as WorktreesBranchesResultSchema,
  in as SessionsDispatchResultSchema,
  io as AgentsWorkspaceEntrySchema,
  is as SkillsUpdateParamsSchema,
  it as SessionsCleanupParamsSchema,
  j as TasksGetParamsSchema,
  ja as TalkSessionJoinParamsSchema,
  ji as CrestodianChatResultSchema,
  jr as ConnectParamsSchema,
  js as SkillsProposalHistoryScanResultSchema,
  jt as SessionsPluginPatchParamsSchema,
  k as TasksCancelParamsSchema,
  ka as TalkSessionCreateParamsSchema,
  ki as CronUpdateParamsSchema,
  kn as PluginsUninstallParamsSchema,
  ko as ModelsProbeResultSchema,
  kr as FsListDirParamsSchema,
  ks as MigrationsMemoryPlanResultSchema,
  l as WorktreesListResultSchema,
  la as ChannelsStartParamsSchema,
  li as EnvironmentsCreateResultSchema,
  ln as WebPushSubscribeParamsSchema,
  lo as AgentsWorkspaceListResultSchema,
  ls as ToolsEffectiveParamsSchema,
  lt as SessionsCompactionRestoreParamsSchema,
  m as TerminalAttachParamsSchema,
  ma as TalkCatalogParamsSchema,
  mi as EnvironmentsStatusParamsSchema,
  mn as PluginCatalogInstallActionSchema,
  mo as AgentsDeleteResultSchema,
  mr as LogsTailParamsSchema,
  ms as AgentParamsSchema,
  mt as SessionsDiffResultSchema,
  n as WorktreeRecordSchema,
  na as UpdateRunParamsSchema,
  nn as SessionPlacementStateSchema,
  no as ArtifactsGetParamsSchema,
  nr as NodeSkillDescriptorSchema,
  ns as SkillsSkillCardResultSchema,
  nt as SessionWorktreeInfoSchema,
  o as WorktreesGcParamsSchema,
  oa as CommandsListResultSchema,
  oi as EnvironmentStatusSchema,
  oo as AgentsWorkspaceGetParamsSchema,
  or as ChatHistoryParamsSchema,
  os as SkillsUploadChunkParamsSchema,
  ot as SessionsCompactionBranchParamsSchema,
  p as TerminalAckResultSchema,
  pa as TalkAgentControlResultSchema,
  pi as EnvironmentsListResultSchema,
  pn as PluginCatalogEntrySchema,
  po as AgentsDeleteParamsSchema,
  pr as ChatToolTitlesResultSchema,
  ps as AgentIdentityResultSchema,
  pt as SessionsDiffParamsSchema,
  q as SystemInfoResultSchema,
  qa as AuditActivityAgentRunV1Schema,
  qi as WizardStepSchema,
  qn as NodePendingDrainResultSchema,
  qo as SkillsProposalReviseParamsSchema,
  qt as SessionsCatalogArchiveParamsSchema,
  r as WorktreesBranchesParamsSchema,
  ra as UpdateStatusParamsSchema,
  rn as SessionsDispatchParamsSchema,
  ro as ArtifactsListParamsSchema,
  rr as NodeSkillsUpdateParamsSchema,
  rs as SkillsStatusParamsSchema,
  rt as SessionsAbortParamsSchema,
  s as WorktreesGcResultSchema,
  sa as TalkSessionAcknowledgeMarkParamsSchema,
  si as EnvironmentSummarySchema,
  sn as PushTestParamsSchema,
  so as AgentsWorkspaceGetResultSchema,
  sr as ChatInjectParamsSchema,
  ss as SkillsUploadCommitParamsSchema,
  st as SessionsCompactionGetParamsSchema,
  t as WorktreeBranchSchema,
  ta as ConfigSetParamsSchema,
  ti as ExecApprovalsGetParamsSchema,
  tn as SessionPlacementSchema,
  to as ArtifactsDownloadParamsSchema,
  ts as SkillsSkillCardParamsSchema,
  tt as SessionGroupSchema,
  u as WorktreesRemoveParamsSchema,
  ua as ChannelsStatusParamsSchema,
  ui as EnvironmentsDestroyParamsSchema,
  un as WebPushTestParamsSchema,
  uo as AgentSummarySchema,
  ur as ChatMetadataParamsSchema,
  us as ToolsInvokeParamsSchema,
  ut as SessionsCreateResultSchema,
  v as TerminalEventSchema,
  va as TalkClientSteerParamsSchema,
  vi as WorkerTunnelStatusSchema,
  vn as PluginsInstallResultSchema,
  vo as AgentsFilesListParamsSchema,
  vr as GatewaySuspendPrepareParamsSchema,
  vs as SendParamsSchema,
  vt as SessionsFilesListResultSchema,
  w as TerminalResizeParamsSchema,
  wi as CronListParamsSchema,
  wn as PluginsSessionActionResultSchema,
  wo as AgentsUpdateParamsSchema,
  wr as GatewaySuspendStatusReadyResultSchema,
  ws as MemoryMigrationSummarySchema,
  wt as SessionsGroupsMutationResultSchema,
  x as TerminalListResultSchema,
  xa as TalkConfigParamsSchema,
  xi as CronDeclarativeAddResultSchema,
  xn as PluginsSearchParamsSchema,
  xo as AgentsFilesSetResultSchema,
  xr as GatewaySuspendResumeParamsSchema,
  xs as MemoryMigrationItemSchema,
  xt as SessionsGroupsDeleteParamsSchema,
  y as TerminalExitEventSchema,
  ya as TalkClientToolCallParamsSchema,
  yi as CronAddParamsSchema,
  yn as PluginsListParamsSchema,
  yo as AgentsFilesListResultSchema,
  yr as GatewaySuspendPrepareReadyResultSchema,
  ys as WakeParamsSchema,
  yt as SessionsFilesSetParamsSchema,
  z as TaskSuggestionsAcceptResultSchema,
  za as TalkSpeakResultSchema,
  zi as CrestodianSetupVerifyResultSchema,
  zo as SkillsProposalActionParamsSchema,
  zr as ShutdownEventSchema,
  zt as SessionsUsageParamsSchema,
} from "../../schema-C_z7F42p.js";
import {
  $ as validateCrestodianSetupDetectParams,
  $i as validateWorktreesBranchesParams,
  $n as validateSessionsDispatchResult,
  $r as validateTalkSessionAcknowledgeMarkParams,
  $t as validateNodePairApproveParams,
  A as validateChannelsStatusParams,
  Ai as validateToolsCatalogParams,
  An as validatePollParams,
  Ar as validateSkillsProposalsListParams,
  At as validateExecApprovalsNodeSnapshot,
  B as validateChatToolTitlesParams,
  Bi as validateWebPushSubscribeParams,
  Bn as validateSessionsCatalogListParams,
  Br as validateSystemInfoResult,
  Bt as validateGatewaySuspendStatusResult,
  C as validateArtifactsGetParams,
  Ci as validateTerminalAttachParams,
  Cn as validatePluginsSessionActionResult,
  Cr as validateSkillsInstallParams,
  Ct as validateExecApprovalGetParams,
  D as validateCancelledApprovalSnapshot,
  Di as validateTerminalOpenParams,
  Dn as validatePluginsUiDescriptorsResult,
  Dr as validateSkillsProposalRequestRevisionParams,
  Dt as validateExecApprovalsGetParams,
  E as validateAuditListParams,
  Ei as validateTerminalInputParams,
  En as validatePluginsUiDescriptorsParams,
  Er as validateSkillsProposalInspectParams,
  Et as validateExecApprovalResolveParams,
  F as validateChatInjectParams,
  Fi as validateUpdateRunParams,
  Fn as validateSecretsResolveResult,
  Fr as validateSkillsUpdateParams,
  Ft as validateGatewaySuspendPrepareParams,
  G as validateConfigSchemaLookupParams,
  Gi as validateWizardNextParams,
  Gn as validateSessionsCompactionGetParams,
  Gr as validateTalkClientCreateResult,
  Gt as validateNodeDescribeParams,
  H as validateConfigApplyParams,
  Hi as validateWebPushUnsubscribeParams,
  Hn as validateSessionsCleanupParams,
  Hr as validateTalkCatalogParams,
  Ht as validateMessageActionParams,
  I as validateChatMessageGetParams,
  Ii as validateUpdateStatusParams,
  In as validateSendParams,
  Ir as validateSkillsUploadBeginParams,
  It as validateGatewaySuspendPrepareResult,
  J as validateConfigSetParams,
  Ji as validateWorkerAdmissionHandshake,
  Jn as validateSessionsCreateParams,
  Jr as validateTalkClientToolCallResult,
  Jt as validateNodeInvokeInputEvent,
  K as validateConfigSchemaLookupResult,
  Ki as validateWizardStartParams,
  Kn as validateSessionsCompactionListParams,
  Kr as validateTalkClientSteerParams,
  Kt as validateNodeEventParams,
  L as validateChatMessageGetResult,
  Li as validateWakeParams,
  Ln as validateSessionsAbortParams,
  Lr as validateSkillsUploadChunkParams,
  Lt as validateGatewaySuspendResumeParams,
  M as validateChatAbortParams,
  Mi as validateToolsInvokeParams,
  Mn as validateRequestFrame,
  Mr as validateSkillsSecurityVerdictsParams,
  Mt as validateExpiredApprovalSnapshot,
  N as validateChatEvent,
  Ni as validateTtsSpeakParams,
  Nn as validateResponseFrame,
  Nr as validateSkillsSkillCardParams,
  Nt as validateFsListDirParams,
  O as validateChannelsLogoutParams,
  Oi as validateTerminalResizeParams,
  On as validatePluginsUninstallParams,
  Or as validateSkillsProposalReviseParams,
  Ot as validateExecApprovalsNodeGetParams,
  P as validateChatHistoryParams,
  Pi as validateTtsSpeakResult,
  Pn as validateSecretsResolveParams,
  Pr as validateSkillsStatusParams,
  Pt as validateFsListDirResult,
  Q as validateCrestodianSetupAuthStartParams,
  Qi as validateWorkerTranscriptCommitParams,
  Qn as validateSessionsDispatchParams,
  Qr as validateTalkModeParams,
  Qt as validateNodeListParams,
  R as validateChatMetadataParams,
  Ri as validateWebLoginStartParams,
  Rn as validateSessionsCatalogArchiveParams,
  Rr as validateSkillsUploadCommitParams,
  Rt as validateGatewaySuspendResumeResult,
  S as validateArtifactsDownloadParams,
  Si as validateTerminalApprovalSnapshot,
  Sn as validatePluginsSessionActionParams,
  Sr as validateSkillsDetailParams,
  St as validateEventFrame,
  T as validateAuditActivityListParams,
  Ti as validateTerminalEvent,
  Tn as validatePluginsSetEnabledResult,
  Tr as validateSkillsProposalCreateParams,
  Tt as validateExecApprovalRequestParams,
  U as validateConfigGetParams,
  Ui as validateWebPushVapidPublicKeyParams,
  Un as validateSessionsCompactParams,
  Ur as validateTalkCatalogResult,
  Ut as validateModelsListParams,
  V as validateCommandsListParams,
  Vi as validateWebPushTestParams,
  Vn as validateSessionsCatalogReadParams,
  Vr as validateTalkAgentControlResult,
  Vt as validateLogsTailParams,
  W as validateConfigPatchParams,
  Wi as validateWizardCancelParams,
  Wn as validateSessionsCompactionBranchParams,
  Wr as validateTalkClientCreateParams,
  Wt as validateModelsProbeParams,
  X as validateCrestodianChatParams,
  Xi as validateWorkerHeartbeatParams,
  Xn as validateSessionsDescribeParams,
  Xr as validateTalkConfigResult,
  Xt as validateNodeInvokeProgressParams,
  Y as validateConnectParams,
  Yi as validateWorkerConnectRequestFrame,
  Yn as validateSessionsDeleteParams,
  Yr as validateTalkConfigParams,
  Yt as validateNodeInvokeParams,
  Z as validateCrestodianSetupActivateParams,
  Zi as validateWorkerLiveEventParams,
  Zn as validateSessionsDiffParams,
  Zr as validateTalkEvent,
  Zt as validateNodeInvokeResultParams,
  _ as validateApprovalKind,
  _i as validateTaskSuggestionsDismissParams,
  _n as validatePluginsInstallResult,
  _r as validateSessionsSendParams,
  _t as validateDeviceTokenRotateParams,
  a as validateAgentsDeleteParams,
  aa as validateMigrationsMemoryApplyParams,
  ai as validateTalkSessionCreateResult,
  an as validateNodePendingEnqueueParams,
  ar as validateSessionsGroupsPutParams,
  at as validateCronRunParams,
  b as validateApprovalSnapshot,
  bi as validateTasksGetParams,
  bn as validatePluginsSearchParams,
  br as validateSkillsCuratorActionParams,
  bt as validateEnvironmentsListParams,
  c as validateAgentsFilesSetParams,
  ca as validateApprovalResolveResult,
  ci as validateTalkSessionOkResult,
  cn as validateNodePresenceAlivePayload,
  cr as validateSessionsMessagesSubscribeParams,
  ct as validateCronUpdateParams,
  d as validateAgentsWorkspaceGetParams,
  da as isClawHubTrustErrorCode,
  di as validateTalkSessionTurnParams,
  dn as validatePendingApprovalSnapshot,
  dr as validateSessionsPluginPatchParams,
  dt as validateDevicePairListParams,
  ea as validateWorktreesCreateParams,
  ei as validateTalkSessionAppendAudioParams,
  en as validateNodePairListParams,
  er as validateSessionsFilesGetParams,
  et as validateCrestodianSetupVerifyParams,
  f as validateAgentsWorkspaceListParams,
  fa as readClawHubTrustErrorDetails,
  fi as validateTalkSessionTurnResult,
  fn as validatePluginApprovalPresentation,
  fr as validateSessionsPreviewParams,
  ft as validateDevicePairRejectParams,
  g as validateApprovalGetParams,
  gi as validateTaskSuggestionsCreateParams,
  gn as validatePluginsInstallParams,
  gr as validateSessionsSearchResult,
  gt as validateDeviceTokenRevokeParams,
  h as validateApprovalDecision,
  hi as validateTaskSuggestionsAcceptParams,
  hn as validatePluginApprovalSeverity,
  hr as validateSessionsSearchParams,
  ht as validateDevicePairSetupCodeParams,
  i as validateAgentsCreateParams,
  ia as validateWorktreesRestoreParams,
  ii as validateTalkSessionCreateParams,
  in as validateNodePendingDrainParams,
  ir as validateSessionsGroupsListParams,
  it as validateCronRemoveParams,
  j as validateChannelsStopParams,
  ji as validateToolsEffectiveParams,
  jn as validatePushTestParams,
  jr as validateSkillsSearchParams,
  jt as validateExecApprovalsSetParams,
  k as validateChannelsStartParams,
  ki as validateTerminalTextParams,
  kn as validatePluginsUninstallResult,
  kr as validateSkillsProposalUpdateParams,
  kt as validateExecApprovalsNodeSetParams,
  l as validateAgentsListParams,
  la as ClawHubTrustErrorCodes,
  li as validateTalkSessionSteerParams,
  ln as validateNodeRenameParams,
  lr as validateSessionsMessagesUnsubscribeParams,
  lt as validateDeniedApprovalSnapshot,
  m as validateApprovalAllowDecision,
  mi as validateTalkSpeakResult,
  mn as validatePluginApprovalResolveParams,
  mr as validateSessionsResolveParams,
  mt as validateDevicePairRenameParams,
  n as validateAgentParams,
  na as validateWorktreesListParams,
  ni as validateTalkSessionCancelTurnParams,
  nn as validateNodePairRemoveParams,
  nr as validateSessionsFilesSetParams,
  nt as validateCronGetParams,
  o as validateAgentsFilesGetParams,
  oa as validateMigrationsMemoryPlanParams,
  oi as validateTalkSessionJoinParams,
  on as validateNodePluginToolsUpdateParams,
  or as validateSessionsGroupsRenameParams,
  ot as validateCronRunsParams,
  p as validateAllowedApprovalSnapshot,
  pi as validateTalkSpeakParams,
  pn as validatePluginApprovalRequestParams,
  pr as validateSessionsResetParams,
  pt as validateDevicePairRemoveParams,
  q as validateConfigSchemaParams,
  qi as validateWizardStatusParams,
  qn as validateSessionsCompactionRestoreParams,
  qr as validateTalkClientToolCallParams,
  qt as validateNodeEventResult,
  r as validateAgentWaitParams,
  ra as validateWorktreesRemoveParams,
  ri as validateTalkSessionCloseParams,
  rn as validateNodePendingAckParams,
  rr as validateSessionsGroupsDeleteParams,
  rt as validateCronListParams,
  s as validateAgentsFilesListParams,
  sa as validateApprovalGetResult,
  si as validateTalkSessionJoinResult,
  sn as validateNodePresenceActivityPayload,
  sr as validateSessionsListParams,
  st as validateCronStatusParams,
  t as validateAgentIdentityParams,
  ta as validateWorktreesGcParams,
  ti as validateTalkSessionCancelOutputParams,
  tn as validateNodePairRejectParams,
  tr as validateSessionsFilesListParams,
  tt as validateCronAddParams,
  u as validateAgentsUpdateParams,
  ua as buildClawHubTrustErrorDetails,
  ui as validateTalkSessionSubmitToolResultParams,
  un as validateNodeSkillsUpdateParams,
  ur as validateSessionsPatchParams,
  ut as validateDevicePairApproveParams,
  v as validateApprovalPresentation,
  vi as validateTaskSuggestionsListParams,
  vn as validatePluginsListParams,
  vr as validateSessionsUsageParams,
  vt as validateEnvironmentsCreateParams,
  w as validateArtifactsListParams,
  wi as validateTerminalCloseParams,
  wn as validatePluginsSetEnabledParams,
  wr as validateSkillsProposalActionParams,
  wt as validateExecApprovalPresentation,
  x as validateApprovalTerminalReason,
  xi as validateTasksListParams,
  xn as validatePluginsSearchResult,
  xr as validateSkillsCuratorStatusParams,
  xt as validateEnvironmentsStatusParams,
  y as validateApprovalResolveParams,
  yi as validateTasksCancelParams,
  yn as validatePluginsListResult,
  yr as validateSkillsBinsParams,
  yt as validateEnvironmentsDestroyParams,
  z as validateChatSendParams,
  zi as validateWebLoginWaitParams,
  zn as validateSessionsCatalogContinueParams,
  zr as validateSystemInfoParams,
  zt as validateGatewaySuspendStatusParams,
} from "../../src-CIJf1lT0.js";
import { t as formatValidationErrors } from "../../validation-errors-B9K6VbD7.js";
import {
  i as PROTOCOL_VERSION,
  n as MIN_NODE_PROTOCOL_VERSION,
  r as MIN_PROBE_PROTOCOL_VERSION,
  t as MIN_CLIENT_PROTOCOL_VERSION,
} from "../../version-CwNT1gaY.js";
import {
  A as WorkerLiveEventRequestFrameSchema,
  B as WorkerTranscriptCommitResultSchema,
  C as WorkerHeartbeatRequestFrameSchema,
  D as WorkerLiveEventErrorDetailsSchema,
  F as WorkerTranscriptCommitErrorReasonSchema,
  I as WorkerTranscriptCommitErrorShapeSchema,
  L as WorkerTranscriptCommitParamsSchema,
  M as WorkerLiveEventResultSchema,
  N as WorkerLiveEventSchema,
  O as WorkerLiveEventErrorShapeSchema,
  P as WorkerProtocolCloseReasonSchema,
  R as WorkerTranscriptCommitRequestFrameSchema,
  S as WorkerHeartbeatParamsSchema,
  V as WorkerTranscriptMessageSchema,
  _ as WorkerAdmissionHandshakeSchema,
  a as WORKER_PROTOCOL_MAX_FEATURE_LENGTH,
  b as WorkerConnectRequestFrameSchema,
  c as WORKER_PROTOCOL_MAX_METHOD_LENGTH,
  d as WORKER_RPC_SET_VERSION,
  f as WORKER_TRANSCRIPT_COMMIT_PROTOCOL_FEATURE,
  g as WorkerAdmissionFailureReasonSchema,
  h as WORKER_TRANSCRIPT_MAX_JSON_DEPTH,
  i as WORKER_PROTOCOL_MAX_FEATURES,
  j as WorkerLiveEventResponseFrameSchema,
  k as WorkerLiveEventParamsSchema,
  l as WORKER_PROTOCOL_MAX_PAYLOAD_BYTES,
  m as WORKER_TRANSCRIPT_MAX_CONTENT_PARTS,
  n as WORKER_LIVE_EVENT_PROTOCOL_FEATURE,
  o as WORKER_PROTOCOL_MAX_FRAME_ID_LENGTH,
  p as WORKER_TRANSCRIPT_MAX_BATCH_MESSAGES,
  r as WORKER_PROTOCOL_FEATURES,
  s as WORKER_PROTOCOL_MAX_IDENTIFIER_LENGTH,
  t as WORKER_HEARTBEAT_INTERVAL_MS,
  u as WORKER_PROTOCOL_METHODS,
  v as WorkerAdmissionResponseFrameSchema,
  w as WorkerHeartbeatResponseFrameSchema,
  z as WorkerTranscriptCommitResponseFrameSchema,
} from "../../worker-admission-BAoXlOyb.js";
import {
  A as validateWorkerInferenceTerminalOutcome,
  C as WorkerInferenceTerminalFrameSchema,
  D as validateWorkerInferenceEventFrame,
  E as validateWorkerInferenceCancelParams,
  O as validateWorkerInferenceStartParams,
  S as WorkerInferenceStartResultSchema,
  T as WorkerInferenceTerminalParamsSchema,
  _ as WorkerInferenceOptionsSchema,
  a as WORKER_INFERENCE_PROTOCOL_FEATURE,
  b as WorkerInferenceStartRequestFrameSchema,
  c as WorkerInferenceCancelRequestFrameSchema,
  d as WorkerInferenceContextSchema,
  f as WorkerInferenceErrorReasonSchema,
  g as WorkerInferenceModelRefSchema,
  h as WorkerInferenceEventParamsSchema,
  i as WORKER_INFERENCE_METHODS,
  k as validateWorkerInferenceTerminalFrame,
  l as WorkerInferenceCancelResponseFrameSchema,
  m as WorkerInferenceEventFrameSchema,
  n as WORKER_INFERENCE_MAX_OUTPUT_TOKENS,
  o as WORKER_PROTOCOL_MAX_INFERENCE_PAYLOAD_BYTES,
  p as WorkerInferenceErrorShapeSchema,
  r as WORKER_INFERENCE_MAX_TOOLS,
  s as WorkerInferenceCancelParamsSchema,
  t as WORKER_INFERENCE_MAX_CONTEXT_MESSAGES,
  u as WorkerInferenceCancelResultSchema,
  v as WorkerInferenceResolvedModelSchema,
  w as WorkerInferenceTerminalOutcomeSchema,
  x as WorkerInferenceStartResponseFrameSchema,
  y as WorkerInferenceStartParamsSchema,
} from "../../worker-inference-y83k6oxW.js";
export {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  AgentsWorkspaceEntrySchema,
  AgentsWorkspaceFileSchema,
  AgentsWorkspaceGetParamsSchema,
  AgentsWorkspaceGetResultSchema,
  AgentsWorkspaceListParamsSchema,
  AgentsWorkspaceListResultSchema,
  AllowedApprovalSnapshotSchema,
  ApprovalAllowDecisionSchema,
  ApprovalDecisionSchema,
  ApprovalGetParamsSchema,
  ApprovalGetResultSchema,
  ApprovalKindSchema,
  ApprovalPresentationSchema,
  ApprovalResolveParamsSchema,
  ApprovalResolveResultSchema,
  ApprovalSnapshotSchema,
  ApprovalTerminalReasonSchema,
  ArtifactSummarySchema,
  ArtifactsDownloadParamsSchema,
  ArtifactsGetParamsSchema,
  ArtifactsListParamsSchema,
  AuditActivityAgentRunV1Schema,
  AuditActivityEventV1Schema,
  AuditActivityInboundMessageV1Schema,
  AuditActivityListParamsSchema,
  AuditActivityListResultSchema,
  AuditActivityOutboundMessageV1Schema,
  AuditActivityToolActionV1Schema,
  AuditEventSchema,
  AuditListParamsSchema,
  AuditListResultSchema,
  AuthProbeStatusSchema,
  CancelledApprovalSnapshotSchema,
  ChannelsLogoutParamsSchema,
  ChannelsStartParamsSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  ChannelsStopParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatMetadataParamsSchema,
  ChatSendParamsSchema,
  ChatToolTitlesParamsSchema,
  ChatToolTitlesResultSchema,
  ClawHubTrustErrorCodes,
  CommandsListParamsSchema,
  CommandsListResultSchema,
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  ConnectParamsSchema,
  CrestodianChatParamsSchema,
  CrestodianChatResultSchema,
  CrestodianSetupActivateParamsSchema,
  CrestodianSetupActivateResultSchema,
  CrestodianSetupAuthStartParamsSchema,
  CrestodianSetupAuthStartResultSchema,
  CrestodianSetupDetectParamsSchema,
  CrestodianSetupDetectResultSchema,
  CrestodianSetupVerifyParamsSchema,
  CrestodianSetupVerifyResultSchema,
  CronAddParamsSchema,
  CronAddResultSchema,
  CronDeclarativeAddResultSchema,
  CronGetParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
  DeniedApprovalSnapshotSchema,
  EnvironmentStatusSchema,
  EnvironmentSummarySchema,
  EnvironmentsCreateParamsSchema,
  EnvironmentsCreateResultSchema,
  EnvironmentsDestroyParamsSchema,
  EnvironmentsDestroyResultSchema,
  EnvironmentsListParamsSchema,
  EnvironmentsListResultSchema,
  EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResultSchema,
  ErrorCodes,
  ErrorShapeSchema,
  EventFrameSchema,
  ExecApprovalGetParamsSchema,
  ExecApprovalPresentationSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
  ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExpiredApprovalSnapshotSchema,
  FsDirEntrySchema,
  FsListDirParamsSchema,
  FsListDirResultSchema,
  GATEWAY_SERVER_CAPS,
  GatewayFrameSchema,
  GatewaySuspendBlockerSchema,
  GatewaySuspendPrepareBusyResultSchema,
  GatewaySuspendPrepareParamsSchema,
  GatewaySuspendPrepareReadyResultSchema,
  GatewaySuspendPrepareResultSchema,
  GatewaySuspendResumeParamsSchema,
  GatewaySuspendResumeResultSchema,
  GatewaySuspendStatusParamsSchema,
  GatewaySuspendStatusReadyResultSchema,
  GatewaySuspendStatusResultSchema,
  GatewaySuspendStatusRunningResultSchema,
  GatewaySuspendTaskBlockerSchema,
  HelloOkSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
  MAX_MEMORY_MIGRATION_ITEMS,
  MIN_CLIENT_PROTOCOL_VERSION,
  MIN_NODE_PROTOCOL_VERSION,
  MIN_PROBE_PROTOCOL_VERSION,
  MemoryMigrationItemSchema,
  MemoryMigrationItemStatusSchema,
  MemoryMigrationProviderPlanSchema,
  MemoryMigrationSummarySchema,
  MessageActionParamsSchema,
  MigrationProtocolSchemas,
  MigrationsMemoryApplyParamsSchema,
  MigrationsMemoryApplyResultSchema,
  MigrationsMemoryPlanParamsSchema,
  MigrationsMemoryPlanResultSchema,
  ModelsListParamsSchema,
  ModelsProbeParamsSchema,
  ModelsProbeResultSchema,
  ModelsProbeTargetResultSchema,
  NodeEventResultSchema,
  NodeInvokeInputEventSchema,
  NodeInvokeParamsSchema,
  NodeInvokeProgressParamsSchema,
  NodeListParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRemoveParamsSchema,
  NodePendingAckParamsSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodePluginToolDescriptorSchema,
  NodePluginToolsUpdateParamsSchema,
  NodePresenceActivityPayloadSchema,
  NodePresenceAlivePayloadSchema,
  NodePresenceAliveReasonSchema,
  NodeSkillDescriptorSchema,
  NodeSkillsUpdateParamsSchema,
  PROTOCOL_VERSION,
  PendingApprovalSnapshotSchema,
  PluginApprovalPresentationSchema,
  PluginApprovalSeveritySchema,
  PluginCatalogEntrySchema,
  PluginCatalogInstallActionSchema,
  PluginSearchPackageSchema,
  PluginSearchResultEntrySchema,
  PluginsInstallParamsSchema,
  PluginsInstallResultSchema,
  PluginsListParamsSchema,
  PluginsListResultSchema,
  PluginsSearchParamsSchema,
  PluginsSearchResultSchema,
  PluginsSessionActionParamsSchema,
  PluginsSessionActionResultSchema,
  PluginsSetEnabledParamsSchema,
  PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResultSchema,
  PluginsUninstallParamsSchema,
  PluginsUninstallResultSchema,
  PollParamsSchema,
  PresenceEntrySchema,
  PushTestParamsSchema,
  PushTestResultSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  SendParamsSchema,
  SessionApprovalEventSchema,
  SessionApprovalReplaySchema,
  SessionCatalogCapabilitiesSchema,
  SessionCatalogDescriptorSchema,
  SessionCatalogHostSchema,
  SessionCatalogSchema,
  SessionCatalogSessionSchema,
  SessionCatalogTranscriptItemSchema,
  SessionDiffFileSchema,
  SessionDiffFileStatusSchema,
  SessionFileBrowserEntrySchema,
  SessionFileBrowserResultSchema,
  SessionFileEntrySchema,
  SessionFileKindSchema,
  SessionFileRelevanceSchema,
  SessionGroupSchema,
  SessionPlacementSchema,
  SessionPlacementStateSchema,
  SessionWorktreeInfoSchema,
  SessionsAbortParamsSchema,
  SessionsCatalogArchiveParamsSchema,
  SessionsCatalogArchiveResultSchema,
  SessionsCatalogContinueParamsSchema,
  SessionsCatalogContinueResultSchema,
  SessionsCatalogListParamsSchema,
  SessionsCatalogListResultSchema,
  SessionsCatalogReadParamsSchema,
  SessionsCatalogReadResultSchema,
  SessionsCleanupParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCreateParamsSchema,
  SessionsCreateResultSchema,
  SessionsDeleteParamsSchema,
  SessionsDescribeParamsSchema,
  SessionsDiffParamsSchema,
  SessionsDiffResultSchema,
  SessionsDispatchParamsSchema,
  SessionsDispatchResultSchema,
  SessionsFilesGetParamsSchema,
  SessionsFilesGetResultSchema,
  SessionsFilesListParamsSchema,
  SessionsFilesListResultSchema,
  SessionsFilesSetParamsSchema,
  SessionsFilesSetResultSchema,
  SessionsGroupsDeleteParamsSchema,
  SessionsGroupsListParamsSchema,
  SessionsGroupsListResultSchema,
  SessionsGroupsMutationResultSchema,
  SessionsGroupsPutParamsSchema,
  SessionsGroupsRenameParamsSchema,
  SessionsListParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPluginPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSearchHitSchema,
  SessionsSearchParamsSchema,
  SessionsSearchResultSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
  ShutdownEventSchema,
  SkillsCuratorActionParamsSchema,
  SkillsCuratorActionResultSchema,
  SkillsCuratorStatusParamsSchema,
  SkillsCuratorStatusResultSchema,
  SkillsDetailParamsSchema,
  SkillsDetailResultSchema,
  SkillsInstallParamsSchema,
  SkillsProposalActionParamsSchema,
  SkillsProposalApplyResultSchema,
  SkillsProposalCreateParamsSchema,
  SkillsProposalHistoryScanParamsSchema,
  SkillsProposalHistoryScanResultSchema,
  SkillsProposalHistoryStatusParamsSchema,
  SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResultSchema,
  SkillsProposalRecordResultSchema,
  SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResultSchema,
  SkillsProposalReviseParamsSchema,
  SkillsProposalUpdateParamsSchema,
  SkillsProposalsListParamsSchema,
  SkillsProposalsListResultSchema,
  SkillsSearchParamsSchema,
  SkillsSearchResultSchema,
  SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParamsSchema,
  SkillsSkillCardResultSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
  SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParamsSchema,
  SnapshotSchema,
  StateVersionSchema,
  SystemInfoParamsSchema,
  SystemInfoResultSchema,
  TalkAgentControlResultSchema,
  TalkCatalogParamsSchema,
  TalkCatalogResultSchema,
  TalkClientCreateParamsSchema,
  TalkClientCreateResultSchema,
  TalkClientSteerParamsSchema,
  TalkClientToolCallParamsSchema,
  TalkClientToolCallResultSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkEventSchema,
  TalkSessionAcknowledgeMarkParamsSchema,
  TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParamsSchema,
  TalkSessionCloseParamsSchema,
  TalkSessionCreateParamsSchema,
  TalkSessionCreateResultSchema,
  TalkSessionJoinParamsSchema,
  TalkSessionJoinResultSchema,
  TalkSessionOkResultSchema,
  TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParamsSchema,
  TalkSessionTurnParamsSchema,
  TalkSessionTurnResultSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  TaskSuggestionEventSchema,
  TaskSuggestionResolutionSchema,
  TaskSuggestionSchema,
  TaskSuggestionsAcceptParamsSchema,
  TaskSuggestionsAcceptResultSchema,
  TaskSuggestionsCreateParamsSchema,
  TaskSuggestionsCreateResultSchema,
  TaskSuggestionsDismissParamsSchema,
  TaskSuggestionsDismissResultSchema,
  TaskSuggestionsListParamsSchema,
  TaskSuggestionsListResultSchema,
  TaskSummarySchema,
  TasksCancelParamsSchema,
  TasksCancelResultSchema,
  TasksGetParamsSchema,
  TasksGetResultSchema,
  TasksListParamsSchema,
  TasksListResultSchema,
  TerminalAckResultSchema,
  TerminalApprovalSnapshotSchema,
  TerminalAttachParamsSchema,
  TerminalAttachResultSchema,
  TerminalCloseParamsSchema,
  TerminalDataEventSchema,
  TerminalEventSchema,
  TerminalExitEventSchema,
  TerminalInputParamsSchema,
  TerminalListResultSchema,
  TerminalOpenParamsSchema,
  TerminalOpenResultSchema,
  TerminalResizeParamsSchema,
  TerminalSessionInfoSchema,
  TerminalTextParamsSchema,
  TerminalTextResultSchema,
  TickEventSchema,
  ToolsCatalogParamsSchema,
  ToolsEffectiveParamsSchema,
  ToolsInvokeParamsSchema,
  TtsSpeakParamsSchema,
  TtsSpeakResultSchema,
  UpdateRunParamsSchema,
  UpdateStatusParamsSchema,
  WORKER_HEARTBEAT_INTERVAL_MS,
  WORKER_INFERENCE_MAX_CONTEXT_MESSAGES,
  WORKER_INFERENCE_MAX_OUTPUT_TOKENS,
  WORKER_INFERENCE_MAX_TOOLS,
  WORKER_INFERENCE_METHODS,
  WORKER_INFERENCE_PROTOCOL_FEATURE,
  WORKER_LIVE_EVENT_PROTOCOL_FEATURE,
  WORKER_PROTOCOL_FEATURES,
  WORKER_PROTOCOL_MAX_FEATURES,
  WORKER_PROTOCOL_MAX_FEATURE_LENGTH,
  WORKER_PROTOCOL_MAX_FRAME_ID_LENGTH,
  WORKER_PROTOCOL_MAX_IDENTIFIER_LENGTH,
  WORKER_PROTOCOL_MAX_INFERENCE_PAYLOAD_BYTES,
  WORKER_PROTOCOL_MAX_METHOD_LENGTH,
  WORKER_PROTOCOL_MAX_PAYLOAD_BYTES,
  WORKER_PROTOCOL_METHODS,
  WORKER_RPC_SET_VERSION,
  WORKER_TRANSCRIPT_COMMIT_PROTOCOL_FEATURE,
  WORKER_TRANSCRIPT_MAX_BATCH_MESSAGES,
  WORKER_TRANSCRIPT_MAX_CONTENT_PARTS,
  WORKER_TRANSCRIPT_MAX_JSON_DEPTH,
  WakeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
  WebPushSubscribeParamsSchema,
  WebPushTestParamsSchema,
  WebPushUnsubscribeParamsSchema,
  WebPushVapidPublicKeyParamsSchema,
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
  WorkerAdmissionFailureReasonSchema,
  WorkerAdmissionHandshakeSchema,
  WorkerAdmissionResponseFrameSchema,
  WorkerConnectRequestFrameSchema,
  WorkerEnvironmentMetadataSchema,
  WorkerEnvironmentStateSchema,
  WorkerHeartbeatParamsSchema,
  WorkerHeartbeatRequestFrameSchema,
  WorkerHeartbeatResponseFrameSchema,
  WorkerInferenceCancelParamsSchema,
  WorkerInferenceCancelRequestFrameSchema,
  WorkerInferenceCancelResponseFrameSchema,
  WorkerInferenceCancelResultSchema,
  WorkerInferenceContextSchema,
  WorkerInferenceErrorReasonSchema,
  WorkerInferenceErrorShapeSchema,
  WorkerInferenceEventFrameSchema,
  WorkerInferenceEventParamsSchema,
  WorkerInferenceModelRefSchema,
  WorkerInferenceOptionsSchema,
  WorkerInferenceResolvedModelSchema,
  WorkerInferenceStartParamsSchema,
  WorkerInferenceStartRequestFrameSchema,
  WorkerInferenceStartResponseFrameSchema,
  WorkerInferenceStartResultSchema,
  WorkerInferenceTerminalFrameSchema,
  WorkerInferenceTerminalOutcomeSchema,
  WorkerInferenceTerminalParamsSchema,
  WorkerLiveEventErrorDetailsSchema,
  WorkerLiveEventErrorShapeSchema,
  WorkerLiveEventParamsSchema,
  WorkerLiveEventRequestFrameSchema,
  WorkerLiveEventResponseFrameSchema,
  WorkerLiveEventResultSchema,
  WorkerLiveEventSchema,
  WorkerProtocolCloseReasonSchema,
  WorkerTranscriptCommitErrorReasonSchema,
  WorkerTranscriptCommitErrorShapeSchema,
  WorkerTranscriptCommitParamsSchema,
  WorkerTranscriptCommitRequestFrameSchema,
  WorkerTranscriptCommitResponseFrameSchema,
  WorkerTranscriptCommitResultSchema,
  WorkerTranscriptMessageSchema,
  WorkerTunnelStatusSchema,
  WorktreeBranchSchema,
  WorktreeRecordSchema,
  WorktreesBranchesParamsSchema,
  WorktreesBranchesResultSchema,
  WorktreesCreateParamsSchema,
  WorktreesGcParamsSchema,
  WorktreesGcResultSchema,
  WorktreesListParamsSchema,
  WorktreesListResultSchema,
  WorktreesRemoveParamsSchema,
  WorktreesRemoveResultSchema,
  WorktreesRestoreParamsSchema,
  buildClawHubTrustErrorDetails,
  errorShape,
  formatValidationErrors,
  isClawHubTrustErrorCode,
  isWellFormedApprovalId,
  readClawHubTrustErrorDetails,
  validateAgentIdentityParams,
  validateAgentParams,
  validateAgentWaitParams,
  validateAgentsCreateParams,
  validateAgentsDeleteParams,
  validateAgentsFilesGetParams,
  validateAgentsFilesListParams,
  validateAgentsFilesSetParams,
  validateAgentsListParams,
  validateAgentsUpdateParams,
  validateAgentsWorkspaceGetParams,
  validateAgentsWorkspaceListParams,
  validateAllowedApprovalSnapshot,
  validateApprovalAllowDecision,
  validateApprovalDecision,
  validateApprovalGetParams,
  validateApprovalGetResult,
  validateApprovalKind,
  validateApprovalPresentation,
  validateApprovalResolveParams,
  validateApprovalResolveResult,
  validateApprovalSnapshot,
  validateApprovalTerminalReason,
  validateArtifactsDownloadParams,
  validateArtifactsGetParams,
  validateArtifactsListParams,
  validateAuditActivityListParams,
  validateAuditListParams,
  validateCancelledApprovalSnapshot,
  validateChannelsLogoutParams,
  validateChannelsStartParams,
  validateChannelsStatusParams,
  validateChannelsStopParams,
  validateChatAbortParams,
  validateChatEvent,
  validateChatHistoryParams,
  validateChatInjectParams,
  validateChatMessageGetParams,
  validateChatMessageGetResult,
  validateChatMetadataParams,
  validateChatSendParams,
  validateChatToolTitlesParams,
  validateCommandsListParams,
  validateConfigApplyParams,
  validateConfigGetParams,
  validateConfigPatchParams,
  validateConfigSchemaLookupParams,
  validateConfigSchemaLookupResult,
  validateConfigSchemaParams,
  validateConfigSetParams,
  validateConnectParams,
  validateCrestodianChatParams,
  validateCrestodianSetupActivateParams,
  validateCrestodianSetupAuthStartParams,
  validateCrestodianSetupDetectParams,
  validateCrestodianSetupVerifyParams,
  validateCronAddParams,
  validateCronGetParams,
  validateCronListParams,
  validateCronRemoveParams,
  validateCronRunParams,
  validateCronRunsParams,
  validateCronStatusParams,
  validateCronUpdateParams,
  validateDeniedApprovalSnapshot,
  validateDevicePairApproveParams,
  validateDevicePairListParams,
  validateDevicePairRejectParams,
  validateDevicePairRemoveParams,
  validateDevicePairRenameParams,
  validateDevicePairSetupCodeParams,
  validateDeviceTokenRevokeParams,
  validateDeviceTokenRotateParams,
  validateEnvironmentsCreateParams,
  validateEnvironmentsDestroyParams,
  validateEnvironmentsListParams,
  validateEnvironmentsStatusParams,
  validateEventFrame,
  validateExecApprovalGetParams,
  validateExecApprovalPresentation,
  validateExecApprovalRequestParams,
  validateExecApprovalResolveParams,
  validateExecApprovalsGetParams,
  validateExecApprovalsNodeGetParams,
  validateExecApprovalsNodeSetParams,
  validateExecApprovalsNodeSnapshot,
  validateExecApprovalsSetParams,
  validateExpiredApprovalSnapshot,
  validateFsListDirParams,
  validateFsListDirResult,
  validateGatewaySuspendPrepareParams,
  validateGatewaySuspendPrepareResult,
  validateGatewaySuspendResumeParams,
  validateGatewaySuspendResumeResult,
  validateGatewaySuspendStatusParams,
  validateGatewaySuspendStatusResult,
  validateLogsTailParams,
  validateMessageActionParams,
  validateMigrationsMemoryApplyParams,
  validateMigrationsMemoryPlanParams,
  validateModelsListParams,
  validateModelsProbeParams,
  validateNodeDescribeParams,
  validateNodeEventParams,
  validateNodeEventResult,
  validateNodeInvokeInputEvent,
  validateNodeInvokeParams,
  validateNodeInvokeProgressParams,
  validateNodeInvokeResultParams,
  validateNodeListParams,
  validateNodePairApproveParams,
  validateNodePairListParams,
  validateNodePairRejectParams,
  validateNodePairRemoveParams,
  validateNodePendingAckParams,
  validateNodePendingDrainParams,
  validateNodePendingEnqueueParams,
  validateNodePluginToolsUpdateParams,
  validateNodePresenceActivityPayload,
  validateNodePresenceAlivePayload,
  validateNodeRenameParams,
  validateNodeSkillsUpdateParams,
  validatePendingApprovalSnapshot,
  validatePluginApprovalPresentation,
  validatePluginApprovalRequestParams,
  validatePluginApprovalResolveParams,
  validatePluginApprovalSeverity,
  validatePluginsInstallParams,
  validatePluginsInstallResult,
  validatePluginsListParams,
  validatePluginsListResult,
  validatePluginsSearchParams,
  validatePluginsSearchResult,
  validatePluginsSessionActionParams,
  validatePluginsSessionActionResult,
  validatePluginsSetEnabledParams,
  validatePluginsSetEnabledResult,
  validatePluginsUiDescriptorsParams,
  validatePluginsUiDescriptorsResult,
  validatePluginsUninstallParams,
  validatePluginsUninstallResult,
  validatePollParams,
  validatePushTestParams,
  validateRequestFrame,
  validateResponseFrame,
  validateSecretsResolveParams,
  validateSecretsResolveResult,
  validateSendParams,
  validateSessionsAbortParams,
  validateSessionsCatalogArchiveParams,
  validateSessionsCatalogContinueParams,
  validateSessionsCatalogListParams,
  validateSessionsCatalogReadParams,
  validateSessionsCleanupParams,
  validateSessionsCompactParams,
  validateSessionsCompactionBranchParams,
  validateSessionsCompactionGetParams,
  validateSessionsCompactionListParams,
  validateSessionsCompactionRestoreParams,
  validateSessionsCreateParams,
  validateSessionsDeleteParams,
  validateSessionsDescribeParams,
  validateSessionsDiffParams,
  validateSessionsDispatchParams,
  validateSessionsDispatchResult,
  validateSessionsFilesGetParams,
  validateSessionsFilesListParams,
  validateSessionsFilesSetParams,
  validateSessionsGroupsDeleteParams,
  validateSessionsGroupsListParams,
  validateSessionsGroupsPutParams,
  validateSessionsGroupsRenameParams,
  validateSessionsListParams,
  validateSessionsMessagesSubscribeParams,
  validateSessionsMessagesUnsubscribeParams,
  validateSessionsPatchParams,
  validateSessionsPluginPatchParams,
  validateSessionsPreviewParams,
  validateSessionsResetParams,
  validateSessionsResolveParams,
  validateSessionsSearchParams,
  validateSessionsSearchResult,
  validateSessionsSendParams,
  validateSessionsUsageParams,
  validateSkillsBinsParams,
  validateSkillsCuratorActionParams,
  validateSkillsCuratorStatusParams,
  validateSkillsDetailParams,
  validateSkillsInstallParams,
  validateSkillsProposalActionParams,
  validateSkillsProposalCreateParams,
  validateSkillsProposalHistoryScanParams,
  validateSkillsProposalHistoryStatusParams,
  validateSkillsProposalInspectParams,
  validateSkillsProposalRequestRevisionParams,
  validateSkillsProposalReviseParams,
  validateSkillsProposalUpdateParams,
  validateSkillsProposalsListParams,
  validateSkillsSearchParams,
  validateSkillsSecurityVerdictsParams,
  validateSkillsSkillCardParams,
  validateSkillsStatusParams,
  validateSkillsUpdateParams,
  validateSkillsUploadBeginParams,
  validateSkillsUploadChunkParams,
  validateSkillsUploadCommitParams,
  validateSystemInfoParams,
  validateSystemInfoResult,
  validateTalkAgentControlResult,
  validateTalkCatalogParams,
  validateTalkCatalogResult,
  validateTalkClientCreateParams,
  validateTalkClientCreateResult,
  validateTalkClientSteerParams,
  validateTalkClientToolCallParams,
  validateTalkClientToolCallResult,
  validateTalkConfigParams,
  validateTalkConfigResult,
  validateTalkEvent,
  validateTalkModeParams,
  validateTalkSessionAcknowledgeMarkParams,
  validateTalkSessionAppendAudioParams,
  validateTalkSessionCancelOutputParams,
  validateTalkSessionCancelTurnParams,
  validateTalkSessionCloseParams,
  validateTalkSessionCreateParams,
  validateTalkSessionCreateResult,
  validateTalkSessionJoinParams,
  validateTalkSessionJoinResult,
  validateTalkSessionOkResult,
  validateTalkSessionSteerParams,
  validateTalkSessionSubmitToolResultParams,
  validateTalkSessionTurnParams,
  validateTalkSessionTurnResult,
  validateTalkSpeakParams,
  validateTalkSpeakResult,
  validateTaskSuggestionsAcceptParams,
  validateTaskSuggestionsCreateParams,
  validateTaskSuggestionsDismissParams,
  validateTaskSuggestionsListParams,
  validateTasksCancelParams,
  validateTasksGetParams,
  validateTasksListParams,
  validateTerminalApprovalSnapshot,
  validateTerminalAttachParams,
  validateTerminalCloseParams,
  validateTerminalEvent,
  validateTerminalInputParams,
  validateTerminalOpenParams,
  validateTerminalResizeParams,
  validateTerminalTextParams,
  validateToolsCatalogParams,
  validateToolsEffectiveParams,
  validateToolsInvokeParams,
  validateTtsSpeakParams,
  validateTtsSpeakResult,
  validateUpdateRunParams,
  validateUpdateStatusParams,
  validateWakeParams,
  validateWebLoginStartParams,
  validateWebLoginWaitParams,
  validateWebPushSubscribeParams,
  validateWebPushTestParams,
  validateWebPushUnsubscribeParams,
  validateWebPushVapidPublicKeyParams,
  validateWizardCancelParams,
  validateWizardNextParams,
  validateWizardStartParams,
  validateWizardStatusParams,
  validateWorkerAdmissionHandshake,
  validateWorkerConnectRequestFrame,
  validateWorkerHeartbeatParams,
  validateWorkerInferenceCancelParams,
  validateWorkerInferenceEventFrame,
  validateWorkerInferenceStartParams,
  validateWorkerInferenceTerminalFrame,
  validateWorkerInferenceTerminalOutcome,
  validateWorkerLiveEventParams,
  validateWorkerTranscriptCommitParams,
  validateWorktreesBranchesParams,
  validateWorktreesCreateParams,
  validateWorktreesGcParams,
  validateWorktreesListParams,
  validateWorktreesRemoveParams,
  validateWorktreesRestoreParams,
};
