import {
  $ as validateCrestodianSetupAuthStartParams,
  $_ as WorkerInferenceTerminalParams,
  $a as PluginsInstallResult,
  $c as NodeSkillDescriptorSchema,
  $d as ConfigSchemaParamsSchema,
  $f as TalkSessionCloseParams,
  $g as MigrationsMemoryPlanParams,
  $h as SkillsSecurityVerdictsResult,
  $i as validateWorkerTranscriptCommitParams,
  $l as ExecApprovalRequestParamsSchema,
  $m as AuthProbeStatusSchema,
  $n as validateSessionsDispatchParams,
  $o as TaskSummary,
  $p as ArtifactsDownloadParams,
  $r as validateTalkModeParams,
  $s as PushTestParamsSchema,
  $t as validateNodeListParams,
  $u as TickEvent,
  $v as WorkerProtocolCloseReason,
  $y as SessionApprovalEvent,
  A as validateChannelsStartParams,
  A_ as WorkerInferenceErrorShapeSchema,
  Aa as WizardCancelParams,
  Ac as NodePairRejectParamsSchema,
  Ad as CrestodianSetupActivateResult,
  Af as TalkCatalogResultSchema,
  Ag as AgentParamsSchema,
  Ah as SkillsProposalInspectParamsSchema,
  Ai as validateTerminalTextParams,
  Al as GatewaySuspendStatusParams,
  Am as AgentsFileEntry,
  An as validatePluginsUninstallResult,
  Ao as TerminalCloseParamsSchema,
  Ap as WebLoginWaitParamsSchema,
  Ar as validateSkillsProposalUpdateParams,
  As as TaskSuggestionsDismissResultSchema,
  At as validateExecApprovalsNodeSetParams,
  Au as WorkerEnvironmentState,
  Av as WorkerErrorShape,
  Ay as ApprovalPresentationSchema,
  B as validateChatSendParams,
  B_ as WorkerInferenceResolvedModelSchema,
  Ba as WizardStatusParams,
  Bc as NodePendingEnqueueResult,
  Bd as CrestodianSetupVerifyParams,
  Bf as TalkClientToolCallResultSchema,
  Bg as MAX_MEMORY_MIGRATION_ITEMS,
  Bh as SkillsProposalReviseParamsSchema,
  Bi as validateWebLoginWaitParams,
  Bl as FsListDirParams,
  Bm as AgentsFilesSetParams,
  Bn as validateSessionsCatalogContinueParams,
  Bo as TerminalListResultSchema,
  Bp as AuditActivityEventV1Schema,
  Br as validateSystemInfoParams,
  Bs as PresenceEntrySchema,
  Bt as validateGatewaySuspendStatusParams,
  Bu as EventFrame,
  Bv as WorkerLiveEventErrorDetails,
  By as CancelledApprovalSnapshotSchema,
  C as validateArtifactsDownloadParams,
  C_ as WorkerInferenceCancelResult,
  Ca as WorktreesListResultSchema,
  Cc as NodeListParams,
  Cd as CronUpdateParamsSchema,
  Cf as ChannelsStopParams,
  Cg as ToolsInvokeResult,
  Ch as SkillsProposalActionParams,
  Ci as validateTerminalApprovalSnapshot,
  Cl as GatewaySuspendPrepareReadyResultSchema,
  Cm as AgentsCreateParamsSchema,
  Cn as validatePluginsSessionActionParams,
  Co as TerminalAckResult,
  Cp as TtsSpeakParams,
  Cr as validateSkillsDetailParams,
  Cs as TaskSuggestionsCreateParams,
  Ct as validateEventFrame,
  Cu as EnvironmentsListResultSchema,
  Cv as WorkerAdmissionHandshake,
  Cy as ApprovalGetParams,
  D as validateAuditListParams,
  D_ as WorkerInferenceErrorReason,
  Da as WorktreesRemoveResultSchema,
  Dc as NodePairListParams,
  Dd as CrestodianChatResultSchema,
  Df as TalkCatalogParams,
  Dg as AgentIdentityParamsSchema,
  Dh as SkillsProposalCreateParams,
  Di as validateTerminalInputParams,
  Dl as GatewaySuspendResumeParamsSchema,
  Dm as AgentsDeleteParamsSchema,
  Dn as validatePluginsUiDescriptorsParams,
  Do as TerminalAttachResult,
  Dp as WebLoginStartParams,
  Dr as validateSkillsProposalInspectParams,
  Ds as TaskSuggestionsDismissParams,
  Dt as validateExecApprovalResolveParams,
  Du as EnvironmentsStatusResultSchema,
  Dv as WorkerConnectParams,
  Dy as ApprovalKind,
  E as validateAuditActivityListParams,
  E_ as WorkerInferenceContextSchema,
  Ea as WorktreesRemoveResult,
  Ec as NodePairApproveParamsSchema,
  Ed as CrestodianChatResult,
  Ef as TalkAgentControlResultSchema,
  Eg as AgentIdentityParams,
  Eh as SkillsProposalApplyResultSchema,
  Ei as validateTerminalEvent,
  El as GatewaySuspendResumeParams,
  Em as AgentsDeleteParams,
  En as validatePluginsSetEnabledResult,
  Eo as TerminalAttachParamsSchema,
  Ep as TtsSpeakResultSchema,
  Er as validateSkillsProposalCreateParams,
  Es as TaskSuggestionsCreateResultSchema,
  Et as validateExecApprovalRequestParams,
  Eu as EnvironmentsStatusResult,
  Ev as WorkerAdmissionResponseFrameSchema,
  Ey as ApprovalGetResultSchema,
  F as validateChatHistoryParams,
  F_ as WorkerInferenceModelRef,
  Fa as WizardNextResultSchema,
  Fc as NodePendingDrainParamsSchema,
  Fd as CrestodianSetupAuthStartResultSchema,
  Ff as TalkClientSteerParams,
  Fg as SendParamsSchema,
  Fh as SkillsProposalRequestRevisionParams,
  Fi as validateTtsSpeakResult,
  Fl as GatewaySuspendStatusRunningResultSchema,
  Fm as AgentsFilesGetResultSchema,
  Fn as validateSecretsResolveParams,
  Fo as TerminalExitEvent,
  Fp as AuditListResult,
  Fr as validateSkillsStatusParams,
  Fs as SystemInfoParams,
  Ft as validateFsListDirResult,
  Fu as errorShape,
  Fv as WorkerHeartbeatResponseFrame,
  Fy as ApprovalSnapshot,
  G as validateConfigPatchParams,
  G_ as WorkerInferenceStartResponseFrame,
  Ga as WizardStepSchema,
  Gc as NodePluginToolsUpdateParamsSchema,
  Gd as ConfigApplyParamsSchema,
  Gf as TalkEventSchema,
  Gg as MemoryMigrationProviderPlan,
  Gh as SkillsProposalsListResult,
  Gi as validateWizardCancelParams,
  Gl as DevicePairListParams,
  Gm as AgentsListParamsSchema,
  Gn as validateSessionsCompactionBranchParams,
  Go as TerminalResizeParams,
  Gp as AuditActivityListResult,
  Gr as validateTalkClientCreateParams,
  Gs as SessionPlacement,
  Gt as validateModelsProbeParams,
  Gu as HelloOk,
  Gv as WorkerLiveEventParamsSchema,
  Gy as ExpiredApprovalSnapshot,
  H as validateCommandsListParams,
  H_ as WorkerInferenceStartParamsSchema,
  Ha as WizardStatusResult,
  Hc as NodePluginToolDescriptor,
  Hd as CrestodianSetupVerifyResult,
  Hf as TalkConfigParamsSchema,
  Hg as MemoryMigrationItemSchema,
  Hh as SkillsProposalUpdateParamsSchema,
  Hi as validateWebPushTestParams,
  Hl as FsListDirResult,
  Hm as AgentsFilesSetResult,
  Hn as validateSessionsCatalogReadParams,
  Ho as TerminalOpenParamsSchema,
  Hp as AuditActivityInboundMessageV1Schema,
  Hr as validateTalkAgentControlResult,
  Hs as SnapshotSchema,
  Ht as validateLogsTailParams,
  Hu as GATEWAY_SERVER_CAPS,
  Hv as WorkerLiveEventErrorShape,
  Hy as DeniedApprovalSnapshotSchema,
  I as validateChatInjectParams,
  I_ as WorkerInferenceModelRefSchema,
  Ia as WizardStartParams,
  Ic as NodePendingDrainResult,
  Id as CrestodianSetupDetectParams,
  If as TalkClientSteerParamsSchema,
  Ig as WakeParams,
  Ih as SkillsProposalRequestRevisionParamsSchema,
  Ii as validateUpdateRunParams,
  Il as GatewaySuspendTaskBlocker,
  Im as AgentsFilesListParams,
  In as validateSecretsResolveResult,
  Io as TerminalExitEventSchema,
  Ip as AuditListResultSchema,
  Ir as validateSkillsUpdateParams,
  Is as SystemInfoParamsSchema,
  It as validateGatewaySuspendPrepareParams,
  Iu as ConnectParams,
  Iv as WorkerHeartbeatResponseFrameSchema,
  Iy as ApprovalSnapshotSchema,
  J as validateConfigSchemaParams,
  J_ as WorkerInferenceStartResultSchema,
  Ja as PluginCatalogInstallActionSchema,
  Jc as NodePresenceAlivePayload,
  Jd as ConfigPatchParams,
  Jf as TalkSessionAppendAudioParamsSchema,
  Jg as MigrationProtocolSchemas,
  Jh as SkillsSearchParamsSchema,
  Ji as validateWizardStatusParams,
  Jl as DevicePairSetupCodeParams,
  Jm as AgentsUpdateParams,
  Jn as validateSessionsCompactionRestoreParams,
  Jo as TerminalSessionInfoSchema,
  Jp as AuditActivityOutboundMessageV1Schema,
  Jr as validateTalkClientToolCallParams,
  Js as SessionPlacementStateSchema,
  Jt as validateNodeEventResult,
  Ju as RequestFrameSchema,
  Jv as WorkerLiveEventResponseFrame,
  Jy as PendingApprovalSnapshotSchema,
  K as validateConfigSchemaLookupParams,
  K_ as WorkerInferenceStartResponseFrameSchema,
  Ka as PluginCatalogEntry,
  Kc as NodePresenceActivityPayload,
  Kd as ConfigGetParams,
  Kf as TalkModeParams,
  Kg as MemoryMigrationProviderPlanSchema,
  Kh as SkillsProposalsListResultSchema,
  Ki as validateWizardNextParams,
  Kl as DevicePairRejectParams,
  Km as AgentsListResult,
  Kn as validateSessionsCompactionGetParams,
  Ko as TerminalResizeParamsSchema,
  Kp as AuditActivityListResultSchema,
  Kr as validateTalkClientCreateResult,
  Ks as SessionPlacementSchema,
  Kt as validateNodeDescribeParams,
  Ku as HelloOkSchema,
  Kv as WorkerLiveEventRequestFrame,
  Ky as ExpiredApprovalSnapshotSchema,
  L as validateChatMessageGetParams,
  L_ as WorkerInferenceOptions,
  La as WizardStartParamsSchema,
  Lc as NodePendingDrainResultSchema,
  Ld as CrestodianSetupDetectParamsSchema,
  Lf as TalkClientToolCallParams,
  Lg as WakeParamsSchema,
  Lh as SkillsProposalRequestRevisionResult,
  Li as validateUpdateStatusParams,
  Ll as GatewaySuspendTaskBlockerSchema,
  Lm as AgentsFilesListParamsSchema,
  Ln as validateSendParams,
  Lo as TerminalInputParams,
  Lp as AuditActivityAgentRunV1,
  Lr as validateSkillsUploadBeginParams,
  Ls as SystemInfoResult,
  Lt as validateGatewaySuspendPrepareResult,
  Lu as ConnectParamsSchema,
  Lv as WorkerHeartbeatResult,
  Ly as ApprovalTerminalReason,
  M as validateChannelsStopParams,
  M_ as WorkerInferenceEventFrameSchema,
  Ma as WizardNextParams,
  Mc as NodePairRemoveParamsSchema,
  Md as CrestodianSetupAuthStartParams,
  Mf as TalkClientCreateParamsSchema,
  Mg as MessageActionParamsSchema,
  Mh as SkillsProposalInspectResultSchema,
  Mi as validateToolsEffectiveParams,
  Ml as GatewaySuspendStatusReadyResultSchema,
  Mm as AgentsFilesGetParams,
  Mn as validatePushTestParams,
  Mo as TerminalDataEventSchema,
  Mp as AuditEventSchema,
  Mr as validateSkillsSearchParams,
  Ms as TaskSuggestionsListParamsSchema,
  Mt as validateExecApprovalsSetParams,
  Mu as WorkerTunnelStatus,
  Mv as WorkerHeartbeatParamsSchema,
  My as ApprovalResolveParamsSchema,
  N as validateChatAbortParams,
  N_ as WorkerInferenceEventParams,
  Na as WizardNextParamsSchema,
  Nc as NodePendingAckParamsSchema,
  Nd as CrestodianSetupAuthStartParamsSchema,
  Nf as TalkClientCreateResult,
  Ng as PollParams,
  Nh as SkillsProposalRecordResult,
  Ni as validateToolsInvokeParams,
  Nl as GatewaySuspendStatusResult,
  Nm as AgentsFilesGetParamsSchema,
  Nn as validateRequestFrame,
  No as TerminalEvent,
  Np as AuditListParams,
  Nr as validateSkillsSecurityVerdictsParams,
  Ns as TaskSuggestionsListResult,
  Nt as validateExpiredApprovalSnapshot,
  Nu as WorkerTunnelStatusSchema,
  Nv as WorkerHeartbeatRequestFrame,
  Ny as ApprovalResolveResult,
  O as validateCancelledApprovalSnapshot,
  O_ as WorkerInferenceErrorReasonSchema,
  Oa as WorktreesRestoreParams,
  Oc as NodePairListParamsSchema,
  Od as CrestodianSetupActivateParams,
  Of as TalkCatalogParamsSchema,
  Og as AgentIdentityResult,
  Oh as SkillsProposalCreateParamsSchema,
  Oi as validateTerminalOpenParams,
  Ol as GatewaySuspendResumeResult,
  Om as AgentsDeleteResult,
  On as validatePluginsUiDescriptorsResult,
  Oo as TerminalAttachResultSchema,
  Op as WebLoginStartParamsSchema,
  Or as validateSkillsProposalRequestRevisionParams,
  Os as TaskSuggestionsDismissParamsSchema,
  Ot as validateExecApprovalsGetParams,
  Ou as WorkerEnvironmentMetadata,
  Ov as WorkerConnectRequestFrame,
  Oy as ApprovalKindSchema,
  P as validateChatEvent,
  P_ as WorkerInferenceEventParamsSchema,
  Pa as WizardNextResult,
  Pc as NodePendingDrainParams,
  Pd as CrestodianSetupAuthStartResult,
  Pf as TalkClientCreateResultSchema,
  Pg as PollParamsSchema,
  Ph as SkillsProposalRecordResultSchema,
  Pi as validateTtsSpeakParams,
  Pl as GatewaySuspendStatusResultSchema,
  Pm as AgentsFilesGetResult,
  Pn as validateResponseFrame,
  Po as TerminalEventSchema,
  Pp as AuditListParamsSchema,
  Pr as validateSkillsSkillCardParams,
  Ps as TaskSuggestionsListResultSchema,
  Pt as validateFsListDirParams,
  Pu as ErrorCodes,
  Pv as WorkerHeartbeatRequestFrameSchema,
  Py as ApprovalResolveResultSchema,
  Q as validateCrestodianSetupActivateParams,
  Q_ as WorkerInferenceTerminalOutcomeSchema,
  Qa as PluginsInstallParamsSchema,
  Qc as NodeSkillDescriptor,
  Qd as ConfigSchemaParams,
  Qf as TalkSessionCancelTurnParamsSchema,
  Qg as MigrationsMemoryApplyResultSchema,
  Qh as SkillsSecurityVerdictsParamsSchema,
  Qi as validateWorkerLiveEventParams,
  Ql as ExecApprovalRequestParams,
  Qm as AuthProbeStatus,
  Qn as validateSessionsDiffParams,
  Qo as TerminalTextResultSchema,
  Qp as ArtifactSummarySchema,
  Qr as validateTalkEvent,
  Qs as SessionsDispatchResultSchema,
  Qt as validateNodeInvokeResultParams,
  Qu as ShutdownEventSchema,
  Qv as WorkerLiveEventSchema,
  Qy as PluginApprovalSeveritySchema,
  R as validateChatMessageGetResult,
  R_ as WorkerInferenceOptionsSchema,
  Ra as WizardStartResult,
  Rc as NodePendingEnqueueParams,
  Rd as CrestodianSetupDetectResult,
  Rf as TalkClientToolCallParamsSchema,
  Rg as validateMigrationsMemoryApplyParams,
  Rh as SkillsProposalRequestRevisionResultSchema,
  Ri as validateWakeParams,
  Rl as FsDirEntry,
  Rm as AgentsFilesListResult,
  Rn as validateSessionsAbortParams,
  Ro as TerminalInputParamsSchema,
  Rp as AuditActivityAgentRunV1Schema,
  Rr as validateSkillsUploadChunkParams,
  Rs as SystemInfoResultSchema,
  Rt as validateGatewaySuspendResumeParams,
  Ru as ErrorShape,
  Rv as WorkerHelloOk,
  Ry as ApprovalTerminalReasonSchema,
  S as validateApprovalTerminalReason,
  S_ as WorkerInferenceCancelResponseFrameSchema,
  Sa as WorktreesListResult,
  Sc as NodeInvokeResultParams,
  Sd as CronUpdateParams,
  Sf as ChannelsStatusResultSchema,
  Sg as ToolsInvokeParamsSchema,
  Sh as SkillsInstallParamsSchema,
  Si as validateTasksListParams,
  Sl as GatewaySuspendPrepareParamsSchema,
  Sm as AgentsCreateParams,
  Sn as validatePluginsSearchResult,
  So as PluginsUninstallResultSchema,
  Sp as TalkSpeakResultSchema,
  Sr as validateSkillsCuratorStatusParams,
  Ss as TaskSuggestionsAcceptResultSchema,
  St as validateEnvironmentsStatusParams,
  Su as EnvironmentsListResult,
  Sv as WorkerAdmissionFailureReasonSchema,
  Sy as ApprovalDecisionSchema,
  T as validateArtifactsListParams,
  T_ as WorkerInferenceContext,
  Ta as WorktreesRemoveParamsSchema,
  Tc as NodePairApproveParams,
  Td as CrestodianChatParamsSchema,
  Tf as TalkAgentControlResult,
  Tg as AgentEventSchema,
  Th as SkillsProposalApplyResult,
  Ti as validateTerminalCloseParams,
  Tl as GatewaySuspendPrepareResultSchema,
  Tm as AgentsCreateResultSchema,
  Tn as validatePluginsSetEnabledParams,
  To as TerminalAttachParams,
  Tp as TtsSpeakResult,
  Tr as validateSkillsProposalActionParams,
  Ts as TaskSuggestionsCreateResult,
  Tt as validateExecApprovalPresentation,
  Tu as EnvironmentsStatusParamsSchema,
  Tv as WorkerAdmissionResponseFrame,
  Ty as ApprovalGetResult,
  U as validateConfigApplyParams,
  U_ as WorkerInferenceStartRequestFrame,
  Ua as WizardStatusResultSchema,
  Uc as NodePluginToolDescriptorSchema,
  Ud as CrestodianSetupVerifyResultSchema,
  Uf as TalkConfigResult,
  Ug as MemoryMigrationItemStatus,
  Uh as SkillsProposalsListParams,
  Ui as validateWebPushUnsubscribeParams,
  Ul as FsListDirResultSchema,
  Um as AgentsFilesSetResultSchema,
  Un as validateSessionsCleanupParams,
  Uo as TerminalOpenResult,
  Up as AuditActivityListParams,
  Ur as validateTalkCatalogParams,
  Us as StateVersion,
  Ut as validateMessageActionParams,
  Uu as GatewayFrame,
  Uv as WorkerLiveEventErrorShapeSchema,
  Uy as ExecApprovalPresentation,
  V as validateChatToolTitlesParams,
  V_ as WorkerInferenceStartParams,
  Va as WizardStatusParamsSchema,
  Vc as NodePendingEnqueueResultSchema,
  Vd as CrestodianSetupVerifyParamsSchema,
  Vf as TalkConfigParams,
  Vg as MemoryMigrationItem,
  Vh as SkillsProposalUpdateParams,
  Vi as validateWebPushSubscribeParams,
  Vl as FsListDirParamsSchema,
  Vm as AgentsFilesSetParamsSchema,
  Vn as validateSessionsCatalogListParams,
  Vo as TerminalOpenParams,
  Vp as AuditActivityInboundMessageV1,
  Vr as validateSystemInfoResult,
  Vs as Snapshot,
  Vt as validateGatewaySuspendStatusResult,
  Vu as EventFrameSchema,
  Vv as WorkerLiveEventErrorDetailsSchema,
  Vy as DeniedApprovalSnapshot,
  W as validateConfigGetParams,
  W_ as WorkerInferenceStartRequestFrameSchema,
  Wa as WizardStep,
  Wc as NodePluginToolsUpdateParams,
  Wd as ConfigApplyParams,
  Wf as TalkConfigResultSchema,
  Wg as MemoryMigrationItemStatusSchema,
  Wh as SkillsProposalsListParamsSchema,
  Wi as validateWebPushVapidPublicKeyParams,
  Wl as DevicePairApproveParams,
  Wm as AgentsListParams,
  Wn as validateSessionsCompactParams,
  Wo as TerminalOpenResultSchema,
  Wp as AuditActivityListParamsSchema,
  Wr as validateTalkCatalogResult,
  Ws as StateVersionSchema,
  Wt as validateModelsListParams,
  Wu as GatewayFrameSchema,
  Wv as WorkerLiveEventParams,
  Wy as ExecApprovalPresentationSchema,
  X as validateConnectParams,
  X_ as WorkerInferenceTerminalFrameSchema,
  Xa as PluginSearchResultEntrySchema,
  Xc as NodePresenceAliveReason,
  Xd as ConfigSchemaLookupParamsSchema,
  Xf as TalkSessionCancelOutputParamsSchema,
  Xg as MigrationsMemoryApplyParamsSchema,
  Xh as SkillsSearchResultSchema,
  Xi as validateWorkerConnectRequestFrame,
  Xl as ExecApprovalGetParams,
  Xm as AgentsUpdateResult,
  Xn as validateSessionsDeleteParams,
  Xo as TerminalTextParamsSchema,
  Xp as AuditActivityToolActionV1Schema,
  Xr as validateTalkConfigParams,
  Xs as SessionsDispatchParamsSchema,
  Xt as validateNodeInvokeParams,
  Xu as ResponseFrameSchema,
  Xv as WorkerLiveEventResult,
  Xy as PluginApprovalPresentationSchema,
  Y as validateConfigSetParams,
  Y_ as WorkerInferenceTerminalFrame,
  Ya as PluginSearchPackageSchema,
  Yc as NodePresenceAlivePayloadSchema,
  Yd as ConfigPatchParamsSchema,
  Yf as TalkSessionCancelOutputParams,
  Yg as MigrationsMemoryApplyParams,
  Yh as SkillsSearchResult,
  Yi as validateWorkerAdmissionHandshake,
  Yl as DevicePairSetupCodeResult,
  Ym as AgentsUpdateParamsSchema,
  Yn as validateSessionsCreateParams,
  Yo as TerminalTextParams,
  Yp as AuditActivityToolActionV1,
  Yr as validateTalkClientToolCallResult,
  Ys as SessionsDispatchParams,
  Yt as validateNodeInvokeInputEvent,
  Yu as ResponseFrame,
  Yv as WorkerLiveEventResponseFrameSchema,
  Yy as PluginApprovalPresentation,
  Z as validateCrestodianChatParams,
  Z_ as WorkerInferenceTerminalOutcome,
  Za as PluginsInstallParams,
  Zc as NodePresenceAliveReasonSchema,
  Zd as ConfigSchemaLookupResultSchema,
  Zf as TalkSessionCancelTurnParams,
  Zg as MigrationsMemoryApplyResult,
  Zh as SkillsSecurityVerdictsParams,
  Zi as validateWorkerHeartbeatParams,
  Zl as ExecApprovalGetParamsSchema,
  Zm as AgentsUpdateResultSchema,
  Zn as validateSessionsDescribeParams,
  Zo as TerminalTextResult,
  Zp as ArtifactSummary,
  Zr as validateTalkConfigResult,
  Zs as SessionsDispatchResult,
  Zt as validateNodeInvokeProgressParams,
  Zu as ShutdownEvent,
  Zv as WorkerLiveEventResultSchema,
  Zy as PluginApprovalSeverity,
  _ as validateApprovalGetParams,
  __ as WorkerInferenceCancelParams,
  _a as WorktreesGcParamsSchema,
  _c as NodeInvokeInputEventSchema,
  _d as CronRunParamsSchema,
  _f as ChannelsStartParams,
  _g as ToolsCatalogResult,
  _h as SkillsDetailParams,
  _i as validateTaskSuggestionsCreateParams,
  _l as LogsTailResultSchema,
  _m as AgentsWorkspaceListParamsSchema,
  _n as validatePluginsInstallParams,
  _o as PluginsUiDescriptorsParamsSchema,
  _p as TalkSessionTurnResult,
  _r as validateSessionsSearchResult,
  _s as TaskSuggestionResolutionSchema,
  _t as validateDeviceTokenRevokeParams,
  _u as EnvironmentsDestroyParamsSchema,
  _v as WORKER_TRANSCRIPT_COMMIT_PROTOCOL_FEATURE,
  _y as AllowedApprovalSnapshot,
  a as validateAgentsCreateParams,
  a_ as SkillsProposalHistoryScanResult,
  aa as validateWorktreesRestoreParams,
  ab as isWellFormedApprovalId,
  ac as WebPushUnsubscribeParams,
  ad as CronDeclarativeAddResult,
  af as UpdateRunParamsSchema,
  ag as SkillsStatusParams,
  ah as ModelsProbeTargetResult,
  ai as validateTalkSessionCreateParams,
  al as ChatInjectParams,
  am as ArtifactsListParams,
  an as validateNodePendingDrainParams,
  ao as PluginsSearchParams,
  ap as TalkSessionJoinParams,
  ar as validateSessionsGroupsListParams,
  as as TasksGetParams,
  at as validateCronRemoveParams,
  au as ExecApprovalsSetParams,
  av as validateWorkerInferenceTerminalOutcome,
  ay as WorkerTranscriptCommitParams,
  b as validateApprovalResolveParams,
  b_ as WorkerInferenceCancelRequestFrameSchema,
  ba as WorktreesListParams,
  bc as NodeInvokeProgressParams,
  bd as CronStatusParams,
  bf as ChannelsStatusParamsSchema,
  bg as ToolsEffectiveResult,
  bh as SkillsDetailResultSchema,
  bi as validateTasksCancelParams,
  bl as GatewaySuspendPrepareBusyResultSchema,
  bm as AgentSummary,
  bn as validatePluginsListResult,
  bo as PluginsUninstallParamsSchema,
  bp as TalkSpeakParamsSchema,
  br as validateSkillsBinsParams,
  bs as TaskSuggestionsAcceptParamsSchema,
  bt as validateEnvironmentsDestroyParams,
  bu as EnvironmentsListParams,
  bv as WORKER_TRANSCRIPT_MAX_JSON_DEPTH,
  by as ApprovalAllowDecisionSchema,
  c as validateAgentsFilesListParams,
  c_ as SkillsProposalHistoryStatusParamsSchema,
  ca as WorktreeRecord,
  cb as ClawHubTrustErrorDetails,
  cc as WebPushVapidPublicKeyParamsSchema,
  cd as CronGetParamsSchema,
  cf as CommandEntry,
  cg as SkillsUpdateParamsSchema,
  ch as SkillsBinsResult,
  ci as validateTalkSessionJoinResult,
  cl as ChatMetadataParamsSchema,
  cm as AgentsWorkspaceEntry,
  cn as validateNodePresenceActivityPayload,
  co as PluginsSearchResultSchema,
  cp as TalkSessionJoinResultSchema,
  cr as validateSessionsListParams,
  cs as TasksGetResultSchema,
  ct as validateCronStatusParams,
  cu as EnvironmentStatus,
  cv as WORKER_PROTOCOL_FEATURES,
  cy as WorkerTranscriptCommitRequestFrameSchema,
  d as validateAgentsUpdateParams,
  d_ as WORKER_INFERENCE_MAX_CONTEXT_MESSAGES,
  da as WorktreesBranchesParamsSchema,
  db as readClawHubTrustErrorDetails,
  dc as MIN_PROBE_PROTOCOL_VERSION,
  dd as CronListParams,
  df as CommandsListResult,
  dg as SkillsUploadChunkParams,
  dh as SkillsCuratorActionResult,
  di as validateTalkSessionSubmitToolResultParams,
  dl as ChatToolTitlesParamsSchema,
  dm as AgentsWorkspaceFileSchema,
  dn as validateNodeSkillsUpdateParams,
  do as PluginsSessionActionResult,
  dp as TalkSessionSteerParams,
  dr as validateSessionsPatchParams,
  ds as TasksListResult,
  dt as validateDevicePairApproveParams,
  du as EnvironmentSummarySchema,
  dv as WORKER_PROTOCOL_MAX_FRAME_ID_LENGTH,
  dy as WorkerTranscriptCommitResult,
  e_ as MigrationsMemoryPlanParamsSchema,
  ea as validateWorktreesBranchesParams,
  eb as SessionApprovalEventSchema,
  ec as PushTestResultSchema,
  ed as TickEventSchema,
  ef as ConfigSchemaResponse,
  eg as SkillsSecurityVerdictsResultSchema,
  eh as ModelsListParamsSchema,
  ei as validateTalkSessionAcknowledgeMarkParams,
  el as NodeSkillsUpdateParams,
  em as ArtifactsDownloadParamsSchema,
  en as validateNodePairApproveParams,
  eo as PluginsInstallResultSchema,
  ep as TalkSessionCloseParamsSchema,
  er as validateSessionsDispatchResult,
  es as TaskSummarySchema,
  et as validateCrestodianSetupDetectParams,
  eu as ExecApprovalResolveParams,
  ev as WorkerInferenceTerminalParamsSchema,
  ey as WorkerProtocolCloseReasonSchema,
  f as validateAgentsWorkspaceGetParams,
  f_ as WORKER_INFERENCE_MAX_OUTPUT_TOKENS,
  fa as WorktreesBranchesResult,
  fb as ProtocolValidator,
  fc as PROTOCOL_VERSION,
  fd as CronListParamsSchema,
  ff as CommandsListResultSchema,
  fg as SkillsUploadChunkParamsSchema,
  fh as SkillsCuratorActionResultSchema,
  fi as validateTalkSessionTurnParams,
  fl as ChatToolTitlesResult,
  fm as AgentsWorkspaceGetParams,
  fn as validatePendingApprovalSnapshot,
  fo as PluginsSessionActionResultSchema,
  fp as TalkSessionSteerParamsSchema,
  fr as validateSessionsPluginPatchParams,
  fs as TasksListResultSchema,
  ft as validateDevicePairListParams,
  fu as EnvironmentsCreateParams,
  fv as WORKER_PROTOCOL_MAX_IDENTIFIER_LENGTH,
  fy as WorkerTranscriptCommitResultSchema,
  g as validateApprovalDecision,
  g_ as WORKER_PROTOCOL_MAX_INFERENCE_PAYLOAD_BYTES,
  ga as WorktreesGcParams,
  gc as NodeInvokeInputEvent,
  gd as CronRunParams,
  gf as ChannelsLogoutParamsSchema,
  gg as ToolsCatalogParamsSchema,
  gh as SkillsCuratorStatusResultSchema,
  gi as validateTaskSuggestionsAcceptParams,
  gl as LogsTailResult,
  gm as AgentsWorkspaceListParams,
  gn as validatePluginApprovalSeverity,
  go as PluginsSetEnabledResultSchema,
  gp as TalkSessionTurnParamsSchema,
  gr as validateSessionsSearchParams,
  gs as TaskSuggestionResolution,
  gt as validateDevicePairSetupCodeParams,
  gu as EnvironmentsDestroyParams,
  gv as WORKER_RPC_SET_VERSION,
  gy as validateApprovalResolveResult,
  h as validateApprovalAllowDecision,
  h_ as WORKER_INFERENCE_PROTOCOL_FEATURE,
  ha as WorktreesCreateParamsSchema,
  hc as NodeEventResultSchema,
  hd as CronRunLogEntry,
  hf as ChannelsLogoutParams,
  hg as ToolsCatalogParams,
  hh as SkillsCuratorStatusResult,
  hi as validateTalkSpeakResult,
  hl as LogsTailParamsSchema,
  hm as AgentsWorkspaceGetResultSchema,
  hn as validatePluginApprovalResolveParams,
  ho as PluginsSetEnabledResult,
  hp as TalkSessionTurnParams,
  hr as validateSessionsResolveParams,
  hs as TaskSuggestionEventSchema,
  ht as validateDevicePairRenameParams,
  hu as EnvironmentsCreateResultSchema,
  hv as WORKER_PROTOCOL_METHODS,
  hy as validateApprovalGetResult,
  i as validateAgentWaitParams,
  i_ as SkillsProposalHistoryScanParamsSchema,
  ia as validateWorktreesRemoveParams,
  ib as TerminalApprovalSnapshotSchema,
  ic as WebPushTestParamsSchema,
  id as CronAddResultSchema,
  if as UpdateRunParams,
  ig as SkillsSkillCardResultSchema,
  ih as ModelsProbeResultSchema,
  ii as validateTalkSessionCloseParams,
  il as ChatHistoryParamsSchema,
  im as ArtifactsGetResult,
  in as validateNodePendingAckParams,
  io as PluginsListResultSchema,
  ip as TalkSessionCreateResultSchema,
  ir as validateSessionsGroupsDeleteParams,
  is as TasksCancelResultSchema,
  it as validateCronListParams,
  iu as ExecApprovalsNodeSnapshot,
  iv as validateWorkerInferenceTerminalFrame,
  iy as WorkerTranscriptCommitErrorShapeSchema,
  j as validateChannelsStatusParams,
  j_ as WorkerInferenceEventFrame,
  ja as WizardCancelParamsSchema,
  jc as NodePairRemoveParams,
  jd as CrestodianSetupActivateResultSchema,
  jf as TalkClientCreateParams,
  jg as AgentWaitParams,
  jh as SkillsProposalInspectResult,
  ji as validateToolsCatalogParams,
  jl as GatewaySuspendStatusParamsSchema,
  jm as AgentsFileEntrySchema,
  jn as validatePollParams,
  jo as TerminalDataEvent,
  jp as AuditEvent,
  jr as validateSkillsProposalsListParams,
  js as TaskSuggestionsListParams,
  jt as validateExecApprovalsNodeSnapshot,
  ju as WorkerEnvironmentStateSchema,
  jv as WorkerHeartbeatParams,
  jy as ApprovalResolveParams,
  k as validateChannelsLogoutParams,
  k_ as WorkerInferenceErrorShape,
  ka as WorktreesRestoreParamsSchema,
  kc as NodePairRejectParams,
  kd as CrestodianSetupActivateParamsSchema,
  kf as TalkCatalogResult,
  kg as AgentIdentityResultSchema,
  kh as SkillsProposalInspectParams,
  ki as validateTerminalResizeParams,
  kl as GatewaySuspendResumeResultSchema,
  km as AgentsDeleteResultSchema,
  kn as validatePluginsUninstallParams,
  ko as TerminalCloseParams,
  kp as WebLoginWaitParams,
  kr as validateSkillsProposalReviseParams,
  ks as TaskSuggestionsDismissResult,
  kt as validateExecApprovalsNodeGetParams,
  ku as WorkerEnvironmentMetadataSchema,
  kv as WorkerConnectRequestFrameSchema,
  ky as ApprovalPresentation,
  l as validateAgentsFilesSetParams,
  l_ as validateSkillsProposalHistoryScanParams,
  la as WorktreeRecordSchema,
  lb as buildClawHubTrustErrorDetails,
  lc as MIN_CLIENT_PROTOCOL_VERSION,
  ld as CronJob,
  lf as CommandsListParams,
  lg as SkillsUploadBeginParams,
  lh as SkillsCuratorActionParams,
  li as validateTalkSessionOkResult,
  ll as ChatSendParamsSchema,
  lm as AgentsWorkspaceEntrySchema,
  ln as validateNodePresenceAlivePayload,
  lo as PluginsSessionActionParams,
  lp as TalkSessionOkResult,
  lr as validateSessionsMessagesSubscribeParams,
  ls as TasksListParams,
  lt as validateCronUpdateParams,
  lu as EnvironmentStatusSchema,
  lv as WORKER_PROTOCOL_MAX_FEATURES,
  ly as WorkerTranscriptCommitResponseFrame,
  m as validateAllowedApprovalSnapshot,
  m_ as WORKER_INFERENCE_METHODS,
  ma as WorktreesCreateParams,
  mb as formatValidationErrors,
  mc as NodeEventResult,
  md as CronRemoveParamsSchema,
  mf as TalkSessionAcknowledgeMarkParamsSchema,
  mg as SkillsUploadCommitParamsSchema,
  mh as SkillsCuratorStatusParamsSchema,
  mi as validateTalkSpeakParams,
  ml as LogsTailParams,
  mm as AgentsWorkspaceGetResult,
  mn as validatePluginApprovalRequestParams,
  mo as PluginsSetEnabledParamsSchema,
  mp as TalkSessionSubmitToolResultParamsSchema,
  mr as validateSessionsResetParams,
  ms as TaskSuggestionEvent,
  mt as validateDevicePairRemoveParams,
  mu as EnvironmentsCreateResult,
  mv as WORKER_PROTOCOL_MAX_PAYLOAD_BYTES,
  my as WorkerTranscriptMessageSchema,
  n as validateAgentIdentityParams,
  n_ as MigrationsMemoryPlanResultSchema,
  na as validateWorktreesGcParams,
  nb as SessionApprovalReplaySchema,
  nc as WebPushSubscribeParamsSchema,
  nd as CronAddParamsSchema,
  nf as ConfigSetParams,
  ng as SkillsSkillCardParamsSchema,
  nh as ModelsProbeParamsSchema,
  ni as validateTalkSessionCancelOutputParams,
  nl as ChatEvent,
  nm as ArtifactsGetParams,
  nn as validateNodePairRejectParams,
  no as PluginsListParamsSchema,
  np as TalkSessionCreateParamsSchema,
  nr as validateSessionsFilesListParams,
  ns as TasksCancelParamsSchema,
  nt as validateCronAddParams,
  nu as ExecApprovalsGetParams,
  nv as validateWorkerInferenceEventFrame,
  ny as WorkerTranscriptCommitErrorReasonSchema,
  o as validateAgentsDeleteParams,
  o_ as SkillsProposalHistoryScanResultSchema,
  oa as WorktreeBranch,
  ob as ClawHubTrustErrorCode,
  oc as WebPushUnsubscribeParamsSchema,
  od as CronDeclarativeAddResultSchema,
  of as UpdateStatusParams,
  og as SkillsStatusParamsSchema,
  oh as ModelsProbeTargetResultSchema,
  oi as validateTalkSessionCreateResult,
  ol as ChatInjectParamsSchema,
  om as ArtifactsListParamsSchema,
  on as validateNodePendingEnqueueParams,
  oo as PluginsSearchParamsSchema,
  op as TalkSessionJoinParamsSchema,
  or as validateSessionsGroupsPutParams,
  os as TasksGetParamsSchema,
  ot as validateCronRunParams,
  ou as ExecApprovalsSetParamsSchema,
  ov as WORKER_HEARTBEAT_INTERVAL_MS,
  oy as WorkerTranscriptCommitParamsSchema,
  p as validateAgentsWorkspaceListParams,
  p_ as WORKER_INFERENCE_MAX_TOOLS,
  pa as WorktreesBranchesResultSchema,
  pb as ValidationError,
  pc as NodeEventParams,
  pd as CronRemoveParams,
  pf as TalkSessionAcknowledgeMarkParams,
  pg as SkillsUploadCommitParams,
  ph as SkillsCuratorStatusParams,
  pi as validateTalkSessionTurnResult,
  pl as ChatToolTitlesResultSchema,
  pm as AgentsWorkspaceGetParamsSchema,
  pn as validatePluginApprovalPresentation,
  po as PluginsSetEnabledParams,
  pp as TalkSessionSubmitToolResultParams,
  pr as validateSessionsPreviewParams,
  ps as TaskSuggestion,
  pt as validateDevicePairRejectParams,
  pu as EnvironmentsCreateParamsSchema,
  pv as WORKER_PROTOCOL_MAX_METHOD_LENGTH,
  py as WorkerTranscriptMessage,
  q as validateConfigSchemaLookupResult,
  q_ as WorkerInferenceStartResult,
  qa as PluginCatalogEntrySchema,
  qc as NodePresenceActivityPayloadSchema,
  qd as ConfigGetParamsSchema,
  qf as TalkSessionAppendAudioParams,
  qg as MemoryMigrationSummarySchema,
  qh as SkillsSearchParams,
  qi as validateWizardStartParams,
  ql as DevicePairRenameParams,
  qm as AgentsListResultSchema,
  qn as validateSessionsCompactionListParams,
  qo as TerminalSessionInfo,
  qp as AuditActivityOutboundMessageV1,
  qr as validateTalkClientSteerParams,
  qs as SessionPlacementState,
  qt as validateNodeEventParams,
  qu as RequestFrame,
  qv as WorkerLiveEventRequestFrameSchema,
  qy as PendingApprovalSnapshot,
  r as validateAgentParams,
  r_ as SkillsProposalHistoryScanParams,
  ra as validateWorktreesListParams,
  rb as TerminalApprovalSnapshot,
  rc as WebPushTestParams,
  rd as CronAddResult,
  rf as ConfigSetParamsSchema,
  rg as SkillsSkillCardResult,
  rh as ModelsProbeResult,
  ri as validateTalkSessionCancelTurnParams,
  rl as ChatEventSchema,
  rm as ArtifactsGetParamsSchema,
  rn as validateNodePairRemoveParams,
  ro as PluginsListResult,
  rp as TalkSessionCreateResult,
  rr as validateSessionsFilesSetParams,
  rs as TasksCancelResult,
  rt as validateCronGetParams,
  ru as ExecApprovalsGetParamsSchema,
  rv as validateWorkerInferenceStartParams,
  ry as WorkerTranscriptCommitErrorShape,
  s as validateAgentsFilesGetParams,
  s_ as SkillsProposalHistoryStatusParams,
  sa as WorktreeBranchSchema,
  sb as ClawHubTrustErrorCodes,
  sc as WebPushVapidPublicKeyParams,
  sd as CronGetParams,
  sf as UpdateStatusParamsSchema,
  sg as SkillsUpdateParams,
  sh as SkillsBinsParams,
  si as validateTalkSessionJoinParams,
  sl as ChatMetadataParams,
  sm as ArtifactsListResult,
  sn as validateNodePluginToolsUpdateParams,
  so as PluginsSearchResult,
  sp as TalkSessionJoinResult,
  sr as validateSessionsGroupsRenameParams,
  ss as TasksGetResult,
  st as validateCronRunsParams,
  su as ExecApprovalsSnapshot,
  sv as WORKER_LIVE_EVENT_PROTOCOL_FEATURE,
  sy as WorkerTranscriptCommitRequestFrame,
  t as SessionsPatchResult,
  t_ as MigrationsMemoryPlanResult,
  ta as validateWorktreesCreateParams,
  tb as SessionApprovalReplay,
  tc as WebPushSubscribeParams,
  td as CronAddParams,
  tf as ConfigSchemaResponseSchema,
  tg as SkillsSkillCardParams,
  th as ModelsProbeParams,
  ti as validateTalkSessionAppendAudioParams,
  tl as NodeSkillsUpdateParamsSchema,
  tm as ArtifactsDownloadResult,
  tn as validateNodePairListParams,
  to as PluginsListParams,
  tp as TalkSessionCreateParams,
  tr as validateSessionsFilesGetParams,
  ts as TasksCancelParams,
  tt as validateCrestodianSetupVerifyParams,
  tu as ExecApprovalResolveParamsSchema,
  tv as validateWorkerInferenceCancelParams,
  ty as WorkerTranscriptCommitErrorReason,
  u as validateAgentsListParams,
  u_ as validateSkillsProposalHistoryStatusParams,
  ua as WorktreesBranchesParams,
  ub as isClawHubTrustErrorCode,
  uc as MIN_NODE_PROTOCOL_VERSION,
  ud as CronJobSchema,
  uf as CommandsListParamsSchema,
  ug as SkillsUploadBeginParamsSchema,
  uh as SkillsCuratorActionParamsSchema,
  ui as validateTalkSessionSteerParams,
  ul as ChatToolTitlesParams,
  um as AgentsWorkspaceFile,
  un as validateNodeRenameParams,
  uo as PluginsSessionActionParamsSchema,
  up as TalkSessionOkResultSchema,
  ur as validateSessionsMessagesUnsubscribeParams,
  us as TasksListParamsSchema,
  ut as validateDeniedApprovalSnapshot,
  uu as EnvironmentSummary,
  uv as WORKER_PROTOCOL_MAX_FEATURE_LENGTH,
  uy as WorkerTranscriptCommitResponseFrameSchema,
  v as validateApprovalKind,
  v_ as WorkerInferenceCancelParamsSchema,
  va as WorktreesGcResult,
  vc as NodeInvokeParams,
  vd as CronRunsParams,
  vf as ChannelsStartParamsSchema,
  vg as ToolsEffectiveParams,
  vh as SkillsDetailParamsSchema,
  vi as validateTaskSuggestionsDismissParams,
  vl as GatewaySuspendBlocker,
  vm as AgentsWorkspaceListResult,
  vn as validatePluginsInstallResult,
  vo as PluginsUiDescriptorsResultSchema,
  vp as TalkSessionTurnResultSchema,
  vr as validateSessionsSendParams,
  vs as TaskSuggestionSchema,
  vt as validateDeviceTokenRotateParams,
  vu as EnvironmentsDestroyResult,
  vv as WORKER_TRANSCRIPT_MAX_BATCH_MESSAGES,
  vy as AllowedApprovalSnapshotSchema,
  w as validateArtifactsGetParams,
  w_ as WorkerInferenceCancelResultSchema,
  wa as WorktreesRemoveParams,
  wc as NodeListParamsSchema,
  wd as CrestodianChatParams,
  wf as ChannelsStopParamsSchema,
  wg as AgentEvent,
  wh as SkillsProposalActionParamsSchema,
  wi as validateTerminalAttachParams,
  wl as GatewaySuspendPrepareResult,
  wm as AgentsCreateResult,
  wn as validatePluginsSessionActionResult,
  wo as TerminalAckResultSchema,
  wp as TtsSpeakParamsSchema,
  wr as validateSkillsInstallParams,
  ws as TaskSuggestionsCreateParamsSchema,
  wt as validateExecApprovalGetParams,
  wu as EnvironmentsStatusParams,
  wv as WorkerAdmissionHandshakeSchema,
  wy as ApprovalGetParamsSchema,
  x as validateApprovalSnapshot,
  x_ as WorkerInferenceCancelResponseFrame,
  xa as WorktreesListParamsSchema,
  xc as NodeInvokeProgressParamsSchema,
  xd as CronStatusParamsSchema,
  xf as ChannelsStatusResult,
  xg as ToolsInvokeParams,
  xh as SkillsInstallParams,
  xi as validateTasksGetParams,
  xl as GatewaySuspendPrepareParams,
  xm as AgentSummarySchema,
  xn as validatePluginsSearchParams,
  xo as PluginsUninstallResult,
  xp as TalkSpeakResult,
  xr as validateSkillsCuratorActionParams,
  xs as TaskSuggestionsAcceptResult,
  xt as validateEnvironmentsListParams,
  xu as EnvironmentsListParamsSchema,
  xv as WorkerAdmissionFailureReason,
  xy as ApprovalDecision,
  y as validateApprovalPresentation,
  y_ as WorkerInferenceCancelRequestFrame,
  ya as WorktreesGcResultSchema,
  yc as NodeInvokeParamsSchema,
  yd as CronRunsParamsSchema,
  yf as ChannelsStatusParams,
  yg as ToolsEffectiveParamsSchema,
  yh as SkillsDetailResult,
  yi as validateTaskSuggestionsListParams,
  yl as GatewaySuspendBlockerSchema,
  ym as AgentsWorkspaceListResultSchema,
  yn as validatePluginsListParams,
  yo as PluginsUninstallParams,
  yp as TalkSpeakParams,
  yr as validateSessionsUsageParams,
  ys as TaskSuggestionsAcceptParams,
  yt as validateEnvironmentsCreateParams,
  yu as EnvironmentsDestroyResultSchema,
  yv as WORKER_TRANSCRIPT_MAX_CONTENT_PARTS,
  yy as ApprovalAllowDecision,
  z as validateChatMetadataParams,
  z_ as WorkerInferenceResolvedModel,
  za as WizardStartResultSchema,
  zc as NodePendingEnqueueParamsSchema,
  zd as CrestodianSetupDetectResultSchema,
  zf as TalkClientToolCallResult,
  zg as validateMigrationsMemoryPlanParams,
  zh as SkillsProposalReviseParams,
  zi as validateWebLoginStartParams,
  zl as FsDirEntrySchema,
  zm as AgentsFilesListResultSchema,
  zn as validateSessionsCatalogArchiveParams,
  zo as TerminalListResult,
  zp as AuditActivityEventV1,
  zr as validateSkillsUploadCommitParams,
  zs as PresenceEntry,
  zt as validateGatewaySuspendResumeResult,
  zu as ErrorShapeSchema,
  zv as WorkerLiveEvent,
  zy as CancelledApprovalSnapshot,
} from "../../index-F2ydESCy.js";
import {
  C as SessionsCatalogListResult,
  D as SessionsCatalogReadResult,
  E as SessionsCatalogReadParamsSchema,
  O as SessionsCatalogReadResultSchema,
  S as SessionsCatalogListParamsSchema,
  T as SessionsCatalogReadParams,
  _ as SessionsCatalogContinueParams,
  a as SessionCatalogDescriptorSchema,
  b as SessionsCatalogContinueResultSchema,
  c as SessionCatalogSchema,
  d as SessionCatalogTranscriptItem,
  f as SessionCatalogTranscriptItemSchema,
  g as SessionsCatalogArchiveResultSchema,
  h as SessionsCatalogArchiveResult,
  i as SessionCatalogDescriptor,
  l as SessionCatalogSession,
  m as SessionsCatalogArchiveParamsSchema,
  n as SessionCatalogCapabilities,
  o as SessionCatalogHost,
  p as SessionsCatalogArchiveParams,
  r as SessionCatalogCapabilitiesSchema,
  s as SessionCatalogHostSchema,
  t as SessionCatalog,
  u as SessionCatalogSessionSchema,
  v as SessionsCatalogContinueParamsSchema,
  w as SessionsCatalogListResultSchema,
  x as SessionsCatalogListParams,
  y as SessionsCatalogContinueResult,
} from "../../sessions-catalog-DPwzj-x7.js";
import {
  $ as SessionsGroupsListParams,
  A as SessionsCreateResultSchema,
  B as SessionsFilesGetParamsSchema,
  C as SessionsCompactParams,
  Ct as SessionsSearchParamsSchema,
  D as SessionsCompactionListParamsSchema,
  Dt as SessionsUsageParams,
  E as SessionsCompactionGetParamsSchema,
  Et as SessionsSendParamsSchema,
  F as SessionsDiffParams,
  G as SessionsFilesListResult,
  H as SessionsFilesGetResultSchema,
  I as SessionsDiffParamsSchema,
  J as SessionsFilesSetParamsSchema,
  K as SessionsFilesListResultSchema,
  L as SessionsDiffResult,
  M as SessionsDeleteParamsSchema,
  N as SessionsDescribeParams,
  O as SessionsCompactionRestoreParamsSchema,
  Ot as SessionsUsageParamsSchema,
  P as SessionsDescribeParamsSchema,
  Q as SessionsGroupsDeleteParamsSchema,
  R as SessionsDiffResultSchema,
  S as SessionsCleanupParamsSchema,
  St as SessionsSearchParams,
  T as SessionsCompactionBranchParamsSchema,
  Tt as SessionsSearchResultSchema,
  U as SessionsFilesListParams,
  V as SessionsFilesGetResult,
  W as SessionsFilesListParamsSchema,
  X as SessionsFilesSetResultSchema,
  Y as SessionsFilesSetResult,
  Z as SessionsGroupsDeleteParams,
  _ as SessionOperationEvent,
  _t as SessionsResetParamsSchema,
  a as SessionFileBrowserEntry,
  at as SessionsGroupsPutParams,
  b as SessionsAbortParamsSchema,
  bt as SessionsSearchHit,
  c as SessionFileBrowserResultSchema,
  ct as SessionsGroupsRenameParamsSchema,
  d as SessionFileKind,
  dt as SessionsPatchParams,
  et as SessionsGroupsListParamsSchema,
  f as SessionFileKindSchema,
  ft as SessionsPatchParamsSchema,
  g as SessionGroupSchema,
  gt as SessionsResetParams,
  h as SessionGroup,
  ht as SessionsPreviewParamsSchema,
  i as SessionDiffFileStatusSchema,
  it as SessionsGroupsMutationResultSchema,
  j as SessionsDeleteParams,
  k as SessionsCreateResult,
  kt as SessionsCreateParamsSchema,
  l as SessionFileEntry,
  lt as SessionsListParams,
  m as SessionFileRelevanceSchema,
  mt as SessionsPreviewParams,
  n as SessionDiffFileSchema,
  nt as SessionsGroupsListResultSchema,
  o as SessionFileBrowserEntrySchema,
  ot as SessionsGroupsPutParamsSchema,
  p as SessionFileRelevance,
  pt as SessionsPluginPatchParamsSchema,
  q as SessionsFilesSetParams,
  r as SessionDiffFileStatus,
  rt as SessionsGroupsMutationResult,
  s as SessionFileBrowserResult,
  st as SessionsGroupsRenameParams,
  t as SessionDiffFile,
  tt as SessionsGroupsListResult,
  u as SessionFileEntrySchema,
  ut as SessionsListParamsSchema,
  v as SessionWorktreeInfo,
  vt as SessionsResolveParams,
  w as SessionsCompactParamsSchema,
  wt as SessionsSearchResult,
  x as SessionsCleanupParams,
  xt as SessionsSearchHitSchema,
  y as SessionWorktreeInfoSchema,
  yt as SessionsResolveParamsSchema,
  z as SessionsFilesGetParams,
} from "../../sessions-xbYJ30YJ.js";
export {
  type AgentEvent,
  AgentEventSchema,
  type AgentIdentityParams,
  AgentIdentityParamsSchema,
  type AgentIdentityResult,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  type AgentSummary,
  AgentSummarySchema,
  type AgentWaitParams,
  type AgentsCreateParams,
  AgentsCreateParamsSchema,
  type AgentsCreateResult,
  AgentsCreateResultSchema,
  type AgentsDeleteParams,
  AgentsDeleteParamsSchema,
  type AgentsDeleteResult,
  AgentsDeleteResultSchema,
  type AgentsFileEntry,
  AgentsFileEntrySchema,
  type AgentsFilesGetParams,
  AgentsFilesGetParamsSchema,
  type AgentsFilesGetResult,
  AgentsFilesGetResultSchema,
  type AgentsFilesListParams,
  AgentsFilesListParamsSchema,
  type AgentsFilesListResult,
  AgentsFilesListResultSchema,
  type AgentsFilesSetParams,
  AgentsFilesSetParamsSchema,
  type AgentsFilesSetResult,
  AgentsFilesSetResultSchema,
  type AgentsListParams,
  AgentsListParamsSchema,
  type AgentsListResult,
  AgentsListResultSchema,
  type AgentsUpdateParams,
  AgentsUpdateParamsSchema,
  type AgentsUpdateResult,
  AgentsUpdateResultSchema,
  type AgentsWorkspaceEntry,
  AgentsWorkspaceEntrySchema,
  type AgentsWorkspaceFile,
  AgentsWorkspaceFileSchema,
  type AgentsWorkspaceGetParams,
  AgentsWorkspaceGetParamsSchema,
  type AgentsWorkspaceGetResult,
  AgentsWorkspaceGetResultSchema,
  type AgentsWorkspaceListParams,
  AgentsWorkspaceListParamsSchema,
  type AgentsWorkspaceListResult,
  AgentsWorkspaceListResultSchema,
  type AllowedApprovalSnapshot,
  AllowedApprovalSnapshotSchema,
  type ApprovalAllowDecision,
  ApprovalAllowDecisionSchema,
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type ApprovalGetParams,
  ApprovalGetParamsSchema,
  type ApprovalGetResult,
  ApprovalGetResultSchema,
  type ApprovalKind,
  ApprovalKindSchema,
  type ApprovalPresentation,
  ApprovalPresentationSchema,
  type ApprovalResolveParams,
  ApprovalResolveParamsSchema,
  type ApprovalResolveResult,
  ApprovalResolveResultSchema,
  type ApprovalSnapshot,
  ApprovalSnapshotSchema,
  type ApprovalTerminalReason,
  ApprovalTerminalReasonSchema,
  type ArtifactSummary,
  ArtifactSummarySchema,
  type ArtifactsDownloadParams,
  ArtifactsDownloadParamsSchema,
  type ArtifactsDownloadResult,
  type ArtifactsGetParams,
  ArtifactsGetParamsSchema,
  type ArtifactsGetResult,
  type ArtifactsListParams,
  ArtifactsListParamsSchema,
  type ArtifactsListResult,
  type AuditActivityAgentRunV1,
  AuditActivityAgentRunV1Schema,
  type AuditActivityEventV1,
  AuditActivityEventV1Schema,
  type AuditActivityInboundMessageV1,
  AuditActivityInboundMessageV1Schema,
  type AuditActivityListParams,
  AuditActivityListParamsSchema,
  type AuditActivityListResult,
  AuditActivityListResultSchema,
  type AuditActivityOutboundMessageV1,
  AuditActivityOutboundMessageV1Schema,
  type AuditActivityToolActionV1,
  AuditActivityToolActionV1Schema,
  type AuditEvent,
  AuditEventSchema,
  type AuditListParams,
  AuditListParamsSchema,
  type AuditListResult,
  AuditListResultSchema,
  type AuthProbeStatus,
  AuthProbeStatusSchema,
  type CancelledApprovalSnapshot,
  CancelledApprovalSnapshotSchema,
  type ChannelsLogoutParams,
  ChannelsLogoutParamsSchema,
  type ChannelsStartParams,
  ChannelsStartParamsSchema,
  type ChannelsStatusParams,
  ChannelsStatusParamsSchema,
  type ChannelsStatusResult,
  ChannelsStatusResultSchema,
  type ChannelsStopParams,
  ChannelsStopParamsSchema,
  type ChatEvent,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  type ChatInjectParams,
  ChatInjectParamsSchema,
  type ChatMetadataParams,
  ChatMetadataParamsSchema,
  ChatSendParamsSchema,
  type ChatToolTitlesParams,
  ChatToolTitlesParamsSchema,
  type ChatToolTitlesResult,
  ChatToolTitlesResultSchema,
  ClawHubTrustErrorCode,
  ClawHubTrustErrorCodes,
  ClawHubTrustErrorDetails,
  type CommandEntry,
  type CommandsListParams,
  CommandsListParamsSchema,
  type CommandsListResult,
  CommandsListResultSchema,
  type ConfigApplyParams,
  ConfigApplyParamsSchema,
  type ConfigGetParams,
  ConfigGetParamsSchema,
  type ConfigPatchParams,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  type ConfigSchemaParams,
  ConfigSchemaParamsSchema,
  type ConfigSchemaResponse,
  ConfigSchemaResponseSchema,
  type ConfigSetParams,
  ConfigSetParamsSchema,
  type ConnectParams,
  ConnectParamsSchema,
  type CrestodianChatParams,
  CrestodianChatParamsSchema,
  type CrestodianChatResult,
  CrestodianChatResultSchema,
  type CrestodianSetupActivateParams,
  CrestodianSetupActivateParamsSchema,
  type CrestodianSetupActivateResult,
  CrestodianSetupActivateResultSchema,
  type CrestodianSetupAuthStartParams,
  CrestodianSetupAuthStartParamsSchema,
  type CrestodianSetupAuthStartResult,
  CrestodianSetupAuthStartResultSchema,
  type CrestodianSetupDetectParams,
  CrestodianSetupDetectParamsSchema,
  type CrestodianSetupDetectResult,
  CrestodianSetupDetectResultSchema,
  type CrestodianSetupVerifyParams,
  CrestodianSetupVerifyParamsSchema,
  type CrestodianSetupVerifyResult,
  CrestodianSetupVerifyResultSchema,
  type CronAddParams,
  CronAddParamsSchema,
  type CronAddResult,
  CronAddResultSchema,
  type CronDeclarativeAddResult,
  CronDeclarativeAddResultSchema,
  type CronGetParams,
  CronGetParamsSchema,
  type CronJob,
  CronJobSchema,
  type CronListParams,
  CronListParamsSchema,
  type CronRemoveParams,
  CronRemoveParamsSchema,
  type CronRunLogEntry,
  type CronRunParams,
  CronRunParamsSchema,
  type CronRunsParams,
  CronRunsParamsSchema,
  type CronStatusParams,
  CronStatusParamsSchema,
  type CronUpdateParams,
  CronUpdateParamsSchema,
  type DeniedApprovalSnapshot,
  DeniedApprovalSnapshotSchema,
  type DevicePairApproveParams,
  type DevicePairListParams,
  type DevicePairRejectParams,
  type DevicePairRenameParams,
  type DevicePairSetupCodeParams,
  type DevicePairSetupCodeResult,
  type EnvironmentStatus,
  EnvironmentStatusSchema,
  type EnvironmentSummary,
  EnvironmentSummarySchema,
  type EnvironmentsCreateParams,
  EnvironmentsCreateParamsSchema,
  type EnvironmentsCreateResult,
  EnvironmentsCreateResultSchema,
  type EnvironmentsDestroyParams,
  EnvironmentsDestroyParamsSchema,
  type EnvironmentsDestroyResult,
  EnvironmentsDestroyResultSchema,
  type EnvironmentsListParams,
  EnvironmentsListParamsSchema,
  type EnvironmentsListResult,
  EnvironmentsListResultSchema,
  type EnvironmentsStatusParams,
  EnvironmentsStatusParamsSchema,
  type EnvironmentsStatusResult,
  EnvironmentsStatusResultSchema,
  ErrorCodes,
  type ErrorShape,
  ErrorShapeSchema,
  type EventFrame,
  EventFrameSchema,
  type ExecApprovalGetParams,
  ExecApprovalGetParamsSchema,
  type ExecApprovalPresentation,
  ExecApprovalPresentationSchema,
  type ExecApprovalRequestParams,
  ExecApprovalRequestParamsSchema,
  type ExecApprovalResolveParams,
  ExecApprovalResolveParamsSchema,
  type ExecApprovalsGetParams,
  ExecApprovalsGetParamsSchema,
  type ExecApprovalsNodeSnapshot,
  type ExecApprovalsSetParams,
  ExecApprovalsSetParamsSchema,
  type ExecApprovalsSnapshot,
  type ExpiredApprovalSnapshot,
  ExpiredApprovalSnapshotSchema,
  type FsDirEntry,
  FsDirEntrySchema,
  type FsListDirParams,
  FsListDirParamsSchema,
  type FsListDirResult,
  FsListDirResultSchema,
  GATEWAY_SERVER_CAPS,
  type GatewayFrame,
  GatewayFrameSchema,
  type GatewaySuspendBlocker,
  GatewaySuspendBlockerSchema,
  GatewaySuspendPrepareBusyResultSchema,
  type GatewaySuspendPrepareParams,
  GatewaySuspendPrepareParamsSchema,
  GatewaySuspendPrepareReadyResultSchema,
  type GatewaySuspendPrepareResult,
  GatewaySuspendPrepareResultSchema,
  type GatewaySuspendResumeParams,
  GatewaySuspendResumeParamsSchema,
  type GatewaySuspendResumeResult,
  GatewaySuspendResumeResultSchema,
  type GatewaySuspendStatusParams,
  GatewaySuspendStatusParamsSchema,
  GatewaySuspendStatusReadyResultSchema,
  type GatewaySuspendStatusResult,
  GatewaySuspendStatusResultSchema,
  GatewaySuspendStatusRunningResultSchema,
  type GatewaySuspendTaskBlocker,
  GatewaySuspendTaskBlockerSchema,
  type HelloOk,
  HelloOkSchema,
  type LogsTailParams,
  LogsTailParamsSchema,
  type LogsTailResult,
  LogsTailResultSchema,
  MAX_MEMORY_MIGRATION_ITEMS,
  MIN_CLIENT_PROTOCOL_VERSION,
  MIN_NODE_PROTOCOL_VERSION,
  MIN_PROBE_PROTOCOL_VERSION,
  MemoryMigrationItem,
  MemoryMigrationItemSchema,
  MemoryMigrationItemStatus,
  MemoryMigrationItemStatusSchema,
  MemoryMigrationProviderPlan,
  MemoryMigrationProviderPlanSchema,
  MemoryMigrationSummarySchema,
  MessageActionParamsSchema,
  MigrationProtocolSchemas,
  MigrationsMemoryApplyParams,
  MigrationsMemoryApplyParamsSchema,
  MigrationsMemoryApplyResult,
  MigrationsMemoryApplyResultSchema,
  MigrationsMemoryPlanParams,
  MigrationsMemoryPlanParamsSchema,
  MigrationsMemoryPlanResult,
  MigrationsMemoryPlanResultSchema,
  ModelsListParamsSchema,
  type ModelsProbeParams,
  ModelsProbeParamsSchema,
  type ModelsProbeResult,
  ModelsProbeResultSchema,
  type ModelsProbeTargetResult,
  ModelsProbeTargetResultSchema,
  type NodeEventParams,
  type NodeEventResult,
  NodeEventResultSchema,
  type NodeInvokeInputEvent,
  NodeInvokeInputEventSchema,
  type NodeInvokeParams,
  NodeInvokeParamsSchema,
  type NodeInvokeProgressParams,
  NodeInvokeProgressParamsSchema,
  type NodeInvokeResultParams,
  type NodeListParams,
  NodeListParamsSchema,
  type NodePairApproveParams,
  NodePairApproveParamsSchema,
  type NodePairListParams,
  NodePairListParamsSchema,
  type NodePairRejectParams,
  NodePairRejectParamsSchema,
  type NodePairRemoveParams,
  NodePairRemoveParamsSchema,
  NodePendingAckParamsSchema,
  type NodePendingDrainParams,
  NodePendingDrainParamsSchema,
  type NodePendingDrainResult,
  NodePendingDrainResultSchema,
  type NodePendingEnqueueParams,
  NodePendingEnqueueParamsSchema,
  type NodePendingEnqueueResult,
  NodePendingEnqueueResultSchema,
  type NodePluginToolDescriptor,
  NodePluginToolDescriptorSchema,
  type NodePluginToolsUpdateParams,
  NodePluginToolsUpdateParamsSchema,
  type NodePresenceActivityPayload,
  NodePresenceActivityPayloadSchema,
  type NodePresenceAlivePayload,
  NodePresenceAlivePayloadSchema,
  type NodePresenceAliveReason,
  NodePresenceAliveReasonSchema,
  type NodeSkillDescriptor,
  NodeSkillDescriptorSchema,
  type NodeSkillsUpdateParams,
  NodeSkillsUpdateParamsSchema,
  PROTOCOL_VERSION,
  type PendingApprovalSnapshot,
  PendingApprovalSnapshotSchema,
  type PluginApprovalPresentation,
  PluginApprovalPresentationSchema,
  type PluginApprovalSeverity,
  PluginApprovalSeveritySchema,
  type PluginCatalogEntry,
  PluginCatalogEntrySchema,
  PluginCatalogInstallActionSchema,
  PluginSearchPackageSchema,
  PluginSearchResultEntrySchema,
  type PluginsInstallParams,
  PluginsInstallParamsSchema,
  type PluginsInstallResult,
  PluginsInstallResultSchema,
  type PluginsListParams,
  PluginsListParamsSchema,
  type PluginsListResult,
  PluginsListResultSchema,
  type PluginsSearchParams,
  PluginsSearchParamsSchema,
  type PluginsSearchResult,
  PluginsSearchResultSchema,
  type PluginsSessionActionParams,
  PluginsSessionActionParamsSchema,
  type PluginsSessionActionResult,
  PluginsSessionActionResultSchema,
  type PluginsSetEnabledParams,
  PluginsSetEnabledParamsSchema,
  type PluginsSetEnabledResult,
  PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResultSchema,
  type PluginsUninstallParams,
  PluginsUninstallParamsSchema,
  type PluginsUninstallResult,
  PluginsUninstallResultSchema,
  type PollParams,
  PollParamsSchema,
  type PresenceEntry,
  PresenceEntrySchema,
  type ProtocolValidator,
  PushTestParamsSchema,
  PushTestResultSchema,
  type RequestFrame,
  RequestFrameSchema,
  type ResponseFrame,
  ResponseFrameSchema,
  SendParamsSchema,
  type SessionApprovalEvent,
  SessionApprovalEventSchema,
  type SessionApprovalReplay,
  SessionApprovalReplaySchema,
  type SessionCatalog,
  type SessionCatalogCapabilities,
  SessionCatalogCapabilitiesSchema,
  type SessionCatalogDescriptor,
  SessionCatalogDescriptorSchema,
  type SessionCatalogHost,
  SessionCatalogHostSchema,
  SessionCatalogSchema,
  type SessionCatalogSession,
  SessionCatalogSessionSchema,
  type SessionCatalogTranscriptItem,
  SessionCatalogTranscriptItemSchema,
  type SessionDiffFile,
  SessionDiffFileSchema,
  type SessionDiffFileStatus,
  SessionDiffFileStatusSchema,
  type SessionFileBrowserEntry,
  SessionFileBrowserEntrySchema,
  type SessionFileBrowserResult,
  SessionFileBrowserResultSchema,
  type SessionFileEntry,
  SessionFileEntrySchema,
  type SessionFileKind,
  SessionFileKindSchema,
  type SessionFileRelevance,
  SessionFileRelevanceSchema,
  type SessionGroup,
  SessionGroupSchema,
  type SessionOperationEvent,
  type SessionPlacement,
  SessionPlacementSchema,
  type SessionPlacementState,
  SessionPlacementStateSchema,
  type SessionWorktreeInfo,
  SessionWorktreeInfoSchema,
  SessionsAbortParamsSchema,
  type SessionsCatalogArchiveParams,
  SessionsCatalogArchiveParamsSchema,
  type SessionsCatalogArchiveResult,
  SessionsCatalogArchiveResultSchema,
  type SessionsCatalogContinueParams,
  SessionsCatalogContinueParamsSchema,
  type SessionsCatalogContinueResult,
  SessionsCatalogContinueResultSchema,
  type SessionsCatalogListParams,
  SessionsCatalogListParamsSchema,
  type SessionsCatalogListResult,
  SessionsCatalogListResultSchema,
  type SessionsCatalogReadParams,
  SessionsCatalogReadParamsSchema,
  type SessionsCatalogReadResult,
  SessionsCatalogReadResultSchema,
  type SessionsCleanupParams,
  SessionsCleanupParamsSchema,
  type SessionsCompactParams,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCreateParamsSchema,
  type SessionsCreateResult,
  SessionsCreateResultSchema,
  type SessionsDeleteParams,
  SessionsDeleteParamsSchema,
  type SessionsDescribeParams,
  SessionsDescribeParamsSchema,
  type SessionsDiffParams,
  SessionsDiffParamsSchema,
  type SessionsDiffResult,
  SessionsDiffResultSchema,
  type SessionsDispatchParams,
  SessionsDispatchParamsSchema,
  type SessionsDispatchResult,
  SessionsDispatchResultSchema,
  type SessionsFilesGetParams,
  SessionsFilesGetParamsSchema,
  type SessionsFilesGetResult,
  SessionsFilesGetResultSchema,
  type SessionsFilesListParams,
  SessionsFilesListParamsSchema,
  type SessionsFilesListResult,
  SessionsFilesListResultSchema,
  type SessionsFilesSetParams,
  SessionsFilesSetParamsSchema,
  type SessionsFilesSetResult,
  SessionsFilesSetResultSchema,
  type SessionsGroupsDeleteParams,
  SessionsGroupsDeleteParamsSchema,
  type SessionsGroupsListParams,
  SessionsGroupsListParamsSchema,
  type SessionsGroupsListResult,
  SessionsGroupsListResultSchema,
  type SessionsGroupsMutationResult,
  SessionsGroupsMutationResultSchema,
  type SessionsGroupsPutParams,
  SessionsGroupsPutParamsSchema,
  type SessionsGroupsRenameParams,
  SessionsGroupsRenameParamsSchema,
  type SessionsListParams,
  SessionsListParamsSchema,
  type SessionsPatchParams,
  SessionsPatchParamsSchema,
  SessionsPatchResult,
  SessionsPluginPatchParamsSchema,
  type SessionsPreviewParams,
  SessionsPreviewParamsSchema,
  type SessionsResetParams,
  SessionsResetParamsSchema,
  type SessionsResolveParams,
  SessionsResolveParamsSchema,
  type SessionsSearchHit,
  SessionsSearchHitSchema,
  type SessionsSearchParams,
  SessionsSearchParamsSchema,
  type SessionsSearchResult,
  SessionsSearchResultSchema,
  SessionsSendParamsSchema,
  type SessionsUsageParams,
  SessionsUsageParamsSchema,
  type ShutdownEvent,
  ShutdownEventSchema,
  type SkillsBinsParams,
  type SkillsBinsResult,
  type SkillsCuratorActionParams,
  SkillsCuratorActionParamsSchema,
  type SkillsCuratorActionResult,
  SkillsCuratorActionResultSchema,
  type SkillsCuratorStatusParams,
  SkillsCuratorStatusParamsSchema,
  type SkillsCuratorStatusResult,
  SkillsCuratorStatusResultSchema,
  type SkillsDetailParams,
  SkillsDetailParamsSchema,
  type SkillsDetailResult,
  SkillsDetailResultSchema,
  type SkillsInstallParams,
  SkillsInstallParamsSchema,
  type SkillsProposalActionParams,
  SkillsProposalActionParamsSchema,
  type SkillsProposalApplyResult,
  SkillsProposalApplyResultSchema,
  type SkillsProposalCreateParams,
  SkillsProposalCreateParamsSchema,
  SkillsProposalHistoryScanParams,
  SkillsProposalHistoryScanParamsSchema,
  SkillsProposalHistoryScanResult,
  SkillsProposalHistoryScanResultSchema,
  SkillsProposalHistoryStatusParams,
  SkillsProposalHistoryStatusParamsSchema,
  type SkillsProposalInspectParams,
  SkillsProposalInspectParamsSchema,
  type SkillsProposalInspectResult,
  SkillsProposalInspectResultSchema,
  type SkillsProposalRecordResult,
  SkillsProposalRecordResultSchema,
  type SkillsProposalRequestRevisionParams,
  SkillsProposalRequestRevisionParamsSchema,
  type SkillsProposalRequestRevisionResult,
  SkillsProposalRequestRevisionResultSchema,
  type SkillsProposalReviseParams,
  SkillsProposalReviseParamsSchema,
  type SkillsProposalUpdateParams,
  SkillsProposalUpdateParamsSchema,
  type SkillsProposalsListParams,
  SkillsProposalsListParamsSchema,
  type SkillsProposalsListResult,
  SkillsProposalsListResultSchema,
  type SkillsSearchParams,
  SkillsSearchParamsSchema,
  type SkillsSearchResult,
  SkillsSearchResultSchema,
  type SkillsSecurityVerdictsParams,
  SkillsSecurityVerdictsParamsSchema,
  type SkillsSecurityVerdictsResult,
  SkillsSecurityVerdictsResultSchema,
  type SkillsSkillCardParams,
  SkillsSkillCardParamsSchema,
  type SkillsSkillCardResult,
  SkillsSkillCardResultSchema,
  type SkillsStatusParams,
  SkillsStatusParamsSchema,
  type SkillsUpdateParams,
  SkillsUpdateParamsSchema,
  type SkillsUploadBeginParams,
  SkillsUploadBeginParamsSchema,
  type SkillsUploadChunkParams,
  SkillsUploadChunkParamsSchema,
  type SkillsUploadCommitParams,
  SkillsUploadCommitParamsSchema,
  type Snapshot,
  SnapshotSchema,
  type StateVersion,
  StateVersionSchema,
  type SystemInfoParams,
  SystemInfoParamsSchema,
  type SystemInfoResult,
  SystemInfoResultSchema,
  type TalkAgentControlResult,
  TalkAgentControlResultSchema,
  type TalkCatalogParams,
  TalkCatalogParamsSchema,
  type TalkCatalogResult,
  TalkCatalogResultSchema,
  type TalkClientCreateParams,
  TalkClientCreateParamsSchema,
  type TalkClientCreateResult,
  TalkClientCreateResultSchema,
  type TalkClientSteerParams,
  TalkClientSteerParamsSchema,
  type TalkClientToolCallParams,
  TalkClientToolCallParamsSchema,
  type TalkClientToolCallResult,
  TalkClientToolCallResultSchema,
  type TalkConfigParams,
  TalkConfigParamsSchema,
  type TalkConfigResult,
  TalkConfigResultSchema,
  TalkEventSchema,
  type TalkModeParams,
  type TalkSessionAcknowledgeMarkParams,
  TalkSessionAcknowledgeMarkParamsSchema,
  type TalkSessionAppendAudioParams,
  TalkSessionAppendAudioParamsSchema,
  type TalkSessionCancelOutputParams,
  TalkSessionCancelOutputParamsSchema,
  type TalkSessionCancelTurnParams,
  TalkSessionCancelTurnParamsSchema,
  type TalkSessionCloseParams,
  TalkSessionCloseParamsSchema,
  type TalkSessionCreateParams,
  TalkSessionCreateParamsSchema,
  type TalkSessionCreateResult,
  TalkSessionCreateResultSchema,
  type TalkSessionJoinParams,
  TalkSessionJoinParamsSchema,
  type TalkSessionJoinResult,
  TalkSessionJoinResultSchema,
  type TalkSessionOkResult,
  TalkSessionOkResultSchema,
  type TalkSessionSteerParams,
  TalkSessionSteerParamsSchema,
  type TalkSessionSubmitToolResultParams,
  TalkSessionSubmitToolResultParamsSchema,
  type TalkSessionTurnParams,
  TalkSessionTurnParamsSchema,
  type TalkSessionTurnResult,
  TalkSessionTurnResultSchema,
  type TalkSpeakParams,
  TalkSpeakParamsSchema,
  type TalkSpeakResult,
  TalkSpeakResultSchema,
  type TaskSuggestion,
  type TaskSuggestionEvent,
  TaskSuggestionEventSchema,
  type TaskSuggestionResolution,
  TaskSuggestionResolutionSchema,
  TaskSuggestionSchema,
  type TaskSuggestionsAcceptParams,
  TaskSuggestionsAcceptParamsSchema,
  type TaskSuggestionsAcceptResult,
  TaskSuggestionsAcceptResultSchema,
  type TaskSuggestionsCreateParams,
  TaskSuggestionsCreateParamsSchema,
  type TaskSuggestionsCreateResult,
  TaskSuggestionsCreateResultSchema,
  type TaskSuggestionsDismissParams,
  TaskSuggestionsDismissParamsSchema,
  type TaskSuggestionsDismissResult,
  TaskSuggestionsDismissResultSchema,
  type TaskSuggestionsListParams,
  TaskSuggestionsListParamsSchema,
  type TaskSuggestionsListResult,
  TaskSuggestionsListResultSchema,
  type TaskSummary,
  TaskSummarySchema,
  type TasksCancelParams,
  TasksCancelParamsSchema,
  type TasksCancelResult,
  TasksCancelResultSchema,
  type TasksGetParams,
  TasksGetParamsSchema,
  type TasksGetResult,
  TasksGetResultSchema,
  type TasksListParams,
  TasksListParamsSchema,
  type TasksListResult,
  TasksListResultSchema,
  type TerminalAckResult,
  TerminalAckResultSchema,
  type TerminalApprovalSnapshot,
  TerminalApprovalSnapshotSchema,
  type TerminalAttachParams,
  TerminalAttachParamsSchema,
  type TerminalAttachResult,
  TerminalAttachResultSchema,
  type TerminalCloseParams,
  TerminalCloseParamsSchema,
  type TerminalDataEvent,
  TerminalDataEventSchema,
  type TerminalEvent,
  TerminalEventSchema,
  type TerminalExitEvent,
  TerminalExitEventSchema,
  type TerminalInputParams,
  TerminalInputParamsSchema,
  type TerminalListResult,
  TerminalListResultSchema,
  type TerminalOpenParams,
  TerminalOpenParamsSchema,
  type TerminalOpenResult,
  TerminalOpenResultSchema,
  type TerminalResizeParams,
  TerminalResizeParamsSchema,
  type TerminalSessionInfo,
  TerminalSessionInfoSchema,
  type TerminalTextParams,
  TerminalTextParamsSchema,
  type TerminalTextResult,
  TerminalTextResultSchema,
  type TickEvent,
  TickEventSchema,
  type ToolsCatalogParams,
  ToolsCatalogParamsSchema,
  type ToolsCatalogResult,
  type ToolsEffectiveParams,
  ToolsEffectiveParamsSchema,
  type ToolsEffectiveResult,
  type ToolsInvokeParams,
  ToolsInvokeParamsSchema,
  type ToolsInvokeResult,
  type TtsSpeakParams,
  TtsSpeakParamsSchema,
  type TtsSpeakResult,
  TtsSpeakResultSchema,
  type UpdateRunParams,
  UpdateRunParamsSchema,
  type UpdateStatusParams,
  UpdateStatusParamsSchema,
  type ValidationError,
  WORKER_HEARTBEAT_INTERVAL_MS,
  WORKER_INFERENCE_MAX_CONTEXT_MESSAGES,
  WORKER_INFERENCE_MAX_OUTPUT_TOKENS,
  WORKER_INFERENCE_MAX_TOOLS,
  WORKER_INFERENCE_METHODS,
  WORKER_INFERENCE_PROTOCOL_FEATURE,
  WORKER_LIVE_EVENT_PROTOCOL_FEATURE,
  WORKER_PROTOCOL_FEATURES,
  WORKER_PROTOCOL_MAX_FEATURES,
  WORKER_PROTOCOL_MAX_FEATURE_LENGTH,
  WORKER_PROTOCOL_MAX_FRAME_ID_LENGTH,
  WORKER_PROTOCOL_MAX_IDENTIFIER_LENGTH,
  WORKER_PROTOCOL_MAX_INFERENCE_PAYLOAD_BYTES,
  WORKER_PROTOCOL_MAX_METHOD_LENGTH,
  WORKER_PROTOCOL_MAX_PAYLOAD_BYTES,
  WORKER_PROTOCOL_METHODS,
  WORKER_RPC_SET_VERSION,
  WORKER_TRANSCRIPT_COMMIT_PROTOCOL_FEATURE,
  WORKER_TRANSCRIPT_MAX_BATCH_MESSAGES,
  WORKER_TRANSCRIPT_MAX_CONTENT_PARTS,
  WORKER_TRANSCRIPT_MAX_JSON_DEPTH,
  type WakeParams,
  WakeParamsSchema,
  type WebLoginStartParams,
  WebLoginStartParamsSchema,
  type WebLoginWaitParams,
  WebLoginWaitParamsSchema,
  type WebPushSubscribeParams,
  WebPushSubscribeParamsSchema,
  type WebPushTestParams,
  WebPushTestParamsSchema,
  type WebPushUnsubscribeParams,
  WebPushUnsubscribeParamsSchema,
  type WebPushVapidPublicKeyParams,
  WebPushVapidPublicKeyParamsSchema,
  type WizardCancelParams,
  WizardCancelParamsSchema,
  type WizardNextParams,
  WizardNextParamsSchema,
  type WizardNextResult,
  WizardNextResultSchema,
  type WizardStartParams,
  WizardStartParamsSchema,
  type WizardStartResult,
  WizardStartResultSchema,
  type WizardStatusParams,
  WizardStatusParamsSchema,
  type WizardStatusResult,
  WizardStatusResultSchema,
  type WizardStep,
  WizardStepSchema,
  type WorkerAdmissionFailureReason,
  WorkerAdmissionFailureReasonSchema,
  type WorkerAdmissionHandshake,
  WorkerAdmissionHandshakeSchema,
  type WorkerAdmissionResponseFrame,
  WorkerAdmissionResponseFrameSchema,
  type WorkerConnectParams,
  type WorkerConnectRequestFrame,
  WorkerConnectRequestFrameSchema,
  type WorkerEnvironmentMetadata,
  WorkerEnvironmentMetadataSchema,
  type WorkerEnvironmentState,
  WorkerEnvironmentStateSchema,
  type WorkerErrorShape,
  type WorkerHeartbeatParams,
  WorkerHeartbeatParamsSchema,
  type WorkerHeartbeatRequestFrame,
  WorkerHeartbeatRequestFrameSchema,
  type WorkerHeartbeatResponseFrame,
  WorkerHeartbeatResponseFrameSchema,
  type WorkerHeartbeatResult,
  type WorkerHelloOk,
  WorkerInferenceCancelParams,
  WorkerInferenceCancelParamsSchema,
  WorkerInferenceCancelRequestFrame,
  WorkerInferenceCancelRequestFrameSchema,
  WorkerInferenceCancelResponseFrame,
  WorkerInferenceCancelResponseFrameSchema,
  WorkerInferenceCancelResult,
  WorkerInferenceCancelResultSchema,
  WorkerInferenceContext,
  WorkerInferenceContextSchema,
  WorkerInferenceErrorReason,
  WorkerInferenceErrorReasonSchema,
  WorkerInferenceErrorShape,
  WorkerInferenceErrorShapeSchema,
  WorkerInferenceEventFrame,
  WorkerInferenceEventFrameSchema,
  WorkerInferenceEventParams,
  WorkerInferenceEventParamsSchema,
  WorkerInferenceModelRef,
  WorkerInferenceModelRefSchema,
  WorkerInferenceOptions,
  WorkerInferenceOptionsSchema,
  WorkerInferenceResolvedModel,
  WorkerInferenceResolvedModelSchema,
  WorkerInferenceStartParams,
  WorkerInferenceStartParamsSchema,
  WorkerInferenceStartRequestFrame,
  WorkerInferenceStartRequestFrameSchema,
  WorkerInferenceStartResponseFrame,
  WorkerInferenceStartResponseFrameSchema,
  WorkerInferenceStartResult,
  WorkerInferenceStartResultSchema,
  WorkerInferenceTerminalFrame,
  WorkerInferenceTerminalFrameSchema,
  WorkerInferenceTerminalOutcome,
  WorkerInferenceTerminalOutcomeSchema,
  WorkerInferenceTerminalParams,
  WorkerInferenceTerminalParamsSchema,
  type WorkerLiveEvent,
  type WorkerLiveEventErrorDetails,
  WorkerLiveEventErrorDetailsSchema,
  type WorkerLiveEventErrorShape,
  WorkerLiveEventErrorShapeSchema,
  type WorkerLiveEventParams,
  WorkerLiveEventParamsSchema,
  type WorkerLiveEventRequestFrame,
  WorkerLiveEventRequestFrameSchema,
  type WorkerLiveEventResponseFrame,
  WorkerLiveEventResponseFrameSchema,
  type WorkerLiveEventResult,
  WorkerLiveEventResultSchema,
  WorkerLiveEventSchema,
  type WorkerProtocolCloseReason,
  WorkerProtocolCloseReasonSchema,
  type WorkerTranscriptCommitErrorReason,
  WorkerTranscriptCommitErrorReasonSchema,
  type WorkerTranscriptCommitErrorShape,
  WorkerTranscriptCommitErrorShapeSchema,
  type WorkerTranscriptCommitParams,
  WorkerTranscriptCommitParamsSchema,
  type WorkerTranscriptCommitRequestFrame,
  WorkerTranscriptCommitRequestFrameSchema,
  type WorkerTranscriptCommitResponseFrame,
  WorkerTranscriptCommitResponseFrameSchema,
  type WorkerTranscriptCommitResult,
  WorkerTranscriptCommitResultSchema,
  type WorkerTranscriptMessage,
  WorkerTranscriptMessageSchema,
  type WorkerTunnelStatus,
  WorkerTunnelStatusSchema,
  type WorktreeBranch,
  WorktreeBranchSchema,
  type WorktreeRecord,
  WorktreeRecordSchema,
  type WorktreesBranchesParams,
  WorktreesBranchesParamsSchema,
  type WorktreesBranchesResult,
  WorktreesBranchesResultSchema,
  type WorktreesCreateParams,
  WorktreesCreateParamsSchema,
  type WorktreesGcParams,
  WorktreesGcParamsSchema,
  type WorktreesGcResult,
  WorktreesGcResultSchema,
  type WorktreesListParams,
  WorktreesListParamsSchema,
  type WorktreesListResult,
  WorktreesListResultSchema,
  type WorktreesRemoveParams,
  WorktreesRemoveParamsSchema,
  type WorktreesRemoveResult,
  WorktreesRemoveResultSchema,
  type WorktreesRestoreParams,
  WorktreesRestoreParamsSchema,
  buildClawHubTrustErrorDetails,
  errorShape,
  formatValidationErrors,
  isClawHubTrustErrorCode,
  isWellFormedApprovalId,
  readClawHubTrustErrorDetails,
  validateAgentIdentityParams,
  validateAgentParams,
  validateAgentWaitParams,
  validateAgentsCreateParams,
  validateAgentsDeleteParams,
  validateAgentsFilesGetParams,
  validateAgentsFilesListParams,
  validateAgentsFilesSetParams,
  validateAgentsListParams,
  validateAgentsUpdateParams,
  validateAgentsWorkspaceGetParams,
  validateAgentsWorkspaceListParams,
  validateAllowedApprovalSnapshot,
  validateApprovalAllowDecision,
  validateApprovalDecision,
  validateApprovalGetParams,
  validateApprovalGetResult,
  validateApprovalKind,
  validateApprovalPresentation,
  validateApprovalResolveParams,
  validateApprovalResolveResult,
  validateApprovalSnapshot,
  validateApprovalTerminalReason,
  validateArtifactsDownloadParams,
  validateArtifactsGetParams,
  validateArtifactsListParams,
  validateAuditActivityListParams,
  validateAuditListParams,
  validateCancelledApprovalSnapshot,
  validateChannelsLogoutParams,
  validateChannelsStartParams,
  validateChannelsStatusParams,
  validateChannelsStopParams,
  validateChatAbortParams,
  validateChatEvent,
  validateChatHistoryParams,
  validateChatInjectParams,
  validateChatMessageGetParams,
  validateChatMessageGetResult,
  validateChatMetadataParams,
  validateChatSendParams,
  validateChatToolTitlesParams,
  validateCommandsListParams,
  validateConfigApplyParams,
  validateConfigGetParams,
  validateConfigPatchParams,
  validateConfigSchemaLookupParams,
  validateConfigSchemaLookupResult,
  validateConfigSchemaParams,
  validateConfigSetParams,
  validateConnectParams,
  validateCrestodianChatParams,
  validateCrestodianSetupActivateParams,
  validateCrestodianSetupAuthStartParams,
  validateCrestodianSetupDetectParams,
  validateCrestodianSetupVerifyParams,
  validateCronAddParams,
  validateCronGetParams,
  validateCronListParams,
  validateCronRemoveParams,
  validateCronRunParams,
  validateCronRunsParams,
  validateCronStatusParams,
  validateCronUpdateParams,
  validateDeniedApprovalSnapshot,
  validateDevicePairApproveParams,
  validateDevicePairListParams,
  validateDevicePairRejectParams,
  validateDevicePairRemoveParams,
  validateDevicePairRenameParams,
  validateDevicePairSetupCodeParams,
  validateDeviceTokenRevokeParams,
  validateDeviceTokenRotateParams,
  validateEnvironmentsCreateParams,
  validateEnvironmentsDestroyParams,
  validateEnvironmentsListParams,
  validateEnvironmentsStatusParams,
  validateEventFrame,
  validateExecApprovalGetParams,
  validateExecApprovalPresentation,
  validateExecApprovalRequestParams,
  validateExecApprovalResolveParams,
  validateExecApprovalsGetParams,
  validateExecApprovalsNodeGetParams,
  validateExecApprovalsNodeSetParams,
  validateExecApprovalsNodeSnapshot,
  validateExecApprovalsSetParams,
  validateExpiredApprovalSnapshot,
  validateFsListDirParams,
  validateFsListDirResult,
  validateGatewaySuspendPrepareParams,
  validateGatewaySuspendPrepareResult,
  validateGatewaySuspendResumeParams,
  validateGatewaySuspendResumeResult,
  validateGatewaySuspendStatusParams,
  validateGatewaySuspendStatusResult,
  validateLogsTailParams,
  validateMessageActionParams,
  validateMigrationsMemoryApplyParams,
  validateMigrationsMemoryPlanParams,
  validateModelsListParams,
  validateModelsProbeParams,
  validateNodeDescribeParams,
  validateNodeEventParams,
  validateNodeEventResult,
  validateNodeInvokeInputEvent,
  validateNodeInvokeParams,
  validateNodeInvokeProgressParams,
  validateNodeInvokeResultParams,
  validateNodeListParams,
  validateNodePairApproveParams,
  validateNodePairListParams,
  validateNodePairRejectParams,
  validateNodePairRemoveParams,
  validateNodePendingAckParams,
  validateNodePendingDrainParams,
  validateNodePendingEnqueueParams,
  validateNodePluginToolsUpdateParams,
  validateNodePresenceActivityPayload,
  validateNodePresenceAlivePayload,
  validateNodeRenameParams,
  validateNodeSkillsUpdateParams,
  validatePendingApprovalSnapshot,
  validatePluginApprovalPresentation,
  validatePluginApprovalRequestParams,
  validatePluginApprovalResolveParams,
  validatePluginApprovalSeverity,
  validatePluginsInstallParams,
  validatePluginsInstallResult,
  validatePluginsListParams,
  validatePluginsListResult,
  validatePluginsSearchParams,
  validatePluginsSearchResult,
  validatePluginsSessionActionParams,
  validatePluginsSessionActionResult,
  validatePluginsSetEnabledParams,
  validatePluginsSetEnabledResult,
  validatePluginsUiDescriptorsParams,
  validatePluginsUiDescriptorsResult,
  validatePluginsUninstallParams,
  validatePluginsUninstallResult,
  validatePollParams,
  validatePushTestParams,
  validateRequestFrame,
  validateResponseFrame,
  validateSecretsResolveParams,
  validateSecretsResolveResult,
  validateSendParams,
  validateSessionsAbortParams,
  validateSessionsCatalogArchiveParams,
  validateSessionsCatalogContinueParams,
  validateSessionsCatalogListParams,
  validateSessionsCatalogReadParams,
  validateSessionsCleanupParams,
  validateSessionsCompactParams,
  validateSessionsCompactionBranchParams,
  validateSessionsCompactionGetParams,
  validateSessionsCompactionListParams,
  validateSessionsCompactionRestoreParams,
  validateSessionsCreateParams,
  validateSessionsDeleteParams,
  validateSessionsDescribeParams,
  validateSessionsDiffParams,
  validateSessionsDispatchParams,
  validateSessionsDispatchResult,
  validateSessionsFilesGetParams,
  validateSessionsFilesListParams,
  validateSessionsFilesSetParams,
  validateSessionsGroupsDeleteParams,
  validateSessionsGroupsListParams,
  validateSessionsGroupsPutParams,
  validateSessionsGroupsRenameParams,
  validateSessionsListParams,
  validateSessionsMessagesSubscribeParams,
  validateSessionsMessagesUnsubscribeParams,
  validateSessionsPatchParams,
  validateSessionsPluginPatchParams,
  validateSessionsPreviewParams,
  validateSessionsResetParams,
  validateSessionsResolveParams,
  validateSessionsSearchParams,
  validateSessionsSearchResult,
  validateSessionsSendParams,
  validateSessionsUsageParams,
  validateSkillsBinsParams,
  validateSkillsCuratorActionParams,
  validateSkillsCuratorStatusParams,
  validateSkillsDetailParams,
  validateSkillsInstallParams,
  validateSkillsProposalActionParams,
  validateSkillsProposalCreateParams,
  validateSkillsProposalHistoryScanParams,
  validateSkillsProposalHistoryStatusParams,
  validateSkillsProposalInspectParams,
  validateSkillsProposalRequestRevisionParams,
  validateSkillsProposalReviseParams,
  validateSkillsProposalUpdateParams,
  validateSkillsProposalsListParams,
  validateSkillsSearchParams,
  validateSkillsSecurityVerdictsParams,
  validateSkillsSkillCardParams,
  validateSkillsStatusParams,
  validateSkillsUpdateParams,
  validateSkillsUploadBeginParams,
  validateSkillsUploadChunkParams,
  validateSkillsUploadCommitParams,
  validateSystemInfoParams,
  validateSystemInfoResult,
  validateTalkAgentControlResult,
  validateTalkCatalogParams,
  validateTalkCatalogResult,
  validateTalkClientCreateParams,
  validateTalkClientCreateResult,
  validateTalkClientSteerParams,
  validateTalkClientToolCallParams,
  validateTalkClientToolCallResult,
  validateTalkConfigParams,
  validateTalkConfigResult,
  validateTalkEvent,
  validateTalkModeParams,
  validateTalkSessionAcknowledgeMarkParams,
  validateTalkSessionAppendAudioParams,
  validateTalkSessionCancelOutputParams,
  validateTalkSessionCancelTurnParams,
  validateTalkSessionCloseParams,
  validateTalkSessionCreateParams,
  validateTalkSessionCreateResult,
  validateTalkSessionJoinParams,
  validateTalkSessionJoinResult,
  validateTalkSessionOkResult,
  validateTalkSessionSteerParams,
  validateTalkSessionSubmitToolResultParams,
  validateTalkSessionTurnParams,
  validateTalkSessionTurnResult,
  validateTalkSpeakParams,
  validateTalkSpeakResult,
  validateTaskSuggestionsAcceptParams,
  validateTaskSuggestionsCreateParams,
  validateTaskSuggestionsDismissParams,
  validateTaskSuggestionsListParams,
  validateTasksCancelParams,
  validateTasksGetParams,
  validateTasksListParams,
  validateTerminalApprovalSnapshot,
  validateTerminalAttachParams,
  validateTerminalCloseParams,
  validateTerminalEvent,
  validateTerminalInputParams,
  validateTerminalOpenParams,
  validateTerminalResizeParams,
  validateTerminalTextParams,
  validateToolsCatalogParams,
  validateToolsEffectiveParams,
  validateToolsInvokeParams,
  validateTtsSpeakParams,
  validateTtsSpeakResult,
  validateUpdateRunParams,
  validateUpdateStatusParams,
  validateWakeParams,
  validateWebLoginStartParams,
  validateWebLoginWaitParams,
  validateWebPushSubscribeParams,
  validateWebPushTestParams,
  validateWebPushUnsubscribeParams,
  validateWebPushVapidPublicKeyParams,
  validateWizardCancelParams,
  validateWizardNextParams,
  validateWizardStartParams,
  validateWizardStatusParams,
  validateWorkerAdmissionHandshake,
  validateWorkerConnectRequestFrame,
  validateWorkerHeartbeatParams,
  validateWorkerInferenceCancelParams,
  validateWorkerInferenceEventFrame,
  validateWorkerInferenceStartParams,
  validateWorkerInferenceTerminalFrame,
  validateWorkerInferenceTerminalOutcome,
  validateWorkerLiveEventParams,
  validateWorkerTranscriptCommitParams,
  validateWorktreesBranchesParams,
  validateWorktreesCreateParams,
  validateWorktreesGcParams,
  validateWorktreesListParams,
  validateWorktreesRemoveParams,
  validateWorktreesRestoreParams,
};
